### ISSUE TITLE
Invalid/corrupted items (?) causes chunk corruption/regen

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#1072]
### Issue description
On my PC imported map, after a few minutes using it the console starts spamming errors because it is trying to save a null item (wtf?) and, due those errors, Nukkit thinks the chunk is corrupted and  regenerates the chunk. A fix is creating a empty item (ID: 0) on NBTIO.java:30.

### Steps to reproduce the issue
1. I still don't have an exact way to reproduce, but on my case it started happening after I pregenerated a world in Paper 1.10.2 and then I imported it in Nukkit.

### OS and versions

* Nukkit: Not sure, but it was this commit: https://github.com/Nukkit/Nukkit/commit/369f6f7b0fd6f1015f5652df8d7569b2500f8a5b
* OS: Windows 10
* Device: PC

### Crashdump, backtrace or other files
```
Caused by: java.lang.NullPointerException
	at cn.nukkit.nbt.NBTIO.putItemHelper(NBTIO.java:30)
	at cn.nukkit.nbt.NBTIO.putItemHelper(NBTIO.java:25)
	at cn.nukkit.entity.item.EntityItem.saveNBT(EntityItem.java:184)
	at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:325)
	at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:143)
	at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:274)
	... 19 more
```

Here is what I done to fix the issue
```
    public static CompoundTag putItemHelper(Item item, Integer slot) {
    	// If the item is null, create a "dummy" item
    	if (item == null) {
            CompoundTag tag = new CompoundTag(null)
                    .putShort("id", 0)
                    .putByte("Count", 1)
                    .putShort("Damage", 0);
            if (slot != null) {
                tag.putByte("Slot", 0);
            }
            return tag;
    	}
        CompoundTag tag = new CompoundTag(null)
                .putShort("id", item.getId())
                .putByte("Count", item.getCount())
                .putShort("Damage", item.getDamage());
        if (slot != null) {
            tag.putByte("Slot", slot);
        }
```

**Comment by MrPowerGamerBR** [comment]
Here is a better stacktrace

```
12:06:08 [ALERT] java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at cn.nukkit.level.Level.saveChunks(Level.java:1115)
        at cn.nukkit.level.Level.save(Level.java:1098)
        at cn.nukkit.level.Level.save(Level.java:1082)
        at cn.nukkit.level.Level.close(Level.java:397)
        at cn.nukkit.level.Level.unload(Level.java:519)
        at cn.nukkit.Server.unloadLevel(Server.java:1533)
        at cn.nukkit.Server.forceShutdown(Server.java:719)
        at cn.nukkit.Server.start(Server.java:766)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:276)
        at cn.nukkit.level.Level.saveChunks(Level.java:1111)
        ... 9 more
Caused by: java.lang.NullPointerException
        at cn.nukkit.nbt.NBTIO.putItemHelper(NBTIO.java:30)
        at cn.nukkit.nbt.NBTIO.putItemHelper(NBTIO.java:25)
        at cn.nukkit.entity.item.EntityItem.saveNBT(EntityItem.java:184)
        at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:325)
        at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:143)
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:274)
        ... 10 more
```
