### ISSUE TITLE
How to get a RandomPlayer in Server?

### ISSUE THREAD

**Issue by RedstoneAlmeida** [Nukkit/Nukkit#1090]
### Issue description

wanted to know if it is possible to take a random server player and save his name in the config and then go changing the player who is online on the server, type saves the name of a random player in the config and after about 10 seconds to get another player aleatorio and save the name in the config

**Comment by MrPowerGamerBR** [comment]
The issues section isn't for questions about the Nukkit API.

http://forums.nukkit.io/

Also, this is Java, if you knew Java you would know how to do it.

```
Player player = getServer().getOnlinePlayers().values().get(new Random().nextInt(getServer().getOnlinePlayers().size());
```

I'm not with my IDE open atm so it may be wrong.

**Comment by RedstoneAlmeida** [comment]
```
08:27:19 [CRITICAL] Exception while invoking run
java.lang.NullPointerException
        at me.slice.corepluginfornukkit.task.bussola.Bussola.onRun(Bussola.java:31)
        at cn.nukkit.scheduler.ServerScheduler.lambda$addTask$1(ServerScheduler.java:165)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:204)
        at cn.nukkit.Server.tick(Server.java:997)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

Code:

```
public void onRun(int currentTick) {
		for(Player p : this.getOwner().getServer().getOnlinePlayers().values()){
			if(p.getPlayer().getInventory().getItemInHand().getId() == 345){
				Player player = this.getOwner().getServer().getOnlinePlayers().get(new Random().nextInt(this.getOwner().getServer().getOnlinePlayers().size()));
				p.sendTip("§bBussola apontando para " + player.getName() + "\n§aSuas Coords : " + (int)p.getX() + " " + (int)p.getY() + " " + (int)p.getZ());
				p.sendPopup("§bCoordenadas de " + player.getName() + ": " + (int)player.getX() + " " + (int)player.getY() + " " + (int)player.getZ());
			}
		}
	}
```

How to fix??

**Comment by MrPowerGamerBR** [comment]
@RedstoneAlmeida if you don't say what is the line 31 on your code, nobody can help you.
