### ISSUE TITLE
Running at MacOS

### ISSUE THREAD

**Issue by weilantian** [Nukkit/Nukkit#1095]
2016-10-6 22:00:10 [INFO] Welcome! Please choose a language first!
2016-10-6 22:00:10 [ALERT] java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at cn.nukkit.utils.Utils.readFile(Utils.java:58)
	at cn.nukkit.Server.<init>(Server.java:210)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-10-6 22:00:10 [INFO] Stopping other threads
2016-10-6 22:04:08 [INFO] Welcome! Please choose a language first!
2016-10-6 22:04:08 [ALERT] java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at cn.nukkit.utils.Utils.readFile(Utils.java:58)
	at cn.nukkit.Server.<init>(Server.java:210)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-10-6 22:04:08 [INFO] Stopping other threads
2016-10-6 22:06:11 [INFO] Welcome! Please choose a language first!
2016-10-6 22:06:11 [ALERT] java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at cn.nukkit.utils.Utils.readFile(Utils.java:58)
	at cn.nukkit.Server.<init>(Server.java:210)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-10-6 22:06:11 [INFO] Stopping other threads

**Comment by kniffo80** [comment]
This is because the language files are not in the final jar when you compile the default project.

Do the following:
* in the Nukkit Project, under /src/main/resources place the complete lang folder (e.g.)
* build again with maven (clean, package)

Now the error should be gone.

**Comment by Snake1999** [comment]
You've got a broken jar, which does not includes language files. That's not the fault of mac.
