### ISSUE TITLE
ConcurrentModificationException while teleporting between worlds

### ISSUE THREAD

**Issue by yescallop** [Nukkit/Nukkit#1099]
### Issue description

ConcurrentModificationException while teleporting between worlds, and then client freezes
### Steps to reproduce the issue

1. idk how to reproduce this
### OS and versions

- Nukkit: Latest
- OS: 
- Device:
### Crashdump, backtrace or other files

08:43:25 [CRITICAL] 计算地图 "f" 时出现错误：java.lang.NullPointerException
08:43:25 [ALERT] java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
        at java.util.HashMap.putMapEntries(HashMap.java:511)
        at java.util.HashMap.<init>(HashMap.java:489)
        at cn.nukkit.Player.orderChunks(Player.java:770)
        at cn.nukkit.Player.checkNetwork(Player.java:1469)
        at cn.nukkit.Server.tick(Server.java:1003)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)                                   at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)  
08:43:25 [CRITICAL] 计算地图 "f" 时出现错误：java.util.ConcurrentModificationException

**Comment by Creeperface01** [comment]
wtf
