### ISSUE TITLE
Item frame does not appear

### ISSUE THREAD

**Issue by Rasuku** [Nukkit/Nukkit#1133]
### Issue description

item frame does not work

### Steps to reproduce the issue

1. put the itenframe
2. leave the server
3. itemframe is not visible

### OS and versions

* Nukkit: 9c9cefd66c251f9bd2f838baaab219458faa9d8b
* OS: Ubuntuu 16.04.1 LTS 64bit
* Device: MC Windows 10 Edition Beta 0.15.10.

### Crashdump, backtrace or other files

```
[ALERT] java.lang.NullPointerException
	at cn.nukkit.block.BlockItemFrame.onActivate(BlockItemFrame.java:50)
	at cn.nukkit.level.Level.useItemOn(Level.java:1812)
	at cn.nukkit.Player.handleDataPacket(Player.java:1956)
	at cn.nukkit.network.Network.processPackets(Network.java:188)
	at cn.nukkit.network.Network.processBatch(Network.java:164)
	at cn.nukkit.Player.handleDataPacket(Player.java:1746)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
	at cn.nukkit.network.Network.processInterfaces(Network.java:75)
	at cn.nukkit.Server.tick(Server.java:989)
	at cn.nukkit.Server.tickProcessor(Server.java:786)
	at cn.nukkit.Server.start(Server.java:765)
	at cn.nukkit.Server.<init>(Server.java:456)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

**Comment by Snake1999** [comment]
Go https://github.com/Nukkit/Nukkit/issues/1133
