### ISSUE TITLE
java.lang.NumberFormatException: For input string: "1000000000000000

### ISSUE THREAD

**Issue by OverTook** [Nukkit/Nukkit#1155]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ... just join and touch any block
2. ...

### OS and versions

* Nukkit: 0.15.10 (build 481)
* OS: 0.15.9
* Device: LG X Screen

### Crashdump, backtrace or other files

* ...

~~~~~~~~~~~~~~~~~~~~~~~~
[ALERT] java.lang.NumberFormatException: For input string: "1000000000000000"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at cn.nukkit.Server.getPropertyInt(Server.java:1738)
        at cn.nukkit.Server.getSpawnRadius(Server.java:1260)
        at cn.nukkit.level.Level.useItemOn(Level.java:1800)
        at cn.nukkit.Player.handleDataPacket(Player.java:1950)
        at cn.nukkit.network.Network.processPackets(Network.java:188)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1740)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:989)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Snake1999** [comment]
Ask who changed your config file.

**Comment by OverTook** [comment]
?? i didn't understand. how can i solve the problem??
