### ISSUE TITLE
When player touch block, Exception happended

### ISSUE THREAD

**Issue by OverTook** [Nukkit/Nukkit#1159]
Steps to reproduce the issue
1. Just join and click any block
(don't use any plugin, world)

OS and versions
* Nukkit: build 481  (Nukkit 1.0dev 「?果(Apple)派(Pie)」 API 버전 1.0.0, Minecraft: PE 버전 v0.15.10 alpha (프로토 콜 버전 84))
* OS: Window 10
* Device: LG X Screen (0.15.10)

please don't remove this issues... i want help..

~~~~~~~~~~~~~~~
[ALERT] java.lang.NumberFormatException: For input string: "1000000000000000"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at cn.nukkit.Server.getPropertyInt(Server.java:1740)
        at cn.nukkit.Server.getSpawnRadius(Server.java:1260)
        at cn.nukkit.level.Level.useItemOn(Level.java:1800)
        at cn.nukkit.Player.handleDataPacket(Player.java:1969)
        at cn.nukkit.network.Network.processPackets(Network.java:188)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1750)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:989)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by OverTook** [comment]
Snake1999 said "Ask who changed your config file.". but i can't understand.

how can i solve the problem?

**Comment by OverTook** [comment]
solved
