### ISSUE TITLE
NullPointerException when placing ItemFrames

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1171]
Version nukkit : 6fd32a5
Version MCPE: MC Windows 10 Edition Beta 0.15.10.
Hosted: On Ubuntuu 16.04.1 LTS 64bit

If you place one item in ItemFrame, get this error in console:

17:23:31 [ALERT] java.lang.NullPointerException
        at cn.nukkit.block.BlockItemFrame.onActivate(BlockItemFrame.java:50)
        at cn.nukkit.level.Level.useItemOn(Level.java:1812)
        at cn.nukkit.Player.handleDataPacket(Player.java:1960)
        at cn.nukkit.network.Network.processPackets(Network.java:188)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1750)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:989)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Snake1999** [comment]
Seems like less of our stuff will concern about this issue as: No detailed title written here

**Comment by jhelom** [comment]
error log.

nukkit.yml 

```
debug:
    level: 2
```


**09:21:40 [DEBUG] BatchPacket 0x78DA636060E052676440004379205107C42C40DCC06CCF5AC960CF71F7836D030383D37F8F6687CDD7B99C99229E80D51A39403521190100AA9A0B1B**

09:21:40 [ALERT] java.lang.NullPointerException
        at cn.nukkit.block.BlockItemFrame.onActivate(BlockItemFrame.java:50)
        at cn.nukkit.level.Level.useItemOn(Level.java:1812)
        at cn.nukkit.Player.handleDataPacket(Player.java:1960)
        at cn.nukkit.network.Network.processPackets(Network.java:188)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1750)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:985)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
