### ISSUE TITLE
timing bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1184]
17:05:01 [ALERT] java.lang.NullPointerException
        at cn.nukkit.timings.Timings.getSendDataPacketTiming(Timings.java:229)
        at cn.nukkit.Player.dataPacket(Player.java:841)
        at cn.nukkit.Player.dataPacket(Player.java:833)
        at cn.nukkit.Player.sendChunk(Player.java:584)
        at cn.nukkit.level.Level.sendChunkFromCache(Level.java:2262)
        at cn.nukkit.level.Level.chunkRequestCallback(Level.java:2306)
        at cn.nukkit.level.Level.chunkRequestCallback(Level.java:2297)
        at cn.nukkit.level.format.mcregion.McRegion.requestChunkTask(McRegion.java:173)
        at cn.nukkit.level.Level.processChunkRequest(Level.java:2286)
        at cn.nukkit.level.Level.doTick(Level.java:777)
        at cn.nukkit.Server.checkTickUpdates(Server.java:914)
        at cn.nukkit.Server.tick(Server.java:988)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

17:05:01 [CRITICAL] Could not tick level "biomes": java.lang.NullPointerException

**Comment by Snake1999** [comment]
Where are the formats? How could I know about your OS version, Nukkit version and so on?
