### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException: 253

### ISSUE THREAD

**Issue by OverTook** [Nukkit/Nukkit#1192]
### Issue description

Write a short description about the issue

There is a crash when open server for about 10 minutes.

### Steps to reproduce the issue

1. ... Just open and enjoy server.
2. ... After 10 minutes, Error Happend [ I think when user uses command, this error happend. ]

[ if there is no player in the server, nothing happend ]

### OS and versions

* Nukkit: build 484
* OS: MCPE 0.15.10
* Device:  LG X Screen, and etc.. (5 peoples)

### Crashdump, backtrace or other files

* 

~~~~~~~~~~
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 253
        at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:117)
        at java.io.FilterOutputStream.write(Unknown Source)
        at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
        at sun.nio.cs.StreamEncoder.flush(Unknown Source)
        at java.io.OutputStreamWriter.flush(Unknown Source)
        at jline.console.ConsoleReader.flush(ConsoleReader.java:1032)
        at cn.nukkit.command.CommandReader.stashLine(CommandReader.java:96)
        at cn.nukkit.utils.MainLogger.send(MainLogger.java:175)
        at cn.nukkit.utils.MainLogger.send(MainLogger.java:169)
        at cn.nukkit.utils.MainLogger.alert(MainLogger.java:90)
        at cn.nukkit.utils.MainLogger.logException(MainLogger.java:131)
        at cn.nukkit.Nukkit.main(Nukkit.java:67)
                                                                        Exception in thread "Console" java.lang.ArrayIndexOutOfBoundsException: 254
        at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:117)
        at java.io.FilterOutputStream.write(Unknown Source)
        at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
        at sun.nio.cs.StreamEncoder.flush(Unknown Source)
        at java.io.OutputStreamWriter.flush(Unknown Source)
        at jline.console.ConsoleReader.flush(ConsoleReader.java:1032)
        at jline.console.ConsoleReader.accept(ConsoleReader.java:2009)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2691)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2372)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2360)
        at cn.nukkit.command.CommandReader.readLine(CommandReader.java:47)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:61)
~~~~~~~~~~~~~

```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by OverTook** [comment]
and sorry for my english :p

**Comment by OverTook** [comment]
is it caused by using command?

**Comment by kniffo80** [comment]
Yes. Seems so.

**Comment by OverTook** [comment]
@kniffo80 thx! but i still have this error :D
