### ISSUE TITLE
Server crashed (Help ME :P)

### ISSUE THREAD

**Issue by OverTook** [Nukkit/Nukkit#1198]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ... just join and enjoy
2. ... it will be crashed... :p (I use an item which has a CustomName)
3. ...

### OS and versions

* Nukkit: build 489
* OS: 0.15.10
* Device: LG X Screen

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

~~~~~~~~~~~~~~
2016-10-26 20:39:25 [ALERT] java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source)
	at cn.nukkit.nbt.stream.NBTInputStream.readByte(NBTInputStream.java:53)
	at cn.nukkit.nbt.tag.ListTag.load(ListTag.java:39)
	at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
	at cn.nukkit.nbt.tag.CompoundTag.load(CompoundTag.java:35)
	at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
	at cn.nukkit.level.format.leveldb.Chunk.fromBinary(Chunk.java:340)
	at cn.nukkit.level.format.leveldb.LevelDB.readChunk(LevelDB.java:292)
	at cn.nukkit.level.format.leveldb.LevelDB.loadChunk(LevelDB.java:268)
	at cn.nukkit.level.format.leveldb.LevelDB.getChunk(LevelDB.java:343)
	at cn.nukkit.level.format.leveldb.LevelDB.getChunk(LevelDB.java:31)
	at cn.nukkit.level.Level.loadChunk(Level.java:2387)
	at cn.nukkit.level.Level.getChunk(Level.java:2112)
	at cn.nukkit.level.Level.populateChunk(Level.java:2621)
	at cn.nukkit.level.Level.populateChunk(Level.java:2612)
	at cn.nukkit.Player.sendNextChunk(Player.java:654)
	at cn.nukkit.Player.checkNetwork(Player.java:1483)
	at cn.nukkit.Server.tick(Server.java:991)
	at cn.nukkit.Server.tickProcessor(Server.java:786)
	at cn.nukkit.Server.start(Server.java:765)
	at cn.nukkit.Server.<init>(Server.java:456)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-10-26 20:39:34 [EMERGENCY] Exception happened while ticking server
2016-10-26 20:39:34 [INFO] [Server] 으아
2016-10-26 20:39:34 [ALERT] java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.ArrayList.grow(Unknown Source)
	at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
	at java.util.ArrayList.ensureCapacityInternal(Unknown Source)
	at java.util.ArrayList.add(Unknown Source)
	at cn.nukkit.nbt.tag.ListTag.load(ListTag.java:46)
	at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
	at cn.nukkit.nbt.tag.CompoundTag.load(CompoundTag.java:35)
	at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
	at cn.nukkit.level.format.leveldb.Chunk.fromBinary(Chunk.java:340)
	at cn.nukkit.level.format.leveldb.LevelDB.readChunk(LevelDB.java:292)
	at cn.nukkit.level.format.leveldb.LevelDB.loadChunk(LevelDB.java:268)
	at cn.nukkit.level.format.leveldb.LevelDB.getChunk(LevelDB.java:343)
	at cn.nukkit.level.format.leveldb.LevelDB.getChunk(LevelDB.java:31)
	at cn.nukkit.level.Level.loadChunk(Level.java:2387)
	at cn.nukkit.level.Level.getChunk(Level.java:2112)
	at cn.nukkit.level.generator.task.PopulationTask.<init>(PopulationTask.java:32)
	at cn.nukkit.level.Level.populateChunk(Level.java:2645)
	at cn.nukkit.level.Level.populateChunk(Level.java:2612)
	at cn.nukkit.Player.sendNextChunk(Player.java:654)
	at cn.nukkit.Player.checkNetwork(Player.java:1483)
	at cn.nukkit.Server.tick(Server.java:991)
	at cn.nukkit.Server.tickProcessor(Server.java:786)
	at cn.nukkit.Server.start(Server.java:765)
	at cn.nukkit.Server.<init>(Server.java:456)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-10-26 20:39:34 [ALERT] 
"Nukkit Asynchronous Task Handler #18" Id=34 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@119b8b3
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@119b8b3
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"Nukkit Asynchronous Task Handler #17" Id=33 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@119b8b3
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@119b8b3
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"Nukkit Asynchronous Task Handler #16" Id=32 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@119b8b3
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@119b8b3
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"Nukkit Asynchronous Task Handler #13" Id=29 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@119b8b3
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@119b8b3
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"Nukkit Asynchronous Task Handler #12" Id=28 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@119b8b3
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@119b8b3
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"threadDeathWatcher-3-1" Id=16 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)


"nioEventLoopGroup-2-1" Id=15 RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@1e0c6ae
	-  locked java.util.Collections$UnmodifiableSet@486d78
	-  locked sun.nio.ch.WindowsSelectorImpl@dc3aae
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	...


"RakNet Thread #12" Id=12 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
	at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
	at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
	at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)


"Console" Id=9 RUNNABLE
	at jline.internal.InputStreamReader.read(InputStreamReader.java:193)
	-  locked jline.internal.NonBlockingInputStream@f2d7a6
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2136)
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2126)
	at jline.console.ConsoleReader.readBinding(ConsoleReader.java:2211)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2460)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2372)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2360)
	at cn.nukkit.command.CommandReader.readLine(CommandReader.java:47)
	...


"NonBlockingInputStreamThread" Id=11 WAITING on jline.internal.NonBlockingInputStream@f2d7a6 owned by "Console" Id=9
	at java.lang.Object.wait(Native Method)
	-  waiting on jline.internal.NonBlockingInputStream@f2d7a6
	at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
	at java.lang.Thread.run(Unknown Source)


"Thread-0" Id=8 RUNNABLE
	at java.io.FileOutputStream.close0(Native Method)
	at java.io.FileOutputStream.access$000(Unknown Source)
	at java.io.FileOutputStream$1.close(Unknown Source)
	at java.io.FileDescriptor.closeAll(Unknown Source)
	-  locked java.io.FileDescriptor@1dcbb60
	at java.io.FileOutputStream.close(Unknown Source)
	at sun.nio.cs.StreamEncoder.implClose(Unknown Source)
	at sun.nio.cs.StreamEncoder.close(Unknown Source)
	-  locked java.io.OutputStreamWriter@36250e
	at java.io.OutputStreamWriter.close(Unknown Source)
	...


"Attach Listener" Id=5 RUNNABLE


"Signal Dispatcher" Id=4 RUNNABLE


"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@1526f6c
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@1526f6c
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)


"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@1f5c307
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@1f5c307
	at java.lang.Object.wait(Unknown Source)
	at java.lang.ref.Reference.tryHandlePending(Unknown Source)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)


"main" Id=1 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
	at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:93)
	at cn.nukkit.Server.tickProcessor(Server.java:800)
	at cn.nukkit.Server.start(Server.java:765)
	at cn.nukkit.Server.<init>(Server.java:456)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by OverTook** [comment]
is this caused by world?

**Comment by Snake1999** [comment]
Only nukkit issues should be pushed into nukkit repo.
