### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by CreeperFaceidk** [Nukkit/Nukkit#1201]
this happened on shutdown

### Issue description

 this exception happened on server shutdown

### Steps to reproduce the issue
stop the server? :D idk

### OS and versions

* Nukkit: idk
* OS: windows
* Device: HP

### Crashdump, backtrace or other files
15:05:46 [ALERT] java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:545)
	at jline.console.ConsoleReader.moveInternal(ConsoleReader.java:2064)
	at jline.console.ConsoleReader.moveCursor(ConsoleReader.java:2044)
	at jline.console.ConsoleReader.moveToEnd(ConsoleReader.java:1070)
	at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3848)
	at cn.nukkit.command.CommandReader.unstashLine(CommandReader.java:104)
	at cn.nukkit.utils.MainLogger.send(MainLogger.java:163)
	at cn.nukkit.utils.MainLogger.send(MainLogger.java:155)
	at cn.nukkit.utils.MainLogger.alert(MainLogger.java:76)
	at cn.nukkit.utils.MainLogger.logException(MainLogger.java:117)
	at cn.nukkit.Server.forceShutdown(Server.java:742)
	at cn.nukkit.Server.start(Server.java:766)
	at cn.nukkit.Server.<init>(Server.java:456)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by EnderKenji** [comment]
###### Unrelated Comments, to remind something.
>Issues are getting more and more, hopefully can fix it asap.
>I know that coding isn't easy, but at least try? because nukkit is a good server
>software out there, hopefully its bug free and the best.
