### ISSUE TITLE
Exception with crash

### ISSUE THREAD

**Issue by OverTook** [Nukkit/Nukkit#1206]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ... Just enjoy the server
2. ... will crash
3. ...

### OS and versions

* Nukkit:  build 491
* OS: 0.15.10
* Device:  lg x screen

### Crashdump, backtrace or other files
~~~~~~~~~~~~~~~~~~~~~~~~~
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 238
        at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:117)
        at java.io.FilterOutputStream.write(Unknown Source)
        at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
        at sun.nio.cs.StreamEncoder.flush(Unknown Source)
        at java.io.OutputStreamWriter.flush(Unknown Source)
        at jline.console.ConsoleReader.flush(ConsoleReader.java:1032)
        at cn.nukkit.command.CommandReader.stashLine(CommandReader.java:96)
        at cn.nukkit.utils.MainLogger.send(MainLogger.java:175)
        at cn.nukkit.utils.MainLogger.send(MainLogger.java:169)
        at cn.nukkit.utils.MainLogger.alert(MainLogger.java:90)
        at cn.nukkit.utils.MainLogger.logException(MainLogger.java:131)
        at cn.nukkit.Nukkit.main(Nukkit.java:67)
Exception in thread "Console" java.lang.ArrayIndexOutOfBoundsException: 239
        at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:117)
        at java.io.FilterOutputStream.write(Unknown Source)
        at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
        at sun.nio.cs.StreamEncoder.flush(Unknown Source)
        at java.io.OutputStreamWriter.flush(Unknown Source)
        at jline.console.ConsoleReader.flush(ConsoleReader.java:1032)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:3194)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2372)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2360)
        at cn.nukkit.command.CommandReader.readLine(CommandReader.java:47)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:61)
* ...

**Comment by OverTook** [comment]
anyone help me. plz... I have this error for over 10 days

**Comment by Snake1999** [comment]
Are you reporting bugs or daydreaming about someone will open a server for you from head to tail?

**Comment by Snake1999** [comment]
Are you reporting bugs or daydreaming about someone will open a server for you from head to tail?
