### ISSUE TITLE
Stopping Server [Build #500 from Mengcraft]

### ISSUE THREAD

**Issue by PyroBeast** [Nukkit/Nukkit#1228]
Server gives error upon using the stop command. This has been performed 4 times with the same error.

> stop
10:16:21 [INFO] [CONSOLE: Stopping the server]
10:16:21 [INFO] Unloading level "world"
10:16:22 [INFO] Stopping other threads
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:545)
	at jline.console.ConsoleReader.backspace(ConsoleReader.java:1050)
	at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1036)
	at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3859)
	at cn.nukkit.command.CommandReader.removePromptLine(CommandReader.java:112)
	at cn.nukkit.Nukkit.main(Nukkit.java:90)
> >

**Comment by PyroBeast** [comment]
Update: Has stopped providing this error randomly and is working fine. It may be because i started a new world each time.

**Comment by Godsoft029** [comment]
Sometimes i get this error too, when i paste a command and execute it

**Comment by Creeperface01** [comment]
@Pub4Game me too
