### ISSUE TITLE
EOFExeption in ZLIB

### ISSUE THREAD

**Issue by wsj7178** [Nukkit/Nukkit#1254]
### Issue description

error when player join

### Steps to reproduce the issue

1. ... server on
2. ... join!

### OS and versions

* Nukkit: http://ci.mengcraft.com:8080/job/nukkit/501/
* OS: Ubuntu 15
* Device: Ubuntu

### Crashdump, backtrace or other files

```
[ALERT] java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at cn.nukkit.utils.Zlib.inflate(Zlib.java:41)
        at cn.nukkit.utils.Zlib.inflate(Zlib.java:58)
        at cn.nukkit.network.Network.processBatch(Network.java:129)
        at cn.nukkit.Player.handleDataPacket(Player.java:1834)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:981)
        at cn.nukkit.Server.tickProcessor(Server.java:788)
        at cn.nukkit.Server.start(Server.java:767)
        at cn.nukkit.Server.<init>(Server.java:458)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

```

**Comment by OverTook** [comment]
I have same issue.

**Comment by MagicDroidX** [comment]
Cannot reproduce this.

**Comment by Snake1999** [comment]
Are you really sure you are joining game with correct version 0.16?
Older version have different packet encoding, which cause the different, and errors when deciding.
