### ISSUE TITLE
Could not tick level java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by PhanaticD** [Nukkit/Nukkit#1270]
got this error spamming console

```
2016-11-10 15:44:41 [CRITICAL] Could not tick level "pocket": java.lang.NegativeArraySizeException^M
2016-11-10 15:44:41 [ALERT] java.lang.NegativeArraySizeException
    at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
    at java.util.ArrayList.<init>(ArrayList.java:177)
    at cn.nukkit.level.Level.unloadChunks(Level.java:2743)
    at cn.nukkit.level.Level.unloadChunks(Level.java:2735)
    at cn.nukkit.level.Level.doTick(Level.java:716)
    at cn.nukkit.Server.checkTickUpdates(Server.java:918)
    at cn.nukkit.Server.tick(Server.java:993)
    at cn.nukkit.Server.tickProcessor(Server.java:789)
    at cn.nukkit.Server.start(Server.java:768)
    at cn.nukkit.Server.<init>(Server.java:459)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)

```

**Comment by Creeperface01** [comment]
WTF :D

**Comment by Snake1999** [comment]
Delete your corrupted world any try again
USE TEMPLATES NEXT TIME

**Comment by PhanaticD** [comment]
what do you mean by "USE TEMPLATES NEXT TIME"

**Comment by Snake1999** [comment]
Didn't you got a template when creating new issue?

**Comment by PhanaticD** [comment]
why cant you just fix the issue instead lol
