### ISSUE TITLE
Attribute errors causing speed

### ISSUE THREAD

**Issue by imjack** [Nukkit/Nukkit#1298]
### Issue description

Setting the players exp level can cause Attribute issues. An example is shown below:
`player.setExperience(player.getExperience(), player.getExperienceLevel() - shop.getMoney());`
shop.getMoney(); returns a int like '1'  so 12-1 = 1 but I assume something goes wrong with the calculations in the sendExperience method.

### Steps to reproduce the issue

1. ... Deduct a level until an error occurs. 
### OS and versions

* Nukkit Version:  This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v0.16.0 alpha (protocol version 91) 
 
* Java Version: 8

* Host OS: Windows

* Client Edition: Win10

* Client Version: 0.16.1

### Crashdump, backtrace or other files

`02:58:08 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:557)
        at cn.nukkit.level.Level.useItemOn(Level.java:1892)
        at cn.nukkit.Player.handleDataPacket(Player.java:2115)
        at cn.nukkit.network.Network.processPackets(Network.java:181)
        at cn.nukkit.network.Network.processBatch(Network.java:157)
        at cn.nukkit.Player.handleDataPacket(Player.java:1879)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:982)
        at cn.nukkit.Server.tickProcessor(Server.java:789)
        at cn.nukkit.Server.start(Server.java:768)
        at cn.nukkit.Server.<init>(Server.java:459)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.IllegalArgumentException: Value 1.0689656 exceeds the range!
        at cn.nukkit.entity.Attribute.setValue(Attribute.java:144)
        at cn.nukkit.entity.Attribute.setValue(Attribute.java:138)
        at cn.nukkit.Player.sendExperience(Player.java:3937)
        at cn.nukkit.Player.setExperience(Player.java:3927)
        at me.imjack.skyblock.eshop.listener.PlayerListener.onSignInteract(PlayerListener.java:114)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 16 more`

**Comment by Creeperface01** [comment]
maybe player has 0 experience and 0 - 1 = -1

**Comment by imjack** [comment]
Nope, In my test I had 10 levels. I am attempting to deduct 1 level.

**Comment by File14** [comment]
Show me your code.

**Comment by imjack** [comment]
Trust me, I know my calculations are correct. I've printed numbers its to do with nukkit and the experience being above 1.0 - not the level being above 1.0.

**Comment by imjack** [comment]
Error still happens you can see in the image I have enough EXP but the exp is too high hence the bar being fully full.
