### ISSUE TITLE
Error with slabs on startup

### ISSUE THREAD

**Issue by PhanaticD** [Nukkit/Nukkit#1299]
After updating Nukkit as of this commit https://github.com/Nukkit/Nukkit/commit/45a7f20784b9a7a808740af9e556a79fa64387f1

I get this error on startup:

```
2016-11-28 01:52:34 [ERROR] Error while registering cn.nukkit.block.BlockSlab^M
java.lang.InstantiationException: cn.nukkit.block.BlockSlab
    at java.lang.Class.newInstance(Class.java:427)
    at cn.nukkit.block.Block.init(Block.java:514)
    at cn.nukkit.Server.<init>(Server.java:367)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.NoSuchMethodException: cn.nukkit.block.BlockSlab.<init>()
    at java.lang.Class.getConstructor0(Class.java:3082)
    at java.lang.Class.newInstance(Class.java:412)
    ... 3 more
```

**Comment by File14** [comment]
Same issuse!
