### ISSUE TITLE
getBlock() bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#1300]
sometimes getBlock() method returns null

**Comment by wsj7178** [comment]
'''
09:38:51 [ALERT] java.lang.NullPointerException
        at cn.nukkit.level.Level.getBlock(Level.java:1367)
        at cn.nukkit.level.Level.getBlock(Level.java:1351)
        at cn.nukkit.blockentity.BlockEntity.getBlock(BlockEntity.java:139)
        at cn.nukkit.blockentity.BlockEntitySign.isBlockEntityValid(BlockEntitySign.java:38)
        at cn.nukkit.level.Level.doChunkGarbageCollection(Level.java:2725)
        at cn.nukkit.Server.tick(Server.java:1035)
        at cn.nukkit.Server.tickProcessor(Server.java:793)
        at cn.nukkit.Server.start(Server.java:772)
        at cn.nukkit.Server.<init>(Server.java:463)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
'''

**Comment by SoyPro** [comment]
its happens to me too

**Comment by geekytime** [comment]
I think now it just sometimes returns empty space, even if there's a block there?

**Comment by SupremeMortal** [comment]
The chunk probably is not loaded if it's empty from what I remember.

**Comment by geekytime** [comment]
Well, I was standing on blocks, and trying to get the block below me, and as I walked around the block, it was sometimes the block ID, and sometimes `0`. Calling `getBlockIdAt` with the same numbers returned better (but not quite perfect) results (sigh).
