### ISSUE TITLE
When i place a sign, the console throw me an error

### ISSUE THREAD

**Issue by SoyPro** [Nukkit/Nukkit#1305]
### Issue description
I get a error when i place a sign, on console
Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...
3. ...

### OS and versions

* Nukkit Version: 519(lastest) 
 
* Java Version: 8 update 111

* Host OS: Windows, 64 bits

* Host Configuration: 2 GB RAM, 1TB GB ??(SSD/HDD/...) drive, 4 core CPU from Intel Pentium n3540 (Intel/AMD/...), 2 Mb internet upload

* Client Edition: Windows 10

* Client Version: 0.16.1

### Crashdump, backtrace or other files

* 
```
<!---12:14:55 [CRITICAL] No se puede marcar el nivel "world": java.lang.NullPointerException
12:14:55 [ALERT] java.lang.NullPointerException
        at cn.nukkit.level.Level.getBlock(Level.java:1367)
        at cn.nukkit.level.Level.getBlock(Level.java:1351)
        at cn.nukkit.block.Block.getSide(Block.java:766)
        at cn.nukkit.block.Block.getSide(Block.java:761)
        at cn.nukkit.block.BlockGrass.onUpdate(BlockGrass.java:80)
        at cn.nukkit.level.Level.tickChunks(Level.java:1085)
        at cn.nukkit.level.Level.doTick(Level.java:751)
        at cn.nukkit.Server.checkTickUpdates(Server.java:922)
        at cn.nukkit.Server.tick(Server.java:997)
        at cn.nukkit.Server.tickProcessor(Server.java:793)
        at cn.nukkit.Server.start(Server.java:772)
        at cn.nukkit.Server.<init>(Server.java:463)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

12:14:59 [ALERT] java.lang.NullPointerException
        at cn.nukkit.level.Level.getBlock(Level.java:1367)
        at cn.nukkit.level.Level.getBlock(Level.java:1351)
        at cn.nukkit.blockentity.BlockEntity.getBlock(BlockEntity.java:139)
        at cn.nukkit.blockentity.BlockEntitySign.isBlockEntityValid(BlockEntitySign.java:38)
        at cn.nukkit.level.Level.doChunkGarbageCollection(Level.java:2725)
        at cn.nukkit.Server.tick(Server.java:1035)
        at cn.nukkit.Server.tickProcessor(Server.java:793)
        at cn.nukkit.Server.start(Server.java:772)
        at cn.nukkit.Server.<init>(Server.java:463)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

12:15:04 [ALERT] java.lang.NullPointerException
        at cn.nukkit.level.Level.getBlock(Level.java:1367)
        at cn.nukkit.level.Level.getBlock(Level.java:1351)
        at cn.nukkit.blockentity.BlockEntity.getBlock(BlockEntity.java:139)
        at cn.nukkit.blockentity.BlockEntitySign.isBlockEntityValid(BlockEntitySign.java:38)
        at cn.nukkit.level.Level.doChunkGarbageCollection(Level.java:2725)
        at cn.nukkit.Server.tick(Server.java:1035)
        at cn.nukkit.Server.tickProcessor(Server.java:793)
        at cn.nukkit.Server.start(Server.java:772)
        at cn.nukkit.Server.<init>(Server.java:463)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

12:15:09 [ALERT] java.lang.NullPointerException
        at cn.nukkit.level.Level.getBlock(Level.java:1367)
        at cn.nukkit.level.Level.getBlock(Level.java:1351)
        at cn.nukkit.blockentity.BlockEntity.getBlock(BlockEntity.java:139)
        at cn.nukkit.blockentity.BlockEntitySign.isBlockEntityValid(BlockEntitySign.java:38)
        at cn.nukkit.level.Level.doChunkGarbageCollection(Level.java:2725)
        at cn.nukkit.Server.tick(Server.java:1035)
        at cn.nukkit.Server.tickProcessor(Server.java:793)
        at cn.nukkit.Server.start(Server.java:772)
        at cn.nukkit.Server.<init>(Server.java:463)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

12:15:14 [ALERT] java.lang.NullPointerException
        at cn.nukkit.level.Level.getBlock(Level.java:1367)
        at cn.nukkit.level.Level.getBlock(Level.java:1351)
        at cn.nukkit.blockentity.BlockEntity.getBlock(BlockEntity.java:139)
        at cn.nukkit.blockentity.BlockEntitySign.isBlockEntityValid(BlockEntitySign.java:38)
        at cn.nukkit.level.Level.doChunkGarbageCollection(Level.java:2725)
        at cn.nukkit.Server.tick(Server.java:1035)
        at cn.nukkit.Server.tickProcessor(Server.java:793)
        at cn.nukkit.Server.start(Server.java:772)
        at cn.nukkit.Server.<init>(Server.java:463)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

12:15:18 [ALERT] java.lang.NullPointerException

12:15:23 [ALERT] java.lang.NullPointerException

12:15:28 [ALERT] java.lang.NullPointerException

12:15:32 [INFO] [Welcome] Player sk8gamer logged-in!
12:15:33 [ALERT] java.lang.NullPointerException

12:15:35 [ALERT] java.lang.NullPointerException

12:15:38 [ALERT] java.lang.NullPointerException

12:15:43 [ALERT] java.lang.NullPointerException

12:15:48 [ALERT] java.lang.NullPointerException

12:15:53 [ALERT] java.lang.NullPointerException

12:15:58 [ALERT] java.lang.NullPointerException

12:15:59 [CRITICAL] No se puede marcar el nivel "world": java.lang.NullPointerException
12:15:59 [ALERT] java.lang.NullPointerException

12:16:00 [INFO] sk8gamer dejó el juego
12:16:00 [INFO] sk8gamer[/181.169.16.49:19132] Desconectado por client disconnect
12:16:03 [ALERT] java.lang.NullPointerException

12:16:08 [ALERT] java.lang.NullPointerException

12:16:13 [ALERT] java.lang.NullPointerException

12:16:18 [ALERT] java.lang.NullPointerException

12:16:23 [ALERT] java.lang.NullPointerException -->
```
* ...

**Comment by Creeperface01** [comment]
and error?

**Comment by SoyPro** [comment]
i forgot it

**Comment by SoyPro** [comment]
wait i copy and paste here now

**Comment by SoyPro** [comment]
its throw me every second that error

**Comment by daveboden** [comment]
I just tried recreating after switching language to "spa" in nukkit.yml, just in case the problem was related to a language pack. Signs work fine for me using an up-to-date build.

I would recommend either providing more info to allow this issue to be recreated or closing the issue report.

**Comment by Creeperface01** [comment]
Check level.dat file and world folder, are there all files?

**Comment by Creeperface01** [comment]
This can happen if nukkit hasnt permissions to write files, or create etc

**Comment by SoyPro** [comment]
its fixed this, closed this issue!
