### ISSUE TITLE
(Too much) NPEs on old clients' join

### ISSUE THREAD

**Issue by Tee7even** [Nukkit/Nukkit#1312]
### Issue description
A shitload of NullPointerExceptions, when a player tries to join with an old client.

### Steps to reproduce the issue
1. Get Nukkit
2. Start Nukkit
3. Try to join with 0.15 (for example)
4. ???????
5.
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException
>[ALERT] java.lang.NullPointerException

### OS and versions
* Nukkit Version: latest ( ͡° ͜ʖ ͡°)

### Crashdump, backtrace or other files
```
[ALERT] java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at cn.nukkit.utils.Zlib.inflate(Zlib.java:41)
	at cn.nukkit.utils.Zlib.inflate(Zlib.java:58)
	at cn.nukkit.network.Network.processBatch(Network.java:129)
	at cn.nukkit.Player.handleDataPacket(Player.java:1874)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:986)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
```
...followed by **8 megabytes** of `NullPointerException`s

**Comment by Snake1999** [comment]
Old clients have different packet formats, and it's not the duty of Nukkit to keep all of them OK. Remove the "AnyVersion" and tell players to update their clients.

**Comment by Tee7even** [comment]
1. IT IS a problem that Nukkit generates a ton of NPEs. It's a problem that Nukkit just has unhandled exceptions during its normal functioning. 
2. I don't use AnyVersion. 
3. You can't prevent some player joining the server with an old client. IT WILL occur.

**Comment by imjack** [comment]
I also get this problem too.

**Comment by loveGhb** [comment]
Similarly, only with version 1.13

`
2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.isBanned(Player.java:226)
	at cn.nukkit.Player.kick(Player.java:3462)
	at cn.nukkit.Player.kick(Player.java:3453)
	at cn.nukkit.Player.kick(Player.java:3445)
	at cn.nukkit.Server.checkTickUpdates(Server.java:906)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:793)
	at cn.nukkit.Server.start(Server.java:772)
	at cn.nukkit.Server.<init>(Server.java:463)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException

2016-12-4 18:20:15 [ALERT] java.lang.NullPointerException
`

**Comment by Creeperface01** [comment]
WTF, you must have modified nukkit or something, because nukkit closes all players with uncompatibile protocol version so isBanned() methods or so are never callled

**Comment by MagicDroidX** [comment]
Maybe we should blame mojang for changing the packet format without modifying the protocol version number?

**Comment by Creeperface01** [comment]
But i think nukkit should be protected. Someone can change protocol version or modify mcpe and then he can crash our servers
