### ISSUE TITLE
Nukkit Problem 

### ISSUE THREAD

**Issue by MatinDark** [Nukkit/Nukkit#1327]
When Some Player Try To Join Server Console Error This Spam And Player Can't Join !
Code:
2016-12-17 09:55:29 [ALERT] java.io.EOFException: Unexpected end of ZLIB input stream
    at java.util.zip.InflaterInputStream.fill(Unknown Source)
    at java.util.zip.InflaterInputStream.read(Unknown Source)
    at java.io.FilterInputStream.read(Unknown Source)
    at cn.nukkit.utils.Zlib.inflate(Zlib.java:41)
    at cn.nukkit.utils.Zlib.inflate(Zlib.java:58)
    at cn.nukkit.network.Network.processBatch(Network.java:129)
    at cn.nukkit.Player.handleDataPacket(Player.java:1875)
    at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
    at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
    at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
    at cn.nukkit.network.Network.processInterfaces(Network.java:76)
    at cn.nukkit.Server.tick(Server.java:986)
    at cn.nukkit.Server.tickProcessor(Server.java:793)
    at cn.nukkit.Server.start(Server.java:772)
    at cn.nukkit.Server.<init>(Server.java:463)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Snake1999** [comment]
Cannot reproduce. 
BTW, How could we solve your problem by no device information and no detailed problem reproducing step provided?

**Comment by Creeperface01** [comment]
@Snake1999 anyway we should prevent these issues, players should not be able to crash hack our server in this way

**Comment by DaMatrix** [comment]
I think this is caused by people with the 1.0 beta trying to connect, not sure though. Speaking of which, is there a bramch to work on the beta? Would be nice to beat G*nisys to it at some point
