### ISSUE TITLE
1.0.0 crash on startup

### ISSUE THREAD

**Issue by erkam2002** [Nukkit/Nukkit#1361]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...
3. ...

### OS and versions

* Nukkit Version: 1.0.0 newest 
 
* Java Version: 8

* Host OS: Debian 8

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: PE

* Client Version: 1.0.0

### Crashdump, backtrace or other files

*  [ALERT] java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
        at cn.nukkit.utils.Utils.readFile(Utils.java:61)
        at cn.nukkit.Server.<init>(Server.java:215)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by erkam2002** [comment]
Why???

**Comment by Pub4Game** [comment]
Duplicate https://github.com/Nukkit/Nukkit/issues/1344
