### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by JackboyPlay** [Nukkit/Nukkit#1368]
OS: Ubuntu
Nukkitversion: nukkit-1.0-SNAPSHOT [Downloaded today at 12:31 MET]
How to reproduce: Start the server
Error: 
[ALERT] java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at cn.nukkit.utils.Utils.readFile(Utils.java:61)
	at cn.nukkit.lang.BaseLang.loadLang(BaseLang.java:96)
	at cn.nukkit.lang.BaseLang.<init>(BaseLang.java:37)
	at cn.nukkit.lang.BaseLang.<init>(BaseLang.java:29)
	at cn.nukkit.lang.BaseLang.<init>(BaseLang.java:25)
	at cn.nukkit.Server.<init>(Server.java:282)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by Pub4Game** [comment]
https://github.com/Nukkit/Nukkit/issues/1344
