### ISSUE TITLE
Commands error

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#140]
GIVE
```
[CRITICAL] Необработанное исключение при выполнении команды 'give 
pub4game 1' в give: java.lang.ArrayIndexOutOfBoundsException: 2
	at cn.nukkit.command.defaults.GiveCommand.execute(GiveCommand.java:70)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148)
	at cn.nukkit.Server.dispatchCommand(Server.java:602)
	at cn.nukkit.command.CommandReader.run(CommandReader.java:62)

[ALEndexOutOfBoundsException: 2
	at cn.nukkit.command.defaults.GiveCommand.execute(GiveCommand.java:70)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148)
	at cn.nukkit.Server.dispatchCommand(Server.java:602)RT] java.lang.ArrayI
	at cn.nukkit.command.CommandReader.run(CommandReader.java:62)
```

```
[CRITICAL] Необработанное исключение при выполнении команды 'give pub4game Apple 123' в give: java.lang.NumberFormatException: For input string: "Apple"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.valueOf(Unknown Source)
	at cn.nukkit.item.Item.fromString(Item.java:971)
	at cn.nukkit.command.defaults.GiveCommand.execute(GiveCommand.java:33)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148)
	at cn.nukkit.Server.dispatchCommand(Server.java:602)
	at cn.nukkit.command.CommandReader.run(CommandReader.java:62)

[ALERT] java.lang.NumberFormatException: For input string: "Apple"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.valueOf(Unknown Source)
	at cn.nukkit.item.Item.fromString(Item.java:971)
	at cn.nukkit.command.defaults.GiveCommand.execute(GiveCommand.java:33)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148)
	at cn.nukkit.Server.dispatchCommand(Server.java:602)
	at cn.nukkit.command.CommandReader.run(CommandReader.java:62)
```
![image](https://cloud.githubusercontent.com/assets/11244874/11699599/2cad64c4-9ed6-11e5-89d2-23a8a4e83eda.png)

TIME:
```
[CRITICAL] Необработанное исключение при выполнении команды 'time set p' в time: java.lang.NumberFormatException: For input string: "p" 
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) 
at java.lang.Integer.parseInt(Integer.java:580) 
at java.lang.Integer.parseInt(Integer.java:615) 
at cn.nukkit.command.defaults.TimeCommand.execute(TimeCommand.java:94) 
at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) 
at cn.nukkit.Server.dispatchCommand(Server.java:602) 
at cn.nukkit.Player.handleDataPacket(Player.java:2474) 
at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135) 
at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123) 
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
at cn.nukkit.network.Network.processInterfaces(Network.java:73) 
at cn.nukkit.Server.tick(Server.java:928) 
at cn.nukkit.Server.tickProcessor(Server.java:750) 
at cn.nukkit.Server.start(Server.java:731) 
at cn.nukkit.Server.<init>(Server.java:427) 
at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

**Comment by Snake1999** [comment]
Array out of bounds. That should be checked :3 Roger

**Comment by MagicDroidX** [comment]
@snake1999 go and fix it :D

**Comment by haidada** [comment]
。。。。。。

**Comment by haidada** [comment]
啦啦啦
