### ISSUE TITLE
Error spamming console

### ISSUE THREAD

**Issue by PhanaticD** [Nukkit/Nukkit#1488]
```
16:36:55 [CRITICAL] Could not tick level "pocket": java.lang.NegativeArraySizeException
16:36:55 [ALERT] java.lang.NegativeArraySizeException
        at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
        at java.util.ArrayList.<init>(ArrayList.java:177)
        at cn.nukkit.level.Level.processChunkRequest(Level.java:2330)
        at cn.nukkit.level.Level.doTick(Level.java:806)
        at cn.nukkit.Server.checkTickUpdates(Server.java:933)
        at cn.nukkit.Server.tick(Server.java:1008)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
```

**Comment by Creeperface01** [comment]
WTF

**Comment by Snake1999** [comment]
If okay, could u please upload the world as zip file, and provide your device information?

if no detailed information provided, i cannot solve your problem.
