### ISSUE TITLE
Level.getChunk(x, z) may be broken?

### ISSUE THREAD

**Issue by sero583** [Nukkit/Nukkit#1498]
### Issue description
Everytime my plugin tries to get a Chunk per Level.getChunk(x, z), it throws me a NullPointerException, also I have no idea what I'm doing wrong, the values are working fine and are NOT null. I use FDevTools to load the plugin, but anyways that doesn't really matter. The chunk which I'm trying to get maybe not even loaded, but does that matter, though?

### Steps to reproduce the issue

1. Try to get a chunk with Level.getChunk(x, z);
2. Wait and look if you get errors on startup

### OS and versions
This server is running Nukkit 1.0dev ???(Apple)?(Pie)? implementing API version 1.0.0 for Minecraft: PE v1.0.3 (protocol version 101)
* Java Version: 8

* Host OS: Ubuntu 16.04.1

* Host Configuration: Doesn't matter
* Client Edition: PE

* Client Version: 1.0.3.0

### Crashdump, backtrace or other files

```
* 18:25:14 [ALERT] java.lang.RuntimeException: java.lang.NullPointerException
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
        at cn.nukkit.Server.enablePlugin(Server.java:626)
        at cn.nukkit.Server.enablePlugins(Server.java:615)
        at moe.berd.FDevTools.Main.onEnable(Main.java:42)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:119)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        at cn.nukkit.Server.enablePlugin(Server.java:626)
        at cn.nukkit.Server.enablePlugins(Server.java:615)
        at cn.nukkit.Server.<init>(Server.java:389)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NullPointerException
        at core.sero583.main.spawnEntityNW(main.java:362)
        at core.sero583.main.onEnable(main.java:140)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at moe.berd.FDevTools.SourcePluginLoader.enablePlugin(SourcePluginLoader.java:163)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        ... 10 more

```

Code info: spawnEntityNW(params) is a function in my plugin, and gets called at the main.java:140 (during enabling it). It gets called right the line main.java:362.:

BaseFullChunk chunk = pos.getLevel().getChunk((Math.round((int) pos.getX()) >> 4), (Math.round((int) pos.getZ()) >> 4));

I tried it normally which didnt worked with getFloorX() >> 4 etc. so don't wonder that code style.

**Comment by Creeperface01** [comment]
Wtf how do you want to round int :D

**Comment by sero583** [comment]
Whops it was a double

**Comment by sero583** [comment]
After all I tried to figure whats the problem and the problem is that.. the plugins get loaded before the level and then Level.getLevelByName(String name); returns null for me. I try to load the level manually then

**Comment by sero583** [comment]
Now I have another problem, if I try to load the level "world" it tells me that level doesn't exists but it definitely exists. I use Server.loadLevel(String name); to load levels, ofcourse.
