### ISSUE TITLE
I can't join my server.

### ISSUE THREAD

**Issue by TexusDark** [Nukkit/Nukkit#150]
Hello,
I have a problem with Nukkit, I can't go connect to my server and on the console I have this : 

> Exception in thread "Asynchronous Worker" java.lang.NullPointerException
	at cn.nukkit.level.generator.Normal.generateChunk(Normal.java:169)
	at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:82)
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:20)
	at cn.nukkit.scheduler.AsyncWorker.run(AsyncWorker.java:41)

So can you help me ?

**Comment by Pub4Game** [comment]
Fixed #148

**Comment by TexusDark** [comment]
Thanks =D
