### ISSUE TITLE
Stackoverflow while ticking (water/lava related)

### ISSUE THREAD

**Issue by PhanaticD** [Nukkit/Nukkit#1566]
### Issue description

Write a short description about the issue

Server crash

### Steps to reproduce the issue

1. I am not sure

### OS and versions

* Nukkit Version:  ??
 https://github.com/Nukkit/Nukkit/commit/e5a385173007e3f92db147a7433297afd0c0ec6a
 
* Java Version: ?? 8

* Host OS: ?? ubuntu

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload 32 gb ram SSD

* Client Edition: ?? unrelated

* Client Version: ??.??.??

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
http://pastebin.com/c5nqb1Us
```
* ...

**Comment by Snake1999** [comment]
I can not open the pastebin... Maybe upload into aikar timings or fuzhizhantie.com ?

**Comment by PhanaticD** [comment]
```
2017-3-25 11:15:45 [EMERGENCY] Exception happened while ticking server^M
2017-3-25 11:15:45 [ALERT] java.lang.StackOverflowError
    at java.util.zip.Deflater.<init>(Deflater.java:168)
    at java.util.zip.Deflater.<init>(Deflater.java:180)
    at cn.nukkit.utils.Zlib.deflate(Zlib.java:18)
    at cn.nukkit.Server.batchPackets(Server.java:599)
    at cn.nukkit.Server.batchPackets(Server.java:566)
    at cn.nukkit.level.Level.sendBlocks(Level.java:979)
    at cn.nukkit.level.Level.sendBlocks(Level.java:910)
    at cn.nukkit.level.Level.setBlock(Level.java:1540)
    at cn.nukkit.level.Level.setBlock(Level.java:1517)
    at cn.nukkit.block.BlockLiquid.checkForHarden(BlockLiquid.java:488)
    at cn.nukkit.block.BlockLiquid.onUpdate(BlockLiquid.java:203)
    at cn.nukkit.block.BlockLava.onUpdate(BlockLava.java:79)
    at cn.nukkit.block.BlockLavaStill.onUpdate(BlockLavaStill.java:37)
    at cn.nukkit.level.Level.updateAround(Level.java:1162)
    at cn.nukkit.level.Level.setBlock(Level.java:1563)
    at cn.nukkit.level.Level.setBlock(Level.java:1517)
    at cn.nukkit.block.BlockLiquid.checkForHarden(BlockLiquid.java:488)
    at cn.nukkit.block.BlockLiquid.onUpdate(BlockLiquid.java:203)
    at cn.nukkit.block.BlockLava.onUpdate(BlockLava.java:79)
    at cn.nukkit.block.BlockLavaStill.onUpdate(BlockLavaStill.java:37)
    at cn.nukkit.level.Level.updateAround(Level.java:1162)
    at cn.nukkit.level.Level.setBlock(Level.java:1563)
    at cn.nukkit.level.Level.setBlock(Level.java:1517)
    at cn.nukkit.block.BlockLiquid.checkForHarden(BlockLiquid.java:488)
    at cn.nukkit.block.BlockLiquid.onUpdate(BlockLiquid.java:203)
    at cn.nukkit.block.BlockLava.onUpdate(BlockLava.java:79)
    at cn.nukkit.block.BlockLavaStill.onUpdate(BlockLavaStill.java:37)
    at cn.nukkit.level.Level.updateAround(Level.java:1162)
    at cn.nukkit.level.Level.setBlock(Level.java:1563)
    at cn.nukkit.level.Level.setBlock(Level.java:1517)
    at cn.nukkit.block.BlockLiquid.checkForHarden(BlockLiquid.java:488)
    at cn.nukkit.block.BlockLiquid.onUpdate(BlockLiquid.java:203)
    at cn.nukkit.block.BlockLava.onUpdate(BlockLava.java:79)
    at cn.nukkit.block.BlockLavaStill.onUpdate(BlockLavaStill.java:37)
    at cn.nukkit.level.Level.updateAround(Level.java:1162)
    at cn.nukkit.level.Level.setBlock(Level.java:1563)
    at cn.nukkit.level.Level.setBlock(Level.java:1517)
    at cn.nukkit.block.BlockLiquid.checkForHarden(BlockLiquid.java:488)
    at cn.nukkit.block.BlockLiquid.onUpdate(BlockLiquid.java:203)
    at cn.nukkit.block.BlockLava.onUpdate(BlockLava.java:79)
    at cn.nukkit.block.BlockLavaStill.onUpdate(BlockLavaStill.java:37)
    at cn.nukkit.level.Level.updateAround(Level.java:1162)
    at cn.nukkit.level.Level.setBlock(Level.java:1563)
    at cn.nukkit.level.Level.setBlock(Level.java:1517)
    at cn.nukkit.block.BlockLiquid.checkForHarden(BlockLiquid.java:488)
    at cn.nukkit.block.BlockLiquid.onUpdate(BlockLiquid.java:203)
    at cn.nukkit.block.BlockLava.onUpdate(BlockLava.java:79)
    at cn.nukkit.block.BlockLavaStill.onUpdate(BlockLavaStill.java:37)
    at cn.nukkit.level.Level.updateAround(Level.java:1162)
    at cn.nukkit.level.Level.setBlock(Level.java:1563)
    at cn.nukkit.level.Level.setBlock(Level.java:1517)
    at cn.nukkit.block.BlockLiquid.checkForHarden(BlockLiquid.java:488)
    at cn.nukkit.block.BlockLiquid.onUpdate(BlockLiquid.java:203)
    at cn.nukkit.block.BlockLava.onUpdate(BlockLava.java:79)
    at cn.nukkit.block.BlockLavaStill.onUpdate(BlockLavaStill.java:37)
    at cn.nukkit.level.Level.updateAround(Level.java:1162)
    at cn.nukkit.level.Level.setBlock(Level.java:1563)
    at cn.nukkit.level.Level.setBlock(Level.java:1517)
    at cn.nukkit.block.BlockLiquid.checkForHarden(BlockLiquid.java:488)
    at cn.nukkit.block.BlockLiquid.onUpdate(BlockLiquid.java:203)
    at cn.nukkit.block.BlockLava.onUpdate(BlockLava.java:79)
    at cn.nukkit.block.BlockLavaStill.onUpdate(BlockLavaStill.java:37)
    at cn.nukkit.level.Level.updateAround(Level.java:1180)
    at cn.nukkit.level.Level.setBlock(Level.java:1563)
    at cn.nukkit.level.Level.setBlock(Level.java:1517)
    at cn.nukkit.block.BlockLiquid.checkForHarden(BlockLiquid.java:488)
    at cn.nukkit.block.BlockLiquid.onUpdate(BlockLiquid.java:203)
    at cn.nukkit.block.BlockLava.onUpdate(BlockLava.java:79)
    at cn.nukkit.block.BlockLavaStill.onUpdate(BlockLavaStill.java:37)
    at cn.nukkit.level.Level.updateAround(Level.java:1168)
    at cn.nukkit.level.Level.setBlock(Level.java:1563)
    at cn.nukkit.level.Level.setBlock(Level.java:1517)
    at cn.nukkit.block.BlockLiquid.checkForHarden(BlockLiquid.java:488)
    at cn.nukkit.block.BlockLiquid.onUpdate(BlockLiquid.java:203)
    at cn.nukkit.block.BlockLava.onUpdate(BlockLava.java:79)
    at cn.nukkit.block.BlockLavaStill.onUpdate(BlockLavaStill.java:37)
    at cn.nukkit.level.Level.updateAround(Level.java:1168)
    at cn.nukkit.level.Level.setBlock(Level.java:1563)
```

**Comment by PhanaticD** [comment]
I hope this can be fixed soon, cant turn my server on without this happening
