### ISSUE TITLE
Custom recipes not work

### ISSUE THREAD

**Issue by JackboyPlay** [Nukkit/Nukkit#1569]
1. Register a custom recipe Item out = Item.get(Item.GOLDEN_APPLE, 1, 0);
		out.setCustomName("§6Golden Head");
        Server.getInstance().getCraftingManager().registerShapedRecipe((new BigShapedRecipe(out,
                "XXX",
                "XOX",
                "XXX"
        )).setIngredient("X", Item.get(Item.GOLD_INGOT)).setIngredient("O", Item.get(Item.STONE)));
2. try to craft it
3. realize that it isn't able to be crafted

### OS and versions

* Nukkit Version: ?? 
 
* Java Version: 8

* Host OS: Linux

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: Windows10

* Client Version: 1.0.4

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by JackboyPlay** [comment]
Error ->

20:41:36 [ALERT] java.lang.NullPointerException
        at cn.nukkit.utils.Binary.writeUUID(Binary.java:70)
        at cn.nukkit.utils.BinaryStream.putUUID(BinaryStream.java:195)
        at cn.nukkit.network.protocol.CraftingDataPacket.writeShapedRecipe(CraftingDataPacket.java:72)
        at cn.nukkit.network.protocol.CraftingDataPacket.writeEntry(CraftingDataPacket.java:36)
        at cn.nukkit.network.protocol.CraftingDataPacket.encode(CraftingDataPacket.java:142)
        at cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:244)
        at cn.nukkit.Player.dataPacket(Player.java:923)
        at cn.nukkit.Player.dataPacket(Player.java:907)
        at cn.nukkit.Server.sendRecipeList(Server.java:921)
        at cn.nukkit.Player.doFirstSpawn(Player.java:756)
        at cn.nukkit.Player.sendNextChunk(Player.java:748)
        at cn.nukkit.Player.checkNetwork(Player.java:1651)
        at cn.nukkit.Server.tick(Server.java:1024)
        at cn.nukkit.Server.tickProcessor(Server.java:808)
        at cn.nukkit.Server.start(Server.java:787)
        at cn.nukkit.Server.<init>(Server.java:472)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by Creeperface01** [comment]
Does it work if you remove item nbt?

**Comment by JackboyPlay** [comment]
@Creeperface01 if I do that without setCustomName it wont work too.

**Comment by PythonCircuit** [comment]
So does this not work? Doesn't seem to work
