### ISSUE TITLE
Joining the server isn't possible

### ISSUE THREAD

**Issue by JackboyPlay** [Nukkit/Nukkit#1570]
### Issue description

If I join my local server with the port 19134 I'll get the error following 

### Steps to reproduce the issue

Joining the server

### OS and versions

* Nukkit Version: snapshot-1.0 
 
* Java Version: 8

* Host OS: Windows

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: Windows 10

* Client Version: 1.0.4

### Crashdump, backtrace or other files

* 
```
20:41:36 [ALERT] java.lang.NullPointerException
        at cn.nukkit.utils.Binary.writeUUID(Binary.java:70)
        at cn.nukkit.utils.BinaryStream.putUUID(BinaryStream.java:195)
        at cn.nukkit.network.protocol.CraftingDataPacket.writeShapedRecipe(CraftingDataPacket.java:72)
        at cn.nukkit.network.protocol.CraftingDataPacket.writeEntry(CraftingDataPacket.java:36)
        at cn.nukkit.network.protocol.CraftingDataPacket.encode(CraftingDataPacket.java:142)
        at cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:244)
        at cn.nukkit.Player.dataPacket(Player.java:923)
        at cn.nukkit.Player.dataPacket(Player.java:907)
        at cn.nukkit.Server.sendRecipeList(Server.java:921)
        at cn.nukkit.Player.doFirstSpawn(Player.java:756)
        at cn.nukkit.Player.sendNextChunk(Player.java:748)
        at cn.nukkit.Player.checkNetwork(Player.java:1651)
        at cn.nukkit.Server.tick(Server.java:1024)
        at cn.nukkit.Server.tickProcessor(Server.java:808)
        at cn.nukkit.Server.start(Server.java:787)
        at cn.nukkit.Server.<init>(Server.java:472)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
```
* ...

**Comment by JackboyPlay** [comment]
Issue associated with #1569
