### ISSUE TITLE
Converting MCPE world to Nukkit?

### ISSUE THREAD

**Issue by ili-codes** [Nukkit/Nukkit#1687]
### Issue description

I've been trying to get a creative map I use on MCPE 1.0.6 on my iPod to Nukkit, which I downloaded from Yives' Mirror. There seems to be an issue when converting the world to Nukkit's format.

### Steps to reproduce the issue

1. Move an MCPE world to the worlds folder in Nukkit.
2. Start server
3. Error will occur.

### OS and versions

* Nukkit Version: v1.0.6-b585
 
* Java Version: 1.8.0_121

* Host OS: Mac OS X Lion 10.7.5

* Host Configuration: 4 GB RAM, 160 GB ??(SSD/HDD/...) drive, 2 core CPU from Intel

* Client Edition: iOS

* Client Version: v1.0.6

### Crashdump, backtrace or other files

* 
```
14:42:10 [INFO] Loading nukkit.yml...
14:42:10 [INFO] Loading server properties...
14:42:10 [INFO] Selected English (eng) as the base language
14:42:10 [INFO] Starting Minecraft: PE server version v1.0.6
14:42:10 [INFO] Opening server on 0.0.0.0:19132
14:42:10 [INFO] This server is running Nukkit version 1.0dev "蘋果(Apple)派(Pie)" (API 1.0.0)
14:42:10 [INFO] Nukkit is distributed under the LGPL License
14:42:11 [INFO] Successfully loaded 0 resource packs
14:42:12 [ERROR] Could not load level "crea2": Caused by java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cn.nukkit.level.Level.<init>(Level.java:256)
	at cn.nukkit.Server.loadLevel(Server.java:1600)
	at cn.nukkit.Server.<init>(Server.java:443)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:102)
	at cn.nukkit.level.format.generic.BaseLevelProvider.<init>(BaseLevelProvider.java:36)
	at cn.nukkit.level.format.anvil.Anvil.<init>(Anvil.java:33)
	... 8 more

14:42:12 [ALERT] cn.nukkit.utils.LevelException: Caused by java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cn.nukkit.level.Level.<init>(Level.java:256)
	at cn.nukkit.Server.loadLevel(Server.java:1600)
	at cn.nukkit.Server.<init>(Server.java:443)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:102)
	at cn.nukkit.level.format.generic.BaseLevelProvider.<init>(BaseLevelProvider.java:36)
	at cn.nukkit.level.format.anvil.Anvil.<init>(Anvil.java:33)
	... 8 more

	at cn.nukkit.level.Level.<init>(Level.java:259)
	at cn.nukkit.Server.loadLevel(Server.java:1600)
	at cn.nukkit.Server.<init>(Server.java:443)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

14:42:12 [EMERGENCY] No default level has been loaded
14:42:12 [INFO] Stopping other threads
```
* ...

**Comment by MasterlazorX** [comment]
I don't think you can port MCPE worlds onto Nukkit without tools.

**Comment by ili-codes** [comment]
What tools?

**Comment by tiNsLeY799** [comment]
You have to convert MCPE's leveldb to mcregion or anvil.

**Comment by ili-codes** [comment]
How would I do this? As in, any programs that would help me with this?

**Comment by tiNsLeY799** [comment]
Try MineConverter (at least I think that's the name of it?)

On Apr 19, 2017 7:00 PM, "Iliyan D." <notifications@github.com> wrote:

How would I do this? As in, any programs that would help me with this?



> On Apr 19, 2017, at 8:52 PM, Edward <notifications@github.com> wrote:
>
> You have to convert MCPE's leveldb to mcregion or anvil.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Nukkit/Nukkit/issues/1687#issuecomment-295542800>, or mute
the thread

**Comment by fuyutsuki** [comment]
@ili-codes Please try using this. https://github.com/ljyloo/LevelDb2Avnil

**Comment by ili-codes** [comment]
Tried, and it failed.

**Comment by fuyutsuki** [comment]
@ili-codes this is? https://github.com/ImagicalCorp/MineConvert

**Comment by ili-codes** [comment]
I'll try that... thanks!

**Comment by ili-codes** [comment]
https://github.com/ImagicalCorp/MineConvert/issues/10

1.0 worlds aren't supported, and the app solution in that issue isn't available anymore.

**Comment by ili-codes** [comment]
https://github.com/ImagicalCorp/MineConvert/issues/10

1.0 worlds aren't supported, and the app solution in that issue isn't available anymore.

**Comment by fuyutsuki** [comment]
@ili-codes Oh…sorry…

**Comment by ili-codes** [comment]
It's OK. Is there another app that can do this?

**Comment by ili-codes** [comment]
LevelDB2Avnil gives me no output in "worldanvil"

**Comment by fuyutsuki** [comment]
@ili-codes But probably not working, I think that it is wise to give up…

**Comment by ili-codes** [comment]
I found something! https://github.com/Awzaw/AnvilConverter I'm going to try it later.

**Comment by fuyutsuki** [comment]
@ili-codes Ok!

**Comment by ili-codes** [comment]
Alright. A quick update: the world does not convert. Do you have an archive of the app mentioned in https://github.com/ImagicalCorp/MineConvert/issues/10?

**Comment by fuyutsuki** [comment]
@ili-codes Download from Download zip button.
AnvilConverter doesn't work?

**Comment by ili-codes** [comment]
Nope. I've got a LevelDb world.

**Comment by ili-codes** [comment]
Also, the https://github.com/H4PM/Elywing/wiki/How-to-convert-a-MCRegion-world-to-an-Anvil-world-%3F link doesn't work.

**Comment by fuyutsuki** [comment]
@ili-codes That software of Elywing converts from MCRegion to Anvil.

**Comment by fuyutsuki** [comment]
@ili-codes First we need to change from LevelDB to MCRegion and then to Anvil from there ...

**Comment by Snake1999** [comment]
WELL OK, WE SHOULD NOT DISCUSS ABOUT DEPENDING ON OTHER SOFTWARE. NUKKIT SHOULD BE THE SWISS KNIFE AS EVERY OUR USERS EXPECTED. @ili-codes @fuyutsuki 
Okay let's begin our work here...

**Comment by poustmal** [comment]
ili-codes,load your world in mcpe 0.16.0(you will lose some things in your world and max high is 128 there) and then in nukkit and it should work.idk

**Comment by ili-codes** [comment]
What will I lose?

**Comment by poustmal** [comment]
If this works,that I think it maybe work,you ll lose end rod,end bricks any 1.0 item but other things will be ok I think.

**Comment by ili-codes** [comment]
Alright.. I'll try this. Thanks.

**Comment by erichexter** [comment]
@ili-codes  were you able to convert the world? If so what were the steps that worked for you?

**Comment by ifeghali** [comment]
1) generate a new blank world in nukkit
2) download and install [amulet](https://www.amuletmc.com)
3) open world to be converted in amulet
4) click convert tab
5) select blank world as output
6) click convert button and you are done
