### ISSUE TITLE
An exception is occurred when I use stop command

### ISSUE THREAD

**Issue by Manato0x2cc** [Nukkit/Nukkit#1688]
Hello. This exception is not fatal error but I report it as issue.

### Issue description

I often see **java.lang.StringIndexOutOfBoundsException: String index out of range 2** when I close the server.
I've changed Nukkit.jar to latest Nukkit.jar but the exception is still called...
The exception's message is shown for about ten seconds, and then Nukkit server is forcefully stopped.
### Steps to reproduce the issue

1. ... use stop command

### OS and versions

* Nukkit Version: 1.0dev build #585 
 
* Java Version: 1.8.0_77

* Host OS: Mac

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: Android

* Client Version: 1.0.6
* 
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:555)
	at jline.console.ConsoleReader.backspace(ConsoleReader.java:1057)
	at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1043)
	at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3858)
	at cn.nukkit.command.CommandReader.removePromptLine(CommandReader.java:125)
	at cn.nukkit.Nukkit.main(Nukkit.java:93)

Took too long to stop, server was killed forcefully!
```
* ...

**Comment by adamiss5138** [comment]
Nukkit you have downloaded is over a year old

**Comment by Creeperface01** [comment]
:D

**Comment by Manato0x2cc** [comment]
I downloaded from [http://ci.mengcraft.com:8080/job/Nukkit/](url)

Then where is to get latest nukkit??

**Comment by Creeperface01** [comment]
circle ci

**Comment by Manato0x2cc** [comment]
The exception is no longer shown!!
Thanks a lot!!
