### ISSUE TITLE
found a bug in the 1.0.7, unable to create a torch

### ISSUE THREAD

**Issue by lzskyline** [Nukkit/Nukkit#1698]
I installed nukkit in the centos7 java8.However, when I use formula to made a fire, as I took it will disappear from the producer.And the corresponding error in the nukkit:

[ALERT] java.lang.NullPointerException
        at cn.nukkit.Player.handleDataPacket(Player.java:3346)
        at cn.nukkit.network.Network.processPackets(Network.java:185)
        at cn.nukkit.network.Network.processBatch(Network.java:156)
        at cn.nukkit.Player.handleDataPacket(Player.java:1893)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1010)
        at cn.nukkit.Server.tickProcessor(Server.java:808)
        at cn.nukkit.Server.start(Server.java:787)
        at cn.nukkit.Server.<init>(Server.java:472)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by teflontoni** [comment]
With Charcoal I am able to craft torches, though I am not sure it's the coal, I crafted the torches in my personal crafting box not with a workbench.

Coal + Workbench shows the behaviour mentioned in OP.
