### ISSUE TITLE
Throws exception while stopping the server 

### ISSUE THREAD

**Issue by ningwang747** [Nukkit/Nukkit#1720]
I type the <code>stop</code> then the server throw the exception
<code>Exception_ in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:555)
	at jline.console.ConsoleReader.backspace(ConsoleReader.java:1057)
	at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1043)
	at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3858)
	at cn.nukkit.command.CommandReader.removePromptLine(CommandReader.java:125)
	at cn.nukkit.Nukkit.main(Nukkit.java:93)</code>

and I try to type something while stopping the server
`[ERROR] Failed to disable litteral next character
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
	at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
	at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
	at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
	at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
	at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:194)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2447)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2370)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2358)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2346)
	at cn.nukkit.command.CommandReader.run(CommandReader.java:64)`

Nukkit version :#2048
System types :MacOS(UNIX) x86_64
OS Version :10.12.4(Darwin Kernel Version 16.5.0)

**Comment by asyven** [comment]
### OS and Versions

* Nukkit Version: 1.0dev 

* Java Version: 
```
Java HotSpot(TM) 64-Bit Server VM (1.8.0_131-b11)
```

* Host Configuration: 


| Item | Value |
|:----:|:-----:|
| Host OS | Ubuntu [14.04.5 LTS] |  
| Memory(RAM) | 4.1 GB | 
| Storage Size | 42.9 GB | 
| Storage Type | Unknown  | 
| CPU Type | Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz | 
| CPU Core Count | 4 cores 4 threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | 
| Client Version | ?? | 

### Crashdump, Backtrace or Other Files

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:555)
	at jline.console.ConsoleReader.backspace(ConsoleReader.java:1057)
	at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1043)
	at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3858)
	at cn.nukkit.command.CommandReader.removePromptLine(CommandReader.java:120)
	at cn.nukkit.Nukkit.main(Nukkit.java:93)

```
