### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by vzlomka76** [Nukkit/Nukkit#1744]
### Issue description
When all players quit from server, i can see error in console ()

### Steps to reproduce the issue

1. Start server
2. Wait a few hours (usually after a few hours)
3. You can see error

### OS and versions

* Nukkit Version: https://github.com/Nukkit/Nukkit/commit/755d0371cb07a6cab59ee58f27e9b199cc27511b
 
* Java Version: ??

* Host OS: Linux

* Host Configuration: 3 GB RAM, 20 GB SSD drive, 6 core CPU from ??, ?? Mb internet upload

* Client Edition: Windows 10

* Client Version: 1.0.9

### Crashdump, backtrace or other files

* 
```
09:41:19 [CRITICAL] Could not tick level "lobby": java.lang.NegativeArraySizeException
09:41:19 [ALERT] java.lang.NegativeArraySizeException
        at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
        at java.util.ArrayList.<init>(ArrayList.java:177)
        at cn.nukkit.level.Level.doTick(Level.java:796)
        at cn.nukkit.Server.checkTickUpdates(Server.java:940)
        at cn.nukkit.Server.tick(Server.java:1007)
        at cn.nukkit.Server.tickProcessor(Server.java:802)
        at cn.nukkit.Server.start(Server.java:781)
        at cn.nukkit.Server.<init>(Server.java:469)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
```
* ...

###Plugins
Plugins (5): Api v0.1, Smiley v0.0.3, Regions v0.0.5, DbLib v0.2.1, Multipass v1.1.2

**Comment by Creeperface01** [comment]
my servers running 24 hours and I have never noticed this error on any of them :D but I know I had this error on my local server in the past, but idk why, when etc :D

**Comment by vzlomka76** [comment]
@Creeperface01 Previously, on this map, I had a plugin MobPlugin, could this be related to this?

**Comment by PikyCZ** [comment]
nope
