### ISSUE TITLE
error with chunk

### ISSUE THREAD

**Issue by PhanaticD** [Nukkit/Nukkit#1747]
```
2017-6-8 03:09:39 [ERROR] Error while unloading a chunk: java.lang.RuntimeException: cn.nukkit.utils.ChunkException: Chunk is too big! 1140670 > 1048576^M
2017-6-8 03:09:39 [ALERT] java.lang.RuntimeException: cn.nukkit.utils.ChunkException: Chunk is too big! 1140670 > 1048576
    at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:279)
    at cn.nukkit.level.Level.unloadChunk(Level.java:2670)
    at cn.nukkit.level.Level.unloadChunk(Level.java:2630)
    at cn.nukkit.level.Level.unloadChunks(Level.java:2928)
    at cn.nukkit.level.Level.unloadChunks(Level.java:2906)
    at cn.nukkit.level.Level.doTick(Level.java:778)
    at cn.nukkit.Server.checkTickUpdates(Server.java:945)
    at cn.nukkit.Server.tick(Server.java:1020)
    at cn.nukkit.Server.tickProcessor(Server.java:807)
    at cn.nukkit.Server.start(Server.java:786)
    at cn.nukkit.Server.<init>(Server.java:471)
    at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: cn.nukkit.utils.ChunkException: Chunk is too big! 1140670 > 1048576
    at cn.nukkit.level.format.anvil.RegionLoader.saveChunk(RegionLoader.java:91)
    at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:144)
    at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:277)
    ... 11 more
```

**Comment by shanwer** [comment]
You're not using a nukkit-generation-map.You can try some softwares to translat it.
