### ISSUE TITLE
error with Level

### ISSUE THREAD

**Issue by endymx** [Nukkit/Nukkit#1760]
### Issue description

Write a short description about the issue

### OS and versions

* Nukkit Version: ?? 
 
* Java Version: 180_131

* Host OS: Linux Centos7

* Host Configuration: 1 GB RAM, 40 GB SSD drive, 1 core CPU from Inter

* Client Edition: win10

* Client Version: 1.1.1

01:51:23 [EMERGENCY] Exception happened while ticking server
01:51:23 [ALERT] java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at cn.nukkit.level.format.generic.EmptyChunkSection.getBytes(EmptyChunkSection.java:137)
	at cn.nukkit.level.format.anvil.Anvil.requestChunkTask(Anvil.java:147)
	at cn.nukkit.level.Level.processChunkRequest(Level.java:2471)
	at cn.nukkit.level.Level.doTick(Level.java:862)
	at cn.nukkit.Server.checkTickUpdates(Server.java:927)
	at cn.nukkit.Server.tick(Server.java:1002)
	at cn.nukkit.Server.tickProcessor(Server.java:789)
	at cn.nukkit.Server.start(Server.java:768)
	at cn.nukkit.Server.<init>(Server.java:459)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

2017-6-23 01:51:23 [ALERT] 
"Thread-10" Id=24 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at cn.nukkit.Player$1.run(Player.java:502)

"Nukkit Asynchronous Task Handler #3" Id=23 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@dc7df28
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@dc7df28
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #2" Id=22 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@dc7df28
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@dc7df28
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #1" Id=21 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@dc7df28
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@dc7df28
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #0" Id=20 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@dc7df28
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@dc7df28
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"process reaper" Id=19 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@30f842ca
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@30f842ca
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"threadDeathWatcher-3-1" Id=18 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

"nioEventLoopGroup-2-1" Id=17 RUNNABLE (in native)
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@69c81773
	-  locked java.util.Collections$UnmodifiableSet@4d14b6c2
	-  locked sun.nio.ch.EPollSelectorImpl@7e990ed7
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	...

"RakNet Thread #14" Id=14 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
	at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
	at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
	at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)

"Console" Id=9 RUNNABLE (in native)
	at java.io.FileInputStream.read0(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:207)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
	-  locked jline.internal.NonBlockingInputStream@c05fddc
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
	at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
	-  locked jline.internal.NonBlockingInputStream@c05fddc
	at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
	-  locked jline.internal.NonBlockingInputStream@c05fddc
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2143)
	...

"NonBlockingInputStreamThread" Id=13 WAITING on jline.internal.NonBlockingInputStream@c05fddc owned by "Console" Id=9
	at java.lang.Object.wait(Native Method)
	-  waiting on jline.internal.NonBlockingInputStream@c05fddc
	at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
	at java.lang.Thread.run(Thread.java:745)

"Thread-0" Id=8 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:224)
	at cn.nukkit.utils.MainLogger.run(MainLogger.java:213)

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@25df00a0
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@25df00a0
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@4d15107f
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@4d15107f
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" Id=1 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
	at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:111)
	at cn.nukkit.Server.tickProcessor(Server.java:804)
	at cn.nukkit.Server.start(Server.java:768)
	at cn.nukkit.Server.<init>(Server.java:459)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by Snake1999** [comment]
Unable to reproduce. Does this issue still exist?

**Comment by centic9** [comment]
The error "NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;" sounds like code compiled with Java 9 runtime libraries and then executed with Java 8...
