### ISSUE TITLE
getNearbyEntities(params); throws many errors

### ISSUE THREAD

**Issue by sero583** [Nukkit/Nukkit#1761]
### Issue description
I try to use on a plugin in the EntitySpawnEvent method Level.getNearbyEntites(params); but then it throws me so many errors. To ensure its not a bug by my side I tested it at pmmp and there it works fine.

### Steps to reproduce the issue
1. Write a plugin
2. Use Level.getNearbyEntites(AABB);
3. See how many errors you receive.

### OS and versions
* Nukkit Version: ```Nukkit 1.0dev ???(Apple)?(Pie)? implementing API version 1.0.0 for Minecraft: PE v1.1.0 (protocol version 113)```
* Java Version: openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
* Host OS: Ubuntu 16.04
* Host Configuration: doesn't matters

* Client Configuration: doesn't matters

| Item | Value |
|:----:|:-----:|
| Client edition | Android |
| Client version | 1.1.0 | 

### Crashdump, backtrace or other files
I'm not sure if I copied multiple times the error since I cant really know it because I get so many errors thrown.
```
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at cn.nukkit.entity.Entity.createEntity(Entity.java:659)
at cn.nukkit.level.format.generic.BaseFullChunk.initChunk(BaseFullChunk.java:124)
at cn.nukkit.level.Level.loadChunk(Level.java:2578)
at cn.nukkit.level.Level.getChunk(Level.java:2289)
at cn.nukkit.level.Level.getChunk(Level.java:2282)
at cn.nukkit.level.Level.getChunkEntities(Level.java:2186)
at cn.nukkit.level.Level.getNearbyEntities(Level.java:2147) at plugin.sero583.Test.onAdded(Test.java:134)
at plugin.sero583.EventListener.onEntityAdded(EventListener.java:255)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
at cn.nukkit.entity.Entity.init(Entity.java:420)
at cn.nukkit.entity.Entity.<init>(Entity.java:315)
at cn.nukkit.entity.EntityLiving.<init>(EntityLiving.java:31)
at cn.nukkit.entity.EntityCreature.<init>(EntityCreature.java:12)
at cn.nukkit.entity.passive.EntityAnimal.<init>(EntityAnimal.java:18)
at cn.nukkit.entity.passive.EntityWolf.<init>(EntityWolf.java:18)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at cn.nukkit.entity.Entity.createEntity(Entity.java:659)
at cn.nukkit.level.format.generic.BaseFullChunk.initChunk(BaseFullChunk.java:124)
at cn.nukkit.level.Level.loadChunk(Level.java:2578)
at cn.nukkit.level.Level.getChunk(Level.java:2289)
at cn.nukkit.level.Level.getChunk(Level.java:2282)
at cn.nukkit.level.Level.getChunkEntities(Level.java:2186)
at cn.nukkit.level.Level.getNearbyEntities(Level.java:2147) at plugin.sero583.Test.onAdded(Test.java:134)
at plugin.sero583.EventListener.onEntityAdded(EventListener.java:255)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
at cn.nukkit.entity.Entity.init(Entity.java:420)
at cn.nukkit.entity.Entity.<init>(Entity.java:315)
at cn.nukkit.entity.EntityLiving.<init>(EntityLiving.java:31)
at cn.nukkit.entity.EntityCreature.<init>(EntityCreature.java:12)
at cn.nukkit.entity.passive.EntityAnimal.<init>(EntityAnimal.java:18)
at cn.nukkit.entity.passive.EntityRabbit.<init>(EntityRabbit.java:18)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at cn.nukkit.entity.Entity.createEntity(Entity.java:659)
at cn.nukkit.level.format.generic.BaseFullChunk.initChunk(BaseFullChunk.java:124)
at cn.nukkit.level.Level.loadChunk(Level.java:2578)
at cn.nukkit.level.Level.getChunk(Level.java:2289)
at cn.nukkit.level.Level.getChunk(Level.java:2282)
at cn.nukkit.level.Level.getChunkEntities(Level.java:2186)
at cn.nukkit.level.Level.getNearbyEntities(Level.java:2147) at plugin.sero583.Test.onAdded(Test.java:134)
at plugin.sero583.EventListener.onEntityAdded(EventListener.java:255)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
at cn.nukkit.entity.Entity.init(Entity.java:420)
at cn.nukkit.entity.Entity.<init>(Entity.java:315)
at cn.nukkit.entity.EntityLiving.<init>(EntityLiving.java:31)
at cn.nukkit.entity.EntityCreature.<init>(EntityCreature.java:12)
at cn.nukkit.entity.passive.EntityAnimal.<init>(EntityAnimal.java:18)
at cn.nukkit.entity.passive.EntityRabbit.<init>(EntityRabbit.java:18)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at cn.nukkit.entity.Entity.createEntity(Entity.java:659)
at cn.nukkit.level.format.generic.BaseFullChunk.initChunk(BaseFullChunk.java:124)
at cn.nukkit.level.Level.loadChunk(Level.java:2578)
at cn.nukkit.level.Level.getChunk(Level.java:2289)
at cn.nukkit.level.Level.getChunk(Level.java:2282)
at cn.nukkit.level.Level.getChunkEntities(Level.java:2186)
at cn.nukkit.level.Level.getNearbyEntities(Level.java:2147) at plugin.sero583.Test.onAdded(Test.java:134)
at plugin.sero583.EventListener.onEntityAdded(EventListener.java:255)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by sero583** [comment]
For everyone who wonders what I do, I pass the event from the Listener to another class, but that isn't really the issue.
