### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by xISRAPILx** [Nukkit/Nukkit#1802]
I'm extended PluginBase and implemented Listener. I'm use only ProjectileHitEvent.

onEnable:
```
    @Override
    public void onEnable(){
        this.getLogger().info("RUS: Плагин успешно включен!");
        this.getLogger().info("ENG: Plugin enabled successfully!");

        this.getDataFolder().mkdir();
        this.saveResource("settings.yml", "settings.yml", false);
        this.config = new Config(new File(this.getDataFolder(), "settings.yml"), Config.YAML);
        this.config.save();

        this.getServer().getPluginManager().registerEvents(this, this);
    }
```

Error:
```
[ALERT] java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
        at cn.nukkit.plugin.PluginDescription.loadMap(PluginDescription.java:145)
        at cn.nukkit.plugin.PluginDescription.<init>(PluginDescription.java:136)
        at cn.nukkit.plugin.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:86)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:165)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
        at cn.nukkit.Server.<init>(Server.java:387)
```
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by xISRAPILx** [comment]
I think the problem is the work of this event in the kernel.

**Comment by xISRAPILx** [comment]
I think the problem is the kernel.

**Comment by vzlomka76** [comment]
@xISRAPILx plugin.yml?

**Comment by vzlomka76** [comment]
@xISRAPILx You are use Double in description? (plugin.yml)

**Comment by xISRAPILx** [comment]
@vzlomka76 NoНет ...

**Comment by vzlomka76** [comment]
@xISRAPILx It's problem not in the core, You incorrectly filled the plugin.yml

**Comment by xISRAPILx** [comment]
name: MyShootingRange
version: 1.1
api: ["1.0.0", "2.0.0"]
main: ISRAPIL.TUTTEBENENADO
author: xISRAPILx

@vzlomka76

**Comment by vzlomka76** [comment]
@xISRAPILx My example:
name: BedWarsPE
main: ru.vzlomka76.bedwars.BedWarsPE
version: "0.1"
author: "vzlomka76"
api: ["1.0.0"]
description: BedWars minigame

**Comment by vzlomka76** [comment]
@xISRAPILx Write me in vk.com for help.

**Comment by xISRAPILx** [comment]
I already found a mistake. @vzlomka76

**Comment by vzlomka76** [comment]
@xISRAPILx ???
