### ISSUE TITLE
PEX

### ISSUE THREAD

**Issue by BlockCraftMCPE** [Nukkit/Nukkit#1815]
I've searched for an Good Permissions plugin,but didnt found anything.So i tried to use PermissionsEX loaded over Pokkit.
I've Changed the plugin.yml like the maker of Pokkit have written it.Now i dont Know what This error mean or how to fix it:

2017-7-24 16:53:49 [INFO] [Pokkit] [PermissionsEx] Enabling PermissionsEx v1.23.4
2017-7-24 16:53:49 [WARNING] [Pokkit] Enabled plugin with unregistered PluginClassLoader PermissionsEx v1.23.4
2017-7-24 16:53:51 [ERROR] [Pokkit] [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>. Full error:
java.lang.NullPointerException
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:64)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.enablePlugin(PokkitPluginLoader.java:69)
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
	at cn.nukkit.Server.enablePlugin(Server.java:620)
	at cn.nukkit.Server.enablePlugins(Server.java:609)
	at cn.nukkit.Server.<init>(Server.java:462)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

2017-7-24 16:53:51 [ERROR] [Pokkit] [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>. Full error:
java.lang.NullPointerException
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:64)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.enablePlugin(PokkitPluginLoader.java:69)
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
	at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.enablePlugin(PokkitPluginManager.java:107)
	at nl.rutgerkok.pokkit.pluginservice.PluginService.enablePlugins(PluginService.java:22)
	at nl.rutgerkok.pokkit.pluginservice.PluginService.onEnable(PluginService.java:29)
	at nl.rutgerkok.pokkit.Pokkit.lambda$1(Pokkit.java:113)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at nl.rutgerkok.pokkit.Pokkit.onEnable(Pokkit.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at nl.rutgerkok.pokkit.startup.NukkitHook.onEnable(NukkitHook.java:26)
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
	at cn.nukkit.Server.enablePlugin(Server.java:620)
	at cn.nukkit.Server.enablePlugins(Server.java:609)
	at cn.nukkit.Server.<init>(Server.java:462)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

2017-7-24 16:53:51 [INFO] [Pokkit] [PermissionsEx] Disabling PermissionsEx v1.23.4

Here is the File:

https://drive.google.com/file/d/0B-97qVsSDgtWeVRBZGhiLVdydTQ/view?usp=drivesdk

Hope anyone can help,
BLOCKSTORM

**Comment by vzlomka76** [comment]
hmmm, good permission plugin is Multipass, but this error you can write to Pokkit repository

**Comment by vzlomka76** [comment]
Please close this, it's not a Nukkit error

**Comment by BlockCraftMCPE** [comment]
How to close it? Im On Android

**Comment by BlockCraftMCPE** [comment]
Oh,ok
