### ISSUE TITLE
The console can not enter a command and the main thread stuck

### ISSUE THREAD

**Issue by WetABQ** [Nukkit/Nukkit#1817]
### Issue Description
Main thread deadlock
Server console stuck, can not enter the command, the player will not be quit but in addition to asynchronous thread plugin can operate other  core of the main functions are not working
Even if a completely new server will exist(This server is completely new without plugins and settings)
服务器控制台卡死，无法输入命令，玩家不会掉线但除了异步线程的插件可以运作其他都不行并且核心的主要功能都无法运作
就算是新开一个服务器这个问题还会存在(这个服务器完全是新的不存在插件和设置)
And no player presence can also cause this problem
并且没有玩家存在也可能造成这个问题

### Steps to Reproduce the Issue
1. Start the server
2. Wait....
3. Main thread deadlock.
But this is a probabilistic event.
And not all servers will happen.
But once the encounter will continue to trigger.
### OS and Versions
* Nukkit Version: d028383d4920468f0e15fbbc44531e2209855464
* Java Version: openjdk version:
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Ubuntu |  
| Memory(RAM) | 4 GB | 
| Storage Size | 128 GB | 
| Storage Type | SSHD | 
| CPU Type | E5-2695v3  | 
| CPU Core Count | 4 cores 4 threads | 
| Upstream Bandwidth | 1Gbps | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Android&IOS&Windows10 | 
| Client Version | 1.1+(1.1.3) | 

### Crashdump, Backtrace or Other Files
No error, you do not know when the thread stuck
完全无报错,你根本不知道什么时候线程卡死了

**Comment by ScraM-Team** [comment]
I am seeing the same thing.  This thread seems to be in common between each of my stack traces:

`"main" #1 prio=5 os_prio=0 tid=0x00007f7154009000 nid=0x4a0 runnable [0x00007f715b6ea000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ThreadLocal$ThreadLocalMap.getEntryAfterMiss(ThreadLocal.java:444)
        at java.lang.ThreadLocal$ThreadLocalMap.getEntry(ThreadLocal.java:419)
        at java.lang.ThreadLocal$ThreadLocalMap.access$000(ThreadLocal.java:298)
        at java.lang.ThreadLocal.get(ThreadLocal.java:163)
        at cn.nukkit.utils.Zlib.inflate(Zlib.java:56)
        at cn.nukkit.utils.Zlib.inflate(Zlib.java:37)
        at cn.nukkit.network.Network.processBatch(Network.java:128)
        at cn.nukkit.Player.handleDataPacket(Player.java:1932)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)`

**Comment by shanwer** [comment]
Yes.Many users have this problem but nobody fixes it.We don't know what the problem is at all.It happens on Windows easier.
是的。许多用户都有这个问题但是没人修它。我们根本不知道这是什么问题。它更容易出现在Windows上

**Comment by WetABQ** [comment]
But the strange is that the thread stuck and will not make players dropped, and some multi-threaded plugin can work
但是诡异的是线程卡死并不会使玩家掉线,并且一些多线程的插件可以正常工作

**Comment by shanwer** [comment]
But players can do nothing there.I meant what they do can't saved into the server.Boybook said we can use jmc to check which class let the thread stuck.
但是玩家们在那什么都做不了。我的意思是他们做的事不能被保存进服务器。Boybook说我们可以用JMC看看是哪个类让线程卡死。

**Comment by WetABQ** [comment]
Multi-threaded plug-ins can work properly
多线程插件可以正常工作
![image](https://user-images.githubusercontent.com/25319400/28611142-65a2877a-721d-11e7-9690-9955c2a0b2ae.png)

**Comment by shanwer** [comment]
因为它不会跟主线程挤在一起
Because it won't work with the main thread together.

**Comment by Creeperface01** [comment]
Raknet runs in different thread and multithreaded plugins too, so if only main thread stucks, then other threads will still work

**Comment by shanwer** [comment]
After deleting one of my server's plugin.The bug disappeared.
在删除了我服务器的其中一个插件。BUG消失了。

**Comment by WetABQ** [comment]
Yes, so the player does not quit, and the normal display motd.
是的，因此玩家并不会掉线，并且正常显示motd.

**Comment by lsw46** [comment]
How can we fix this problem?

**Comment by Creeperface01** [comment]
I have 10 nukkit servers running 24/7 and it never happened so it is probably caused by a plugin

**Comment by lsw46** [comment]
There are only 5 plugins

**Comment by ScraM-Team** [comment]
@Creeperface01, are you running a very recent build?  My stack trace suggests a possible problem in ZLib.java, which changed just 16 days ago.  

I have made a branch which reverts just that one file to see if the problem goes away.

**Comment by Creeperface01** [comment]
Im not, so maybe you are right

**Comment by ScraM-Team** [comment]
If the change is stable for me (no more ZLib in the stack traces during server freezes), I will make a pull request for it.

**Comment by WetABQ** [comment]
Thank you so much
那可真谢谢你们了
I have already said that this is a probabilistic event
我已经说过这是一个概率事件
The probability is very low, but will continue to trigger
概率极低，但是碰上就会不断触发

**Comment by Angelic47** [comment]
That's a interesting bug, @ScraM-Team  shows that there are a packet which cause ZLib hang up.
It's hard to reproduce, and there is no better way to attach debug tools when deadlock was trigger.
I tried to start a new server on my windows virtual machine, waiting for a long time but nothing happend.
The thing we know yet is **only MainThread** will stuck **randomly**, and MainThread just handle the server ticking, such as NetworkPacket, Level, Player, Event...
So I think the input data could be the cause, since there are no other data input excpet network, the major problem could be ZLib. Just my guess, I don't know if that's right or not.
~~If true, we could make a server crasher XD, Just a joke~~
@shanwer says that Windows server will happens easier, so I'm guessing if there are some Windows services send the udp packet which blews up Zlib.
@WetABQ try to start a server with out network connection, will this problem trigger again?
I'm continue stay focus on this bug.

这个bug比较有意思, @ScraM-Team 表示有个数据包把ZLib给卡住了.
问题比较难复现, 有一个原因是一旦问题发生之后没有比较好的办法附加调试工具.
我在我的windows虚拟机上开了一个新服, 等了一段时间, 并没有发现这个问题.
目前我们知道的是 **仅仅主线程** 会 **随机性** 卡住, 主线程只用于服务器的tick处理，比如处理数据包、地图、玩家、事件等等……
所以综上我倒是认为输入数据可能是问题的原因，加之除了网络通讯之外没有别的输入数据，那ZLib就是最可能的原因了. 仅仅是猜测, 不知道是否正确.
~~如果确实是这个原因, 那都能做个炸服器了XD, 开个玩笑~~
@shanwer 说Windows的服务器会更容易出这个问题, 所以我猜是不是Windows有什么服务会发送udp包, 让ZLib爆炸了.
@WetABQ 试试开个服, 断开服务器的网络连接, 还会有这个问题出现么?
我这将会继续关注这个问题.

**Comment by WetABQ** [comment]
我的主机目前正在重装系统尝试解决这个问题
My host is currently reloading the system to try to solve this problem
发生这个问题的时候常常是在玩家刚刚进入服务器
This happens when the player is just entering the server
而且玩家反映总是卡在向微软发送数据包阶段。
这时候服务器已经卡死了
And the player is always stuck in sending a packet to Microsoft.
This time the server has been stuck
但这个问题不限于在玩家进入的时候发生，就算完全没有任何玩家进入过，也会造成这个bug
But this problem is not limited to when the player into the time, even if no player has entered, will cause this bug
只是有时候玩家进入服务器，服务器就卡死了
But sometimes the player into the server, the server stuck

**Comment by Angelic47** [comment]
Hmm... So do you know client version the player used?
所以你知道玩家用的是什么版本的客户端么

**Comment by Angelic47** [comment]
Oops sorry I clicked close

**Comment by WetABQ** [comment]
Minecraft version v1.1.3

**Comment by ScraM-Team** [comment]
ScraM for MCPE has been up for a whole day now with my changed version, no lockups due to this issue as far as I can tell.  All I did was roll back the ZLib.java change from
https://github.com/Nukkit/Nukkit/commit/18221f780bca9ab12827d3cb381869525b410be3

(By the way, I like the Zlib.java change intent -- to reduce memory churn by reusing a buffer.  I hope we can put it back soon in a slightly different form with no side effects.)

My version is probably using up memory faster.  However, I prefer faster memory consumption to the freezes that are hard to detect and recover from automatically.  Nukkit's memory usage is already much lower than Vanilla Minecraft PC servers -- kudos to the Nukkit team!

**Comment by WetABQ** [comment]
呃..所以说这个问题到底有没有被解决
Uh .. so that the problem in the end has not been resolved?
就是说因为16天前的修改所以造成了Zlib的问题吗?
That is because 16 days ago because of the change caused Zlib problem

**Comment by WetABQ** [comment]
这个问题在我回滚18221f7之前的版本被修复
This question was repaired before my rollback 18221f7 version

**Comment by Angelic47** [comment]
@WetABQ Make a pull requests, just revert Zlib.java for temporary fix this problem.
提交一个只回滚Zlib.java的pr，临时修复这个问题.

**Comment by ScraM-Team** [comment]
I am about to check in my fix and create a pull request.  It has been working now for ScraM for several days.

**Comment by ScraM-Team** [comment]
Thanks, @Angelic47 !

@WetABQ , @lsw46 , can you please try out the latest build and see if it helps?
http://ci.mengcraft.com:8080/job/Nukkit/619/

**Comment by WetABQ** [comment]
This issue was fixed in the latest version. @ScraM-Team

**Comment by NycuRO** [comment]
Revented. @WetABQ
