### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#182]
Join on new Nukkit server from MC:Win10 Ed and get this
```
09:06:36 [NOTICE] Player data not found for "cursivegeoduck9", creating new profile
09:06:36 [ALERT] java.lang.RuntimeException: java.io.EOFException
        at cn.nukkit.level.format.generic.BaseRegionLoader.<init>(BaseRegionLoader.java:54)
        at cn.nukkit.level.format.mcregion.RegionLoader.<init>(RegionLoader.java:23)
        at cn.nukkit.level.format.mcregion.McRegion.loadRegion(McRegion.java:345)
        at cn.nukkit.level.format.mcregion.McRegion.loadChunk(McRegion.java:237)
        at cn.nukkit.level.format.mcregion.McRegion.getChunk(McRegion.java:303)
        at cn.nukkit.level.format.mcregion.McRegion.getChunk(McRegion.java:33)
        at cn.nukkit.level.Level.loadChunk(Level.java:2073)
        at cn.nukkit.level.Level.getChunk(Level.java:1823)
        at cn.nukkit.level.Level.getSafeSpawn(Level.java:2211)
        at cn.nukkit.level.Level.getSafeSpawn(Level.java:2201)
        at cn.nukkit.Server.getOfflinePlayerData(Server.java:1307)
        at cn.nukkit.Player.processLogin(Player.java:1489)
        at cn.nukkit.Player.authenticateCallback(Player.java:1454)
        at cn.nukkit.Player.tryAuthenticate(Player.java:1443)
        at cn.nukkit.Player.onPlayerPreLogin(Player.java:1439)
        at cn.nukkit.Player.handleDataPacket(Player.java:1798)
        at cn.nukkit.network.Network.processBatch(Network.java:152)
        at cn.nukkit.Player.handleDataPacket(Player.java:1707)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:927)
        at cn.nukkit.Server.tickProcessor(Server.java:749)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.io.EOFException
        at java.io.RandomAccessFile.readInt(RandomAccessFile.java:803)
        at cn.nukkit.level.format.mcregion.RegionLoader.loadLocationTable(RegionLoader.java:221)
        at cn.nukkit.level.format.generic.BaseRegionLoader.<init>(BaseRegionLoader.java:49)
        ... 26 more
```

**Comment by caoli5288** [comment]
Maybe protocol compatible issue.

**Comment by caoli5288** [comment]
Maybe protocol compatible issue.

**Comment by caoli5288** [comment]
Maybe protocol compatible issue.

**Comment by xpyctum** [comment]
maybe

**Comment by MagicDroidX** [comment]
How to reproduce?

**Comment by xpyctum** [comment]
@MagicDroidX try join on new nukkit server from mc win10 Edition.

**Comment by MagicDroidX** [comment]
It seems to be caused by level not w10.

**Comment by xpyctum** [comment]
maybe. can you fix this?

**Comment by xpyctum** [comment]
#64 build. Some error.

**Comment by xpyctum** [comment]
Wow, try connect from mcpe 0.13.1 and get some error. 
I would try to delete my world.

**Comment by xpyctum** [comment]
It's generation not works. I just upload any mcregion world and it's works fine!
