### ISSUE TITLE
Bug Minecart

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1833]
### Issue Description

Write a short description about the issue
18:59:23 [CRITICAL] Unhandled exception executing command 'skyblock' in is: java.lang.ArrayIndexOutOfBoundsException: 12
        at cn.nukkit.block.BlockVine.onUpdate(BlockVine.java:178)
        at cn.nukkit.level.Level.updateAround(Level.java:1258)
        at cn.nukkit.level.Level.setBlock(Level.java:1689)
        at com.larryTheCoder.schematic.IslandBlock.paste(IslandBlock.java:435)
        at com.larryTheCoder.schematic.Schematic.lambda$pasteSchematic$1(Schematic.java:485)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at com.larryTheCoder.schematic.Schematic.pasteSchematic(Schematic.java:484)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:229)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:188)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:63)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:52)
        at com.larryTheCoder.Commands.execute(Commands.java:91)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:638)
        at cn.nukkit.Player.handleDataPacket(Player.java:3127)
        at cn.nukkit.network.Network.processPackets(Network.java:180)
        at cn.nukkit.network.Network.processBatch(Network.java:151)
        at cn.nukkit.Player.handleDataPacket(Player.java:1992)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

18:59:23 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 12
        at cn.nukkit.block.BlockVine.onUpdate(BlockVine.java:178)
        at cn.nukkit.level.Level.updateAround(Level.java:1258)
        at cn.nukkit.level.Level.setBlock(Level.java:1689)
        at com.larryTheCoder.schematic.IslandBlock.paste(IslandBlock.java:435)
        at com.larryTheCoder.schematic.Schematic.lambda$pasteSchematic$1(Schematic.java:485)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at com.larryTheCoder.schematic.Schematic.pasteSchematic(Schematic.java:484)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:229)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:188)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:63)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:52)
        at com.larryTheCoder.Commands.execute(Commands.java:91)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:638)
        at cn.nukkit.Player.handleDataPacket(Player.java:3127)
        at cn.nukkit.network.Network.processPackets(Network.java:180)
        at cn.nukkit.network.Network.processBatch(Network.java:151)
        at cn.nukkit.Player.handleDataPacket(Player.java:1992)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

### Steps to Reproduce the Issue

1. Put one Minecart Hopper to rail
2. Click to them
3. Get error 

### OS and Versions

* Nukkit Version: ?? 

* Java Version: https://github.com/Nukkit/Nukkit/commit/b190802a4a3f67064ceae824dbddae16d4974fb5
```
??
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Windows 10 |  
| Memory(RAM) | 8 GB | 
| Storage Size | 1TB | 
| Storage Type | HDD | 
| CPU Type | i7 4720hq 2.6 max 3.6 | 
| CPU Core Count | 2.6 cores 8 threads | 
| Upstream Bandwidth | 150mbp/s | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Windows 10 | 
| Client Version | 1.1.4 | 

### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```

**Comment by Snake1999** [comment]
Regenerate your world and try again. It might be the meta value difference between Minecraft c++ and Minecraft Java.

**Comment by NycuRO** [comment]
@Snake1999 Please check your email
