### ISSUE TITLE
2 Issues.

### ISSUE THREAD

**Issue by NycuRO** [Nukkit/Nukkit#1837]
Sorry if i don't use ISSUE Template, but it's more easy that.

I have 2 issues with Nukkit:

**ISSUE 1**
When i'm fighting with more players, he stucks.

Steps to Reproduce:
1. Enter on Server.
2. Attack one player and them attack you.
3. Get blocked.

**ISSUE 2**
Client is freezes randomly.

Steps to Reproduce:
1. Enter on server.
2. Move on map.
3. Get freeze...

When i'm freezed i'm on Desert Biome.

Version Client: 1.1.4 
Version OS: Windows 10.
It's reproduced and on Android.
Version Software: https://github.com/Nukkit/Nukkit/commit/b190802a4a3f67064ceae824dbddae16d4974fb5

Single error who i have on console is by one Plugin, MadPerms, when players enter on server:

```
20:18:18 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerJoinEvent' to 'MadPerms v1.0.0': null on me.imjack.permissions.listeners.PlayerListeners
20:18:18 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.Player.doFirstSpawn(Player.java:785)
        at cn.nukkit.Player.sendNextChunk(Player.java:741)
        at cn.nukkit.Player.checkNetwork(Player.java:1743)
        at cn.nukkit.Server.tick(Server.java:1010)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NullPointerException
        at a.e.b.addAttachment(NukkitPlayer.java:501)
        at cn.nukkit.Player.addAttachment(Player.java:429)
        at cn.nukkit.Player.addAttachment(Player.java:424)
        at me.imjack.permissions.listeners.PlayerListeners.onJoin(PlayerListeners.java:24)
        at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 10 more
```

**Comment by WetABQ** [comment]
check your plugins

**Comment by NycuRO** [comment]
@WetABQ Yes, is.

**Comment by ScraM-Team** [comment]
@NycuRO , could you attach a stack trace when it happened without plugins?  I think the plugin in question is "me.imjack.permissions".  Take it out of the plugins folder, reproduce the issue, and send in the new stack trace, please.

**Comment by lsw46** [comment]
I have the same problem...
But But I rolled back to 4f6f586[https://github.com/Nukkit/Nukkit/commit/4f6f586ce511949212a5a43a9cc663f1ed48f2b2](url) The problem disappeared

**Comment by Guillaume351** [comment]
Same problem, rolled back too
