### ISSUE TITLE
Some chunk crash my server

### ISSUE THREAD

**Issue by rusinc** [Nukkit/Nukkit#1874]
### Issue Description

i dont know why, but when i enter in the some chunk, server has freeze. All players kicked by timeout and after lags i receive error in console. I know, what this chunk been correct, but, probably, players put some incorrect block

### Steps to Reproduce the Issue

Enter some chunk
### OS and Versions

* Nukkit Version:  1.0dev「 蘋果(Apple)派(Pie) 

* Java Version: 
```
8
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS |Linux |  
| Memory(RAM) | 16 GB | 
| Storage Size | 200 GB | 
| Storage Type | SSD | 
| CPU Type | AMD ?? | 
| CPU Core Count | ?? cores ?? threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | All editions | 
| Client Version | 1.1.X | 

### Crashdump, Backtrace or Other Files

Ошибка при выгрузке чанка: java.lang.RuntimeException: cn.nukkit.utils.ChunkException: Chunk is too big! 1195740 > 1048576 
2017-8-23 03:03:58 [ALERT] java.lang.RuntimeException: cn.nukkit.utils.ChunkException: Chunk is too big! 1195740 > 1048576 
at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:279) 
at cn.nukkit.level.Level.unloadChunk(Level.java:2690) 
at cn.nukkit.level.Level.unloadChunk(Level.java:2650) 
at cn.nukkit.level.Level.unloadChunks(Level.java:2948) 
at cn.nukkit.level.Level.unloadChunks(Level.java:2926) 
at cn.nukkit.level.Level.doTick(Level.java:783) 
at cn.nukkit.Server.checkTickUpdates(Server.java:932) 
at cn.nukkit.Server.tick(Server.java:1007) 
at cn.nukkit.Server.tickProcessor(Server.java:794) 
at cn.nukkit.Server.start(Server.java:773) 
at cn.nukkit.Server.<init>(Server.java:464) 
at cn.nukkit.Nukkit.main(Nukkit.java:68) 
Caused by: cn.nukkit.utils.ChunkException: Chunk is too big! 1195740 > 1048576 
at cn.nukkit.level.format.anvil.RegionLoader.saveChunk(RegionLoader.java:91) 
at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:144) 
at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:277) 
... 11 more
```
<!--- Copy and paste your backtrace here... -->
```

**Comment by PeratX** [comment]
Do you understand what is ```Chunk is too big! 1195740 > 1048576```? 
That means you are using a non-nukkit-generate map!

Take a look at this https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/level/format/anvil/RegionLoader.java#L91

**Comment by Ivanzar** [comment]
@PeratX Do you know how to fix this problem ?

**Comment by rusinc** [comment]
@PeratX  but i haven't problems on this chunk before. what can happen on correct chunk?

**Comment by NycuRO** [comment]
Closed.
