### ISSUE TITLE
Nukkit posted OutOfMemory crushdump

### ISSUE THREAD

**Issue by rusinc** [Nukkit/Nukkit#1885]
### Issue Description

??

### Steps to Reproduce the Issue

i dont know

### OS and Versions
* Nukkit Version: 1.0dev 
* Git Commit Abbrev: 5b04671
* Java Version: 
```
Java HotSpot(TM) 64-Bit Server VM (1.8.0_144-b01)
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Ubuntu [14.04.5 LTS] |  
| Memory(RAM) | 16.7 GB | 
| Storage Size | 128.0 GB | 
| Storage Type | TS128GSSD370S  | 
| CPU Type | Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz | 
| CPU Core Count | 4 cores 8 threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | 
| Client Version | ?? | 

### Crashdump, Backtrace or Other Files

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at cn.nukkit.nbt.tag.IntTag.copy(IntTag.java:52)
	at cn.nukkit.nbt.tag.CompoundTag.copy(CompoundTag.java:225)
	at cn.nukkit.nbt.tag.CompoundTag.copy(CompoundTag.java:12)
	at cn.nukkit.nbt.tag.ListTag.copy(ListTag.java:121)
	at cn.nukkit.nbt.tag.CompoundTag.copy(CompoundTag.java:225)
	at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:368)
	at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:143)
	at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:277)
	at cn.nukkit.level.Level.saveChunks(Level.java:1210)
	at cn.nukkit.level.Level.save(Level.java:1197)
	at cn.nukkit.level.Level.save(Level.java:1181)
	at cn.nukkit.level.Level.close(Level.java:443)
	at cn.nukkit.level.Level.unload(Level.java:587)
	at cn.nukkit.Server.unloadLevel(Server.java:1552)
	at cn.nukkit.Server.forceShutdown(Server.java:727)
	at cn.nukkit.Server.start(Server.java:774)
	at cn.nukkit.Server.<init>(Server.java:464)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

```

**Comment by SupremeMortal** [comment]
What are your JVM arguments?

**Comment by rusinc** [comment]
i start server with this
libs="./libs/*"
java -cp $libs:"./nukkit-1.0-SNAPSHOT.jar" "cn.nukkit.Nukkit"

**Comment by SupremeMortal** [comment]
Why not just `java -jar nukkit-1.0-SNAPSHOT.jar` ?

**Comment by PeratX** [comment]
try -Xmx4096m

**Comment by rusinc** [comment]
@SupremeMortal i need to load some libraries for my plugins

**Comment by rusinc** [comment]
@PeratX Probably, problem go away, but not by argument. I think, it is from world's issues, and i replaced it and problem has been liquidated.
