### ISSUE TITLE
[ALERT] java.lang.StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit/Nukkit#1887]
### Issue Description
I get this some times when I stop my server:

[ALERT] java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:555)
	at jline.console.ConsoleReader.backspace(ConsoleReader.java:1057)
	at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1043)
	at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3858)
	at cn.nukkit.command.CommandReader.unstashLine(CommandReader.java:112)
	at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:242)
	at cn.nukkit.utils.MainLogger.run(MainLogger.java:213)

### OS and Versions

* Nukkit Version: CircleCI Build #2101 

* Java Version: 1.8.0_131

**Comment by PeratX** [comment]
In fact, you can ignore it.

**Comment by PetteriM1** [comment]
Yes but why this come?

**Comment by PeratX** [comment]
idk
