### ISSUE TITLE
Debian 7 animals,mobs and more dont spawn

### ISSUE THREAD

**Issue by erwbar1** [Nukkit/Nukkit#1927]
Hello,
I try play with my friend in minecraft PE,
I have VPS and i take nukkit server.
All is ok, server is online, but i dont have animals, mobs and others monesters.
In server.properites i have all on, but they dont spawned, why?
Help me please.

**Comment by erwbar1** [comment]
I install novamobs 1.2 and i have this when i try turn on my server:
[ALERT] java.lang.RuntimeException: java.lang.NullPointerException
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
        at cn.nukkit.Server.enablePlugin(Server.java:627)
        at cn.nukkit.Server.enablePlugins(Server.java:616)
        at cn.nukkit.Server.reload(Server.java:691)
        at cn.nukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:28)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:645)
        at cn.nukkit.command.CommandReader.lambda$run$0(CommandReader.java:75)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:283)
        at cn.nukkit.Server.tick(Server.java:1006)
        at cn.nukkit.Server.tickProcessor(Server.java:801)
        at cn.nukkit.Server.start(Server.java:780)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NullPointerException
        at com.pikycz.novamobs.NovaMobs.onEnable(NovaMobs.java:141)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        ... 14 more

**Comment by ZizzyZizzy** [comment]
This is not a help forum, this is for reporting software bugs only. If you think you have experienced a bug in Nukkit, you **must** follow the bug format that is provided, or your report will be ignore and closed.

Regarding mobs, please check out the "Help and FAQ" section of the forums before asking a question that has been asked 100 times before:

https://forums.nukkit.io/search/772418/?q=mobs&o=date&c[node]=8

**Comment by erwbar1** [comment]
OK great, im in google page from 2 days, i open 1000 pages, and still dont have animals on my server. 
Plugins dont work, or is in development.
If you know how i can do that please tell me and i go play, and i dont write here again... :( 
Nukkit is great, but why dont have animals and other monsters in standard edition? Game without this is boring so much

**Comment by SupremeMortal** [comment]
@erwbar1 It's not implemented yet because there are more important issues to deal with before implementing a new system which could cause a variety of new bugs.

**Comment by erwbar1** [comment]
So now i cant add mobs on this server, right?  Novamobs 1.2 is new, added 2 Days ago nad dont work? Im very---> :(

**Comment by sero583** [comment]
@ewbar1 Thats a plugin issue and does not have anything to do with Nukkit itself. Go ahead and report it at the plugins repository (https://github.com/CoreXDevelopment/NovaMobs)

Also if you want all vanilla features, the simplest thing would be either opening a local world and playing via portforward or inviting via Xbox live your friend or basically buy a realm. Yes they don't support plugins, but I think your intention is playing on a normal vanilla server.

**Comment by erwbar1** [comment]
yes right but i like  play with my friends, when server ja online 24/7 and when we have time we joint to server. When im offline and i cant play my friends cant play top, this od shit :/. 
So i buy vps and would take online server and all was Good, only this fucking animals dont spawn:(

**Comment by PetteriM1** [comment]
Why can't mobs implemented to Nukkit?

**Comment by sero583** [comment]
@PetteriM1 If you would mind reading @SupremeMortal's answer, you would also know it.

**Comment by PetteriM1** [comment]
ok

**Comment by sero583** [comment]
@erwbar1 Please dont use such words here first, second then buy maybe a realm? Best soloution in my eyes. NovaMobs don't have auto-spawn implemented or either will, but the first EntityAI plugin which was made on Nukkit afaik has a auto-spawn feature.

**Comment by erwbar1** [comment]
Can you give me .jar from this plugin? I want install this plugin and try spawn animals and mobs. 
I cant find .jar, evrywhere i must compilate, and i dont know how... :( 
Im sory.. :(

**Comment by PetteriM1** [comment]
Use NovaMobs + **[this](https://sites.google.com/site/downloadcenterpetterim1/home/MobAI.jar?attredirects=0&d=1)** plugin for mobs and autospawn.

**Comment by erwbar1** [comment]
ok nad novamobs 1.2 right ? I test it Today, and i write here did this work. Sory for my english, im low:(

**Comment by erwbar1** [comment]
and *

**Comment by PetteriM1** [comment]
Yes, use NovaMobs 1.2 for MobAI and **[this](https://sites.google.com/site/downloadcenterpetterim1/home/MobAI.jar?attredirects=0&d=1)** for autospawn.

**Comment by erwbar1** [comment]
thank you very much but dont work, this novamobs 1.2 dont work, i have this bug when i reload server:
`[ALERT] java.lang.RuntimeException: java.lang.NullPointerException
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
        at cn.nukkit.Server.enablePlugin(Server.java:627)
        at cn.nukkit.Server.enablePlugins(Server.java:616)
        at cn.nukkit.Server.reload(Server.java:691)
        at cn.nukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:28)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:645)
        at cn.nukkit.Player.handleDataPacket(Player.java:2546)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:1985)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:998)
        at cn.nukkit.Server.tickProcessor(Server.java:801)
        at cn.nukkit.Server.start(Server.java:780)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NullPointerException
        at com.pikycz.novamobs.NovaMobs.onEnable(NovaMobs.java:141)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        ... 20 more
`
1.1 version too dont work, 1.0.4 i have crash nukkit engine when i try turn on server. :( 
I dont know why this dont work, this 1.2 version look good, and when i turn on server first time was all ok. When i try reload server plugin exit and i see this text (up); 
Petter help me man :( 
When i try spawn mobs and write in server console: /mob summon pig i have command "Unable spawn pig" :/

**Comment by sero583** [comment]
@erwbar1 Okay this is definetly a NovaMobs bug now, go ahead and report it there to get a fix or maybe download the latest NovaMobs where it's fixed. Seems that issue happens when plugin tries to start, a value is still null which should not be that's why it wont start.

**Comment by sero583** [comment]
Should be fixed in next build after my PR https://github.com/CoreXDevelopment/NovaMobs/pull/84 will be merged, but why summon do not works I only have a guess why it does not work I'm not sure at all, but is that command really that important? Maybe use spawning eggs?

**Comment by erwbar1** [comment]
ok i wait on new build novamobs. Maybe they fix it. Thank you very much for that help! What is it spawning eggs,how it work?

**Comment by PetteriM1** [comment]
Is there any working mob plugin with autospawn anymore?

**Comment by sero583** [comment]
@PetteriM1 I could implement into it a good autospawn.
@erwbar1 Normal spawn eggs (from creative mode) or gather them via /give command.

**Comment by NuclearSteven** [comment]
Plugin issue
