### ISSUE TITLE
Jukebox cause world corruption

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit/Nukkit#1929]
### Issue Description
If you place jukebox chunk get corrupted.

### Steps to Reproduce the Issue

1. Place jukebox.
2. Try to save world.

### OS and Versions

* Nukkit Version: 1.2 

* Java Version: 1.8.0_131

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Lubuntu |  
| Memory(RAM) | 2 GB | 
| Storage Size | ?? GB | 
| Storage Type | HDD | 
| CPU Type | ?? | 
| CPU Core Count | ?? cores ?? threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition |Windows 10 | 
| Client Version | 1.2.3| 

### Crashdump, Backtrace or Other Files

[CRITICAL] Unhandled exception executing command 'save-all' in save-all: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at cn.nukkit.level.Level.saveChunks(Level.java:1200)
	at cn.nukkit.level.Level.save(Level.java:1183)
	at cn.nukkit.command.defaults.SaveCommand.execute(SaveCommand.java:34)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:247)
	at cn.nukkit.Server.dispatchCommand(Server.java:645)
	at cn.nukkit.Player.handleDataPacket(Player.java:2546)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at cn.nukkit.network.Network.processPackets(Network.java:184)
	at cn.nukkit.network.Network.processBatch(Network.java:166)
	at cn.nukkit.Player.handleDataPacket(Player.java:1985)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:998)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:279)
	at cn.nukkit.level.Level.saveChunks(Level.java:1196)
	... 18 more
Caused by: java.lang.NullPointerException

2017-11-4 14:47:52 [ALERT] java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at cn.nukkit.level.Level.saveChunks(Level.java:1200)
	at cn.nukkit.level.Level.save(Level.java:1183)
	at cn.nukkit.command.defaults.SaveCommand.execute(SaveCommand.java:34)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:247)
	at cn.nukkit.Server.dispatchCommand(Server.java:645)
	at cn.nukkit.Player.handleDataPacket(Player.java:2546)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at cn.nukkit.network.Network.processPackets(Network.java:184)
	at cn.nukkit.network.Network.processBatch(Network.java:166)
	at cn.nukkit.Player.handleDataPacket(Player.java:1985)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:998)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:279)
	at cn.nukkit.level.Level.saveChunks(Level.java:1196)
	... 18 more
Caused by: java.lang.NullPointerException

**Comment by SupremeMortal** [comment]
It looks like just a simple NPE that needs fixing.

**Comment by Creeperface01** [comment]
I'll fix it!

**Comment by Creeperface01** [comment]
that helped me to find more bugs with blocketntities :D
