### ISSUE TITLE
nukkit funktioniert nicht

### ISSUE THREAD

**Issue by danieltaraba** [Nukkit/Nukkit#1935]
das ist mein problem
[INFO] Starte Minecraft: PE mit Version v1.2.0.31 beta
14:02:19 [INFO] Starte Server auf 84.200.109.15:19132
14:02:19 [INFO] Dieser Server startet mit der Version Nukkit 1.0dev "蘋果(Apple)派(Pie)" (API: 1.0.0)
14:02:19 [INFO] Nukkit wird unter der LGPL-Lizenz vertrieben
14:02:21 [INFO] Loading recipes...
14:02:21 [INFO] Loaded 415 recipes.
14:02:21 [INFO] Successfully loaded 0 resource packs
14:02:22 [INFO] Vorbereiten der Welt "world"
> java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:101)
	at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
	at io.netty.util.Signal$1.<init>(Signal.java:27)
	at io.netty.util.Signal.<clinit>(Signal.java:27)
	at io.netty.util.concurrent.DefaultPromise.<clinit>(DefaultPromise.java:42)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:51)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
	at cn.nukkit.raknet.server.UDPServerSocket.<init>(UDPServerSocket.java:43)
	at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:99)
14:02:22 [INFO] [BugReport] An error has been detected, creating a bug report.
14:02:22 [INFO] Starte GS4 Status-Listener
14:02:22 [INFO] Setze Query-Port auf 19132
14:02:22 [INFO] Query startet auf 84.200.109.15:19132
14:02:22 [INFO] Standard-Spielmodus: Überlebensmodus
14:02:23 [INFO] Fertig! (12.928s)! Für Hilfe, tippe "help" oder "?"
> 4d465f4
14:02:24 [INFO] [BugReport] A bug report has been created: /home/daniel/Schreibtisch/mcpe/lobby/logs/bug_reports/201711051402551_NoClassDefFoundError.md

**Comment by PetteriM1** [comment]
Can you upload bug report file?

/home/daniel/Schreibtisch/mcpe/lobby/logs/bug_reports/201711051402551_NoClassDefFoundError.md

**Comment by danieltaraba** [comment]
[201711051402551_NoClassDefFoundError.txt](https://github.com/Nukkit/Nukkit/files/1444190/201711051402551_NoClassDefFoundError.txt)

**Comment by PetteriM1** [comment]
## Nukkit Bug Report

(DO NOT OPEN A ISSUE IF THIS IS A PLUGIN ERROR)

PLUGIN ERROR: TRUE   **<-- It is plugin error.**

**Comment by danieltaraba** [comment]
ok thanks

**Comment by PetteriM1** [comment]
and close this issue

**Comment by NuclearSteven** [comment]
This is actually not a plugin error. I need to revise the bug report system.

**Comment by NuclearSteven** [comment]
Plus, something is wrong with netty. Try with Oracle Java 8.
