### ISSUE TITLE
CommandRequestPacket decode error on beta 1.2.6.2

### ISSUE THREAD

**Issue by yescallop** [Nukkit/Nukkit#1937]
### Issue Description

CommandRequestPacket decode error on beta 1.2.6.2

I don't know whether if this error occurs on the stable versions, someone can check it?

### Steps to Reproduce the Issue

1. Use MCPE beta 1.2.6.2 to join the server
2. Send a command with args

### OS and Versions

* Nukkit Version: v1.2.2 

* Java Version: 1.8.0_65

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Android | 
| Client Version | 1.2.6.2 | 

### Crashdump, Backtrace or Other Files

```
[ALERT] java.lang.ArrayIndexOutOfBoundsException: 30
        at cn.nukkit.utils.BinaryStream.getByte(BinaryStream.java:198)
        at cn.nukkit.utils.VarInt.read(VarInt.java:64)
        at cn.nukkit.utils.VarInt.readUnsignedVarLong(VarInt.java:141)
        at cn.nukkit.utils.VarInt.readVarLong(VarInt.java:125)
        at cn.nukkit.utils.BinaryStream.getVarLong(BinaryStream.java:353)
        at cn.nukkit.network.protocol.CommandRequestPacket.decode(CommandRequestPacket.java:38)
        at cn.nukkit.network.Network.processBatch(Network.java:154)
        at cn.nukkit.Player.handleDataPacket(Player.java:1985)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:998)
        at cn.nukkit.Server.tickProcessor(Server.java:801)
        at cn.nukkit.Server.start(Server.java:780)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
```

**Comment by SupremeMortal** [comment]
There is now CommandOrigin data in the CommandRequest like so
https://github.com/SupremeMortal/voxelwind/blob/1.2/server/src/main/java/com/voxelwind/server/network/mcpe/packets/McpeCommandRequest.java
https://github.com/SupremeMortal/voxelwind/blob/1.2/server/src/main/java/com/voxelwind/server/network/mcpe/util/CommandOriginData.java
https://github.com/SupremeMortal/voxelwind/blob/1.2/server/src/main/java/com/voxelwind/server/network/mcpe/McpeUtil.java#L326

**Comment by naturefreshmilk** [comment]
Appears in MCPE 1.2.5 Stable too:
```
 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 32
        at cn.nukkit.utils.BinaryStream.getByte(BinaryStream.java:198)
        at cn.nukkit.utils.VarInt.read(VarInt.java:64)
        at cn.nukkit.utils.VarInt.readUnsignedVarLong(VarInt.java:141)
        at cn.nukkit.utils.VarInt.readVarLong(VarInt.java:125)
        at cn.nukkit.utils.BinaryStream.getVarLong(BinaryStream.java:353)
        at cn.nukkit.network.protocol.CommandRequestPacket.decode(CommandRequestPacket.java:38)
        at cn.nukkit.network.Network.processBatch(Network.java:154)
        at cn.nukkit.Player.handleDataPacket(Player.java:1985)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:998)
        at cn.nukkit.Server.tickProcessor(Server.java:801)
        at cn.nukkit.Server.start(Server.java:780)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)

```

Server-Info:
```
15:06:53 [INFO] Starting Minecraft: PE server version v1.2.2
15:06:53 [INFO] Opening server on 0.0.0.0:19132
15:06:53 [INFO] This server is running Nukkit version 1.0dev "蘋果(Apple)派(Pie)" (API 1.0.0)

```

**Comment by SupremeMortal** [comment]
#1947

**Comment by naturefreshmilk** [comment]
Can confirm: works with #1947
