### ISSUE TITLE
Join error

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#196]
![image](https://cloud.githubusercontent.com/assets/11244874/11919713/36efd988-a76b-11e5-8f0e-8799cf6601a2.png)

**Comment by fromgate** [comment]
I don't know is it same error, but I get this:

```
22:53:44 [ALERT] java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(Unknown Source)
        at java.util.HashMap$ValueIterator.next(Unknown Source)
        at cn.nukkit.Player.processLogin(Player.java:1476)
        at cn.nukkit.Player.authenticateCallback(Player.java:1455)
        at cn.nukkit.Player.tryAuthenticate(Player.java:1444)
        at cn.nukkit.Player.onPlayerPreLogin(Player.java:1440)
        at cn.nukkit.Player.handleDataPacket(Player.java:1799)
        at cn.nukkit.network.Network.processBatch(Network.java:152)
        at cn.nukkit.Player.handleDataPacket(Player.java:1708)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:927)
        at cn.nukkit.Server.tickProcessor(Server.java:749)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

How to reproduce (I'm not sure that it's possible to reproduce, but you can try):
1. Login using Android device. Exit from server.
2. Login using same name, but using other device (I use windows 10 tablet).

**Comment by fromgate** [comment]
@caoli5288 
:+1:
