### ISSUE TITLE
Can't Use Commands In Game

### ISSUE THREAD

**Issue by PotatoeTrainYT** [Nukkit/Nukkit#1967]
### Issue Description

Write a short description about the issue

### Steps to Reproduce the Issue

1. ... Use Any Command In Game
2. ...
3. ...

### OS and Versions

* Nukkit Version: This server is running Nukkit version 1.0dev "蘋果(Apple)派(Pie)" (API 1.0.0) 

* Java Version: 
```
??
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | RamShard Host |  
| Memory(RAM) | 1 GB | 
| Storage Size | 1 GB | 
| Storage Type | HHD | 
| CPU Type | ?? | 
| CPU Core Count | ?? cores ?? threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Android | 
| Client Version | 1.2 | 

### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```
14.12 17:16:38 [Server] INFO GK12:16:38 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 34
14.12 17:16:38 [Server] INFO at cn.nukkit.utils.BinaryStream.getByte(BinaryStream.java:198)
14.12 17:16:38 [Server] INFO at cn.nukkit.utils.VarInt.read(VarInt.java:64)
14.12 17:16:38 [Server] INFO at cn.nukkit.utils.VarInt.readUnsignedVarLong(VarInt.java:141)
14.12 17:16:38 [Server] INFO at cn.nukkit.utils.VarInt.readVarLong(VarInt.java:125)
14.12 17:16:38 [Server] INFO at cn.nukkit.utils.BinaryStream.getVarLong(BinaryStream.java:353)
14.12 17:16:38 [Server] INFO at cn.nukkit.network.protocol.CommandRequestPacket.decode(CommandRequestPacket.java:38)
14.12 17:16:38 [Server] INFO at cn.nukkit.network.Network.processBatch(Network.java:154)
14.12 17:16:38 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:1985)
14.12 17:16:38 [Server] INFO at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
14.12 17:16:38 [Server] INFO at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
14.12 17:16:38 [Server] INFO at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
14.12 17:16:38 [Server] INFO at cn.nukkit.network.Network.processInterfaces(Network.java:76)
14.12 17:16:38 [Server] INFO at cn.nukkit.Server.tick(Server.java:998)
14.12 17:16:38 [Server] INFO at cn.nukkit.Server.tickProcessor(Server.java:801)
14.12 17:16:38 [Server] INFO at cn.nukkit.Server.start(Server.java:780)
14.12 17:16:38 [Server] INFO at cn.nukkit.Server.<init>(Server.java:471)
14.12 17:16:38 [Server] INFO at cn.nukkit.Nukkit.main(Nukkit.java:99)

**Comment by SupremeMortal** [comment]
#1947

**Comment by PotatoeTrainYT** [comment]
what

**Comment by SupremeMortal** [comment]
The 1.2.5 update broke commands and that pull request fixes it.

**Comment by PotatoeTrainYT** [comment]
im on android i, can't create the jar

**Comment by SupremeMortal** [comment]
Here's the fix https://ci.potestas.xyz/job/NukkitX/job/1.2.6/
