### ISSUE TITLE
Player Ticking Error

### ISSUE THREAD

**Issue by Rangganak02** [Nukkit/Nukkit#1972]
1. Player ticking error
2. ...
3. ...

* Nukkit Version: 1.0-SNAPSHOT
* Java Version: java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
??
```
| Item | Value |
|:----:|:-----:|
| Host OS | Ubuntu 14.04 | 
| Memory(RAM) | 1GB | 
| Storage Size | 20 GB | 
| Storage Type | SSD | 
| CPU Type | Intel® Xeon® E5-2650L v4 | 
| CPU Core Count | 1 | 
| Upstream Bandwidth | 100Mbps | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Android | 
| Client Version | 1.2.7.2 | 

### Crashdump, Backtrace or Other Files
10:44:32 [EMERGENCY] Exception happened while ticking server
10:44:32 [ALERT] java.lang.NoSuchMethodError: cn.nukkit.Player.teleportImmediate(Lcn/nukkit/math/Vector3;)V
        at org.to2mbn.basiscommands.command.CommandTp.execute(CommandTp.java:40)
        at org.to2mbn.basiscommands.util.command.CommandHandler.pushCommand(CommandHandler.java:48)
        at org.to2mbn.basiscommands.BasisCommands.onCommand(BasisCommands.java:93)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:645)
        at cn.nukkit.Player.handleDataPacket(Player.java:2546)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:1985)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:998)
        at cn.nukkit.Server.tickProcessor(Server.java:801)
        at cn.nukkit.Server.start(Server.java:780)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)

10:44:32 [ALERT]
"threadDeathWatcher-3-1" Id=24 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)

"Nukkit Asynchronous Task Handler #4" Id=23 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@56637cff
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@56637cff
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ...

"Nukkit Asynchronous Task Handler #3" Id=22 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@56637cff
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@56637cff
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ...

"Nukkit Asynchronous Task Handler #2" Id=21 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@56637cff
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@56637cff
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ...

"Nukkit Asynchronous Task Handler #1" Id=20 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@56637cff
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@56637cff
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ...

"epollEventLoopGroup-2-1" Id=18 RUNNABLE
        at io.netty.channel.epoll.Native.epollWait0(Native Method)
        at io.netty.channel.epoll.Native.epollWait(Native.java:117)
        at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:231)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)

"RakNet Thread #15" Id=15 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
        at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
        at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
        at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)

"RCON" Id=14 RUNNABLE (in native)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$3@2938127d
        -  locked java.util.Collections$UnmodifiableSet@127a7272
        -  locked sun.nio.ch.EPollSelectorImpl@ff23ae7
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
        at cn.nukkit.network.rcon.RCONServer.run(RCONServer.java:84)

"Console" Id=9 RUNNABLE (in native)
        at java.io.FileInputStream.read0(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:207)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
        -  locked jline.internal.NonBlockingInputStream@423b2b62
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
        at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
        -  locked jline.internal.NonBlockingInputStream@423b2b62
        at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
        -  locked jline.internal.NonBlockingInputStream@423b2b62
        at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2143)
        ...

"NonBlockingInputStreamThread" Id=13 WAITING on jline.internal.NonBlockingInputStream@423b2b62 owned by "Console" Id=9
        at java.lang.Object.wait(Native Method)
        -  waiting on jline.internal.NonBlockingInputStream@423b2b62
        at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
        at java.lang.Thread.run(Thread.java:748)

"process reaper" Id=11 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@2b7962a2
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@2b7962a2
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ...

"Thread-0" Id=8 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:233)
        at cn.nukkit.utils.MainLogger.run(MainLogger.java:222)

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@6ad16c5d
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@6ad16c5d
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@74ea46e2
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.Reference$Lock@74ea46e2
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" Id=1 RUNNABLE
        at sun.management.ThreadImpl.dumpThreads0(Native Method)
        at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
        at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:111)
        at cn.nukkit.Server.tickProcessor(Server.java:816)
        at cn.nukkit.Server.start(Server.java:780)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:99

**Comment by SupremeMortal** [comment]
This is a plugin issue. basiscommands

**Comment by Rangganak02** [comment]
ok i will test it to remove the plugin
