### ISSUE TITLE
Comands that I inputed in console can't display

### ISSUE THREAD

**Issue by erickwoc** [Nukkit/Nukkit#1976]
### Issue Description

I tried to input command from the console, and it don't display. Then I pressed ENTER, the comand runs sussefully. 

### Steps to Reproduce the Issue

1. Clone the latest codes
2. Build from codes
3. copy the target to where I wanna run the server `cp target/nukkit-1.0-SNAPSHOT.jar where_I_wanna_run_the_server/`
4. run the server `java -jar where_I_wanna_run_the_server/nukkit-1.0-SNAPSHOT.jar`

### OS and Versions

* Nukkit Version: 此服务器正在运行 Nukkit 1.0dev 「蘋果(Apple)派(Pie)」API 版本 1.0.0 支持 Minecraft：PE v1.2.2 (协议版本 137) 

* Java Version: 
```
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Linux eric-PC 4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19) x86_64 GNU/Linux |  
| Memory(RAM) | 8 GB | 
| Storage Size |  207.6GB | 
| Storage Type | HDD | 
| CPU Type | Intel(R) Core(TM) i7-6700HQ CPU | 
| CPU Core Count | 8 cores 16 threads | 
| Upstream Bandwidth | 100 Mbps | 

* Client Configuration: 
There is no client connected yet.

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | 
| Client Version | ?? | 

### Crashdump, Backtrace or Other Files

```
Using log level 'INFO'
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:223)
	at cn.nukkit.command.CommandReader.<init>(CommandReader.java:37)
	at cn.nukkit.Server.<init>(Server.java:221)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

20:07:44 [INFO] Loading nukkit.yml...
20:07:44 [INFO] Loading server properties...
20:07:44 [INFO] 将 中文(简体) (chs) 设定为基本语言
20:07:44 [INFO] 正在启动支持 Minecraft: PE v1.2.2 版本的服务器
20:07:44 [INFO] 正在启动服务器在 0.0.0.0:19132
20:07:44 [INFO] 此服务器正在运行 Nukkit 1.0dev 版本 "蘋果(Apple)派(Pie)" (API 1.0.0)
20:07:44 [INFO] Nukkit 根据 LGPL 许可发行
20:07:45 [INFO] Loading recipes...
20:07:45 [INFO] Loaded 415 recipes.
20:07:45 [INFO] Successfully loaded 0 resource packs
20:07:45 [INFO] 准备地图中... "world"
20:07:45 [INFO] 启动 GS4 状态监听器
20:07:45 [INFO] 将 Query 端口设定为 19132
20:07:45 [INFO] Query 运行在 0.0.0.0:19132
20:07:45 [INFO] 默认的游戏模式为：生存模式
20:07:45 [INFO] 启动完成 (0.641s)！如需帮助，请输入 "help" 或 "?"

```

**Comment by SupremeMortal** [comment]
Looks like jLine had issues trying to figure out what terminal you're using.

**Comment by erickwoc** [comment]
@SupremeMortal Could you please tell me how to fix this?
