### ISSUE TITLE
Nukkit dosen't runs in Windows

### ISSUE THREAD

**Issue by Fludixx** [Nukkit/Nukkit#1981]
I have a Nukkit server running on Linux and it works perfectly fine, but on Windows it dosen't works. Sorry for my bad Grammer.

Here the Bug Report:

## Nukkit Bug Report

(DO NOT OPEN A ISSUE IF THIS IS A PLUGIN ERROR)

PLUGIN ERROR: FALSE

### Issue Description

??

### Steps to Reproduce the Issue

??

### OS and Versions
* Nukkit Version: 1.0dev 
* Git Commit Abbrev: cd5f4fd
* Java Version: 
```
Java HotSpot(TM) 64-Bit Server VM (9.0.1+11)
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Windows [10] |  
| Memory(RAM) | 12,8 GB | 
| Storage Size | 1,0 TB | 
| Storage Type | WDC WD10JPCX-24UE4T0 (Standardlaufwerke)  | 
| CPU Type | Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz | 
| CPU Core Count | 2 cores 4 threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | 
| Client Version | ?? | 

### Crashdump, Backtrace or Other Files

```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at cn.nukkit.item.Item.initCreativeItems(Item.java:863)
	at cn.nukkit.item.Item.init(Item.java:838)
	at cn.nukkit.Server.<init>(Server.java:376)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

```

**Comment by Fludixx** [comment]
Sorry, i had an Older version of Nukkit
