### ISSUE TITLE
Crafting Not Working

### ISSUE THREAD

**Issue by i14y** [Nukkit/Nukkit#2010]
### Expected Behavior
Got logs, turned into planks, tried to craft Crating Table, expected Crafting Table.

### Actual Behavior
Crafting Table appears in inventory, attempt to select, it vanishes and number of planks returns +4. Server gets alert error on crafting.

### Steps to Reproduce
On XB1, signed in to Live; Get logs, turn into planks, craft Crating Table, try to place.

### Debug information
```
10:32:25 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 1
        at cn.nukkit.inventory.ShapedRecipe.matchInputMap(ShapedRecipe.java:227)
        at cn.nukkit.inventory.ShapedRecipe.matchItems(ShapedRecipe.java:171)
        at cn.nukkit.inventory.CraftingManager.matchRecipe(CraftingManager.java:307)
        at cn.nukkit.inventory.transaction.CraftingTransaction.canExecute(CraftingTransaction.java:141)
        at cn.nukkit.inventory.transaction.InventoryTransaction.execute(InventoryTransaction.java:275)
        at cn.nukkit.inventory.transaction.CraftingTransaction.execute(CraftingTransaction.java:175)
        at cn.nukkit.Player.handleDataPacket(Player.java:2795)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:2022)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1074)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:508)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
```

**Comment by Xelokwonie** [comment]
I'm assuming your using the crafting book to make it then select it from that, you can ignore this error if you manually make the item like you would on the java edition back before the crafting book was added to it, I did notice this and found a simple way to ignore it until it could be fixed, if i knew what I was doing I would attempt to do something more productive to this, but I do hope this helps a little for you.

**Comment by Svahnen** [comment]
This is still a problem and happens on all platforms if using a controller or a touch screen.

**Comment by mshawnee** [comment]
I have this issue as well.  I will try Xelokwonie's solution.

**Comment by mshawnee** [comment]
> I'm assuming your using the crafting book to make it then select it from that, you can ignore this error if you manually make the item like you would on the java edition back before the crafting book was added to it, I did notice this and found a simple way to ignore it until it could be fixed, if i knew what I was doing I would attempt to do something more productive to this, but I do hope this helps a little for you.

Annoying but this works, thanks for the solution.  I have been tearing my hair out trying to figure this out.

**Comment by LarkinZero** [comment]
I have this issues too when i using a xbox controller in my iPad.
Please fix this issue!
