### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by shenkovdev** [Nukkit/Nukkit#2044]
on start i see this:

Using log level 'INFO'
20:49:34 [INFO] Loading nukkit.yml...                                20:49:34 [INFO] Loading server properties...                         20:49:34 [ALERT] java.lang.NullPointerException                      at java.io.Reader.<init>(Reader.java:78)
at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
at cn.nukkit.utils.Utils.readFile(Utils.java:62)
at cn.nukkit.lang.BaseLang.loadLang(BaseLang.java:96)
at cn.nukkit.lang.BaseLang.<init>(BaseLang.java:37)
at cn.nukkit.lang.BaseLang.<init>(BaseLang.java:29)
at cn.nukkit.lang.BaseLang.<init>(BaseLang.java:25)
at cn.nukkit.Server.<init>(Server.java:295)
at cn.nukkit.Nukkit.main(Nukkit.java:99)

How to fix?

**Comment by SupremeMortal** [comment]
Did you build Nukkit yourself?
