### ISSUE TITLE
Nukkit 2.0

### ISSUE THREAD

**Issue by HowToPeaZYT** [Nukkit/Nukkit#2059]
### Actual Behavior

07:37:56 [ERROR] "Test.jar" im Ordner "/home/Nukkit/plugins" konnte nicht geladen werden: java.lang.NullPointerException
        at cn.nukkit.plugin.PluginDescription.loadMap(PluginDescription.java:140)
        at cn.nukkit.plugin.PluginDescription.<init>(PluginDescription.java:136)
        at cn.nukkit.plugin.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:93)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:159)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:126)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:118)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:114)
        at cn.nukkit.Server.boot(Server.java:496)
        at cn.nukkit.Nukkit.main(Nukkit.java:139)

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit

**Comment by IceCruelStuff** [comment]
Use the new repository https://github.com/NukkitX/Nukkit
