### ISSUE TITLE
cant join my new server

### ISSUE THREAD

**Issue by Aditz5041** [Nukkit/Nukkit#2061]
### Expected Behavior

Can you fix nukkit 

### Actual Behavior

i tried to join on my fully updated ios device and updated application i join and there is a endless loop to join the server apexminecraft server hosting said to make a report because they couldnt fix it

### Steps to Reproduce
i dont know

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by ZizzyZizzy** [comment]
You want the support forums. This is for reporting software bugs and crash issues.

https://nukkitx.com/

**Comment by Katana-Steel** [comment]
I get this stack trace when my ios device tries to join


```
20:43:02 [ERROR] Unable to decode packet
java.lang.IllegalArgumentException: Illegal base64 character 5f
        at java.util.Base64$Decoder.decode0(Base64.java:788) ~[?:?]
        at java.util.Base64$Decoder.decode(Base64.java:564) ~[?:?]
        at java.util.Base64$Decoder.decode(Base64.java:587) ~[?:?]
        at cn.nukkit.network.protocol.LoginPacket.decodeToken(LoginPacket.java:147) ~[nukkit-1.0-884.jar:?]
        at cn.nukkit.network.protocol.LoginPacket.decodeChainData(LoginPacket.java:68) ~[nukkit-1.0-884.jar:?]
        at cn.nukkit.network.protocol.LoginPacket.decode(LoginPacket.java:48) ~[nukkit-1.0-884.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:267) [nukkit-1.0-884.jar:?]
        at cn.nukkit.network.RakNetInterface$NukkitRakNetSession.onEncapsulated(RakNetInterface.java:285) [nukkit-1.0-884.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:269) [nukkit-1.0-884.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:392) [nukkit-1.0-884.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:372) [nukkit-1.0-884.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:360) [nukkit-1.0-884.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:241) [nukkit-1.0-884.jar:?]
```
