### ISSUE TITLE
Bugs,bugs...anywhere :)

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#209]
While server works i get crash :)
```
[ALERT] java.lang.NullPointerException
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:195)
        at cn.nukkit.Server.tick(Server.java:929)
        at cn.nukkit.Server.tickProcessor(Server.java:749)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

```
And when write /stop get this.
```
[ERROR] Failed to disable litteral next character
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:396)
        at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
        at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
        at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:185)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2448)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2372)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2360)
        at cn.nukkit.command.CommandReader.readLine(CommandReader.java:44)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:58)
```

**Comment by MagicDroidX** [comment]
I cannot reproduce this.

**Comment by xpyctum** [comment]
@MagicDroidX because i use plugins..
