### ISSUE TITLE
Changed skin, causes server overload on join.

### ISSUE THREAD

**Issue by ProjectInfinity** [Nukkit/Nukkit#238]
See the screenshot for an explanation. This is running build 68 from mengcraft jenkins.

![http://puu.sh/m9vNi/603e26dfec.png](http://puu.sh/m9vNi/603e26dfec.png)

Prior to attempting to join the server it will hover around normal usage, it also worked fine prior to changing my skin.

Eventually with a unresponsive console it finally uttered:
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.util.ArrayList.grow(Unknown Source)
        at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
        at java.util.ArrayList.ensureCapacityInternal(Unknown Source)
        at java.util.ArrayList.add(Unknown Source)
        at cn.nukkit.nbt.tag.ListTag.load(ListTag.java:46)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
        at cn.nukkit.nbt.tag.CompoundTag.load(CompoundTag.java:35)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
        at cn.nukkit.nbt.NBTIO.read(NBTIO.java:73)
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:95)
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:90)
        at cn.nukkit.Server.getOfflinePlayerData(Server.java:1298)
        at cn.nukkit.Player.processLogin(Player.java:1491)
        at cn.nukkit.Player.authenticateCallback(Player.java:1456)
        at cn.nukkit.Player.tryAuthenticate(Player.java:1445)
        at cn.nukkit.Player.onPlayerPreLogin(Player.java:1441)
        at cn.nukkit.Player.handleDataPacket(Player.java:1800)
        at cn.nukkit.network.Network.processBatch(Network.java:152)
        at cn.nukkit.Player.handleDataPacket(Player.java:1709)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:927)
        at cn.nukkit.Server.tickProcessor(Server.java:749)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by ProjectInfinity** [comment]
Okay. So it is related to the data file for the player for sure. I had a backup of the old player data and restored that even with the new skin enabled and it worked. 

Here's the file that makes it all crash: https://gist.github.com/ProjectInfinity/ac753735a6023afbdd3e

**Comment by Pub4Game** [comment]
Dublicate #189

**Comment by ProjectInfinity** [comment]
@Pub4Game Could be. Seems your ticket has gone inactive though.

**Comment by Pub4Game** [comment]
Yes, you gave more precise information, thanks!
