### ISSUE TITLE
save chunk bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#261]
10:29:53 [ERROR] Error while unloading a chunk: java.lang.IndexOutOfBoundsExcept
ion: Index: 27, Size: 0
10:29:53 [ALERT] java.lang.RuntimeException: java.lang.IndexOutOfBoundsException
: Index: 27, Size: 0
        at cn.nukkit.level.format.mcregion.McRegion.saveChunk(McRegion.java:282)

        at cn.nukkit.level.Level.unloadChunk(Level.java:2215)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2179)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2448)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2425)
        at cn.nukkit.level.Level.doTick(Level.java:561)
        at cn.nukkit.Server.checkTickUpdates(Server.java:869)
        at cn.nukkit.Server.tick(Server.java:931)
        at cn.nukkit.Server.tickProcessor(Server.java:749)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.IndexOutOfBoundsException: Index: 27, Size: 0
        at java.util.ArrayList.rangeCheckForAdd(Unknown Source)
        at java.util.ArrayList.add(Unknown Source)
        at cn.nukkit.nbt.tag.ListTag.add(ListTag.java:78)
        at cn.nukkit.tile.Chest.setItem(Chest.java:103)
        at cn.nukkit.tile.Chest.saveNBT(Chest.java:55)
        at cn.nukkit.level.format.mcregion.Chunk.toBinary(Chunk.java:446)
        at cn.nukkit.level.format.mcregion.RegionLoader.writeChunk(RegionLoader.
java:156)
        at cn.nukkit.level.format.mcregion.McRegion.saveChunk(McRegion.java:280)

        ... 11 more

**Comment by MagicDroidX** [comment]
How to reproduce

**Comment by Creeperface01** [comment]
I have map with some tiles  and when i unload chunk with this tile this happens (it doesn't happen in pocketmine)

**Comment by Creeperface01** [comment]
It is map from PC

**Comment by MagicDroidX** [comment]
Would you please upload the map so that we can try to fix it and test if the fix is effective?
