### ISSUE TITLE
teleport bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#262]
10:29:23 [CRITICAL] Unhandled exception executing command 'start' in start: java
.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(Unknown Source)
        at java.util.HashMap$KeyIterator.next(Unknown Source)
        at cn.nukkit.Player.switchLevel(Player.java:458)
        at cn.nukkit.entity.Entity.setPosition(Entity.java:1340)
        at cn.nukkit.entity.Entity.setPositionAndRotation(Entity.java:1290)
        at cn.nukkit.entity.Entity.teleportYawAndPitch(Entity.java:1434)
        at cn.nukkit.Player.teleportYawAndPitch(Player.java:3492)
        at cn.nukkit.entity.Entity.teleport(Entity.java:1396)
        at cn.nukkit.Player.teleport(Player.java:3432)
        at Annihilation.Arena.Arena.teleportToArena(Arena.java:699)
        at Annihilation.Arena.Arena.startGame(Arena.java:791)
        at Annihilation.Annihilation.onCommand(Annihilation.java:212)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148
)
        at cn.nukkit.Server.dispatchCommand(Server.java:602)
        at cn.nukkit.Player.handleDataPacket(Player.java:2606)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.
java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java
:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:927)
        at cn.nukkit.Server.tickProcessor(Server.java:749)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

10:29:23 [ALERT] java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(Unknown Source)
        at java.util.HashMap$KeyIterator.next(Unknown Source)
        at cn.nukkit.Player.switchLevel(Player.java:458)
        at cn.nukkit.entity.Entity.setPosition(Entity.java:1340)
        at cn.nukkit.entity.Entity.setPositionAndRotation(Entity.java:1290)
        at cn.nukkit.entity.Entity.teleportYawAndPitch(Entity.java:1434)
        at cn.nukkit.Player.teleportYawAndPitch(Player.java:3492)
        at cn.nukkit.entity.Entity.teleport(Entity.java:1396)
        at cn.nukkit.Player.teleport(Player.java:3432)
        at Annihilation.Arena.Arena.teleportToArena(Arena.java:699)
        at Annihilation.Arena.Arena.startGame(Arena.java:791)
        at Annihilation.Annihilation.onCommand(Annihilation.java:212)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148
)
        at cn.nukkit.Server.dispatchCommand(Server.java:602)
        at cn.nukkit.Player.handleDataPacket(Player.java:2606)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.
java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java
:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:927)
        at cn.nukkit.Server.tickProcessor(Server.java:749)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by ProjectInfinity** [comment]
Might want to provide code demonstrating the issue. I've been using teleport without this issue.

**Comment by Creeperface01** [comment]
But i teleport player to another level
