### ISSUE TITLE
Raknet Error

### ISSUE THREAD

**Issue by Flirble** [Nukkit/Nukkit#263]
Just updated my server and players can no longer connect, first connection generates errors, subsequent attempts to connect are then ignored.

> 
        at cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:234)
        at cn.nukkit.Player.dataPacket(Player.java:795)
        at cn.nukkit.Player.dataPacket(Player.java:781)
        at cn.nukkit.Server.broadcastPacketsCallback(Server.java:571)
        at cn.nukkit.Server.batchPackets(Server.java:556)
        at cn.nukkit.Server.broadcastPacket(Server.java:507)
        at cn.nukkit.Server.updatePlayerListData(Server.java:798)
        at cn.nukkit.Server.updatePlayerListData(Server.java:802)
        at cn.nukkit.Server.updatePlayerListData(Server.java:791)
        at cn.nukkit.Server.addOnlinePlayer(Server.java:775)
        at cn.nukkit.Player.processLogin(Player.java:1635)
        at cn.nukkit.Player.authenticateCallback(Player.java:1478)
        at cn.nukkit.Player.tryAuthenticate(Player.java:1467)
        at cn.nukkit.Player.onPlayerPreLogin(Player.java:1463)
        at cn.nukkit.Player.handleDataPacket(Player.java:1826)
        at cn.nukkit.network.Network.processBatch(Network.java:152)
        at cn.nukkit.Player.handleDataPacket(Player.java:1735)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:927)
        at cn.nukkit.Server.tickProcessor(Server.java:749)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by MagicDroidX** [comment]
What's the name of the exception

**Comment by Flirble** [comment]
The pasted info is everything the console showed

**Comment by Flirble** [comment]
Thanks, the codechange (whatever you did) 3 hours ago has resolved this issue :)
