### ISSUE TITLE
If kick player when he loading (PlayerLoginEvent)

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#264]
```
[ALERT] java.lang.NullPointerException
        at cn.nukkit.Player.processLogin(Player.java:1648)
        at cn.nukkit.Player.authenticateCallback(Player.java:1478)
        at cn.nukkit.Player.tryAuthenticate(Player.java:1467)
        at cn.nukkit.Player.onPlayerPreLogin(Player.java:1463)
        at cn.nukkit.Player.handleDataPacket(Player.java:1826)
        at cn.nukkit.network.Network.processBatch(Network.java:152)
        at cn.nukkit.Player.handleDataPacket(Player.java:1735)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:927)
        at cn.nukkit.Server.tickProcessor(Server.java:749)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

**Comment by MagicDroidX** [comment]
Use event.setCancelled() instead.
