### ISSUE TITLE
Could not tick level

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#266]
10:40:06 [CRITICAL] Could not tick level "Canyon": java.lang.NullPointerExceptio
n

this happens sometimes but idk why i have debug enabled but how to find out the line?

**Comment by Creeperface01** [comment]
11:28:43 [CRITICAL] Could not tick level "Canyon": java.lang.NullPointerExceptio
n
11:28:43 [ALERT] java.lang.NullPointerException
        at cn.nukkit.lang.BaseLang.parseTranslation(BaseLang.java:183)
        at cn.nukkit.lang.BaseLang.parseTranslation(BaseLang.java:175)
        at cn.nukkit.lang.BaseLang.translateString(BaseLang.java:138)
        at cn.nukkit.lang.BaseLang.translateString(BaseLang.java:127)
        at cn.nukkit.lang.BaseLang.translateString(BaseLang.java:123)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2226)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2180)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2449)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2426)
        at cn.nukkit.level.Level.doTick(Level.java:561)
        at cn.nukkit.Server.checkTickUpdates(Server.java:871)
        at cn.nukkit.Server.tick(Server.java:934)
        at cn.nukkit.Server.tickProcessor(Server.java:750)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Creeperface01** [comment]
and error is this:

11:47:03 [ALERT] java.lang.NullPointerException
        at cn.nukkit.inventory.DoubleChestInventory.setContents(DoubleChestInven
tory.java:87)
        at cn.nukkit.inventory.BaseInventory.<init>(BaseInventory.java:67)
        at cn.nukkit.inventory.BaseInventory.<init>(BaseInventory.java:45)
        at cn.nukkit.inventory.BaseInventory.<init>(BaseInventory.java:41)
        at cn.nukkit.inventory.BaseInventory.<init>(BaseInventory.java:37)
        at cn.nukkit.inventory.DoubleChestInventory.<init>(DoubleChestInventory.
java:21)
        at cn.nukkit.tile.Chest.checkPairing(Chest.java:132)
        at cn.nukkit.tile.Chest.getInventory(Chest.java:112)
        at cn.nukkit.tile.Chest.close(Chest.java:40)
        at cn.nukkit.level.format.generic.BaseFullChunk.unload(BaseFullChunk.jav
a:401)
        at cn.nukkit.level.format.mcregion.McRegion.unloadChunk(McRegion.java:26
9)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2223)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2180)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2450)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2427)
        at cn.nukkit.level.Level.doTick(Level.java:561)
        at cn.nukkit.Server.checkTickUpdates(Server.java:871)
        at cn.nukkit.Server.tick(Server.java:934)
        at cn.nukkit.Server.tickProcessor(Server.java:750)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

> java.lang.NullPointerException
        at cn.nukkit.inventory.DoubleChestInventory.setContents(DoubleChestInven
tory.java:87)
        at cn.nukkit.inventory.BaseInventory.<init>(BaseInventory.java:67)
        at cn.nukkit.inventory.BaseInventory.<init>(BaseInventory.java:45)
        at cn.nukkit.inventory.BaseInventory.<init>(BaseInventory.java:41)
        at cn.nukkit.inventory.BaseInventory.<init>(BaseInventory.java:37)
        at cn.nukkit.inventory.DoubleChestInventory.<init>(DoubleChestInventory.
java:21)
        at cn.nukkit.tile.Chest.checkPairing(Chest.java:132)
        at cn.nukkit.tile.Chest.getInventory(Chest.java:112)
        at cn.nukkit.tile.Chest.close(Chest.java:40)
        at cn.nukkit.level.format.generic.BaseFullChunk.unload(BaseFullChunk.jav
a:401)
        at cn.nukkit.level.format.mcregion.McRegion.unloadChunk(McRegion.java:26
9)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2223)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2180)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2450)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2427)
        at cn.nukkit.level.Level.doTick(Level.java:561)
        at cn.nukkit.Server.checkTickUpdates(Server.java:871)
        at cn.nukkit.Server.tick(Server.java:934)
        at cn.nukkit.Server.tickProcessor(Server.java:750)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by caoli5288** [comment]
@MagicDroidX

**Comment by Creeperface01** [comment]
i don't know how to fix this issue because super() constructor must be called after defining left and right chest but parent constructor must be defined first -,-

**Comment by Pub4Game** [comment]
@MagicDroidX @Snake1999 @Angelic47 I attract you attention! Please fix this bug!

**Comment by Creeperface01** [comment]
It is because of bad constructor
