### ISSUE TITLE
Error with the world

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#282]
```
[CRITICAL] Ошибка прорисовки мира "world": java.lang.NullPointerException
    [ALERT] java.lang.NullPointerException
	at cn.nukkit.math.Vector3.equals(Vector3.java:240)
	at cn.nukkit.math.AxisAlignedBB.calculateIntercept(AxisAlignedBB.java:279)
	at cn.nukkit.entity.Projectile.onUpdate(Projectile.java:107)
	at cn.nukkit.entity.Snowball.onUpdate(Snowball.java:59)
	at cn.nukkit.level.Level.doTick(Level.java:571)
	at cn.nukkit.Server.checkTickUpdates(Server.java:871)
	at cn.nukkit.Server.tick(Server.java:933)
	at cn.nukkit.Server.tickProcessor(Server.java:750)
	at cn.nukkit.Server.start(Server.java:730)
	at cn.nukkit.Server.<init>(Server.java:427)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
```
I don't know how to reproduce it...

**Comment by Angelic47** [comment]
How to reproduce this? I tried to throw a snowball but can't cause this problem...

**Comment by Pub4Game** [comment]
@Angelic47 I threw many snowballs and happens this error...

**Comment by Angelic47** [comment]
@Pub4Game OK, i will try...
