### ISSUE TITLE
LDB Error with loaded map.

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#301]
```
13:06:45 [ERROR] Error while unloading a chunk: java.lang.IndexOutOfBoundsException: Index: 27, Size: 0
13:06:45 [ALERT] java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 27, Size: 0
        at cn.nukkit.level.format.leveldb.Chunk.toBinary(Chunk.java:497)
        at cn.nukkit.level.format.leveldb.LevelDB.writeChunk(LevelDB.java:294)
        at cn.nukkit.level.format.leveldb.LevelDB.saveChunk(LevelDB.java:320)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2216)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2180)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2449)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2426)
        at cn.nukkit.level.Level.doTick(Level.java:561)
        at cn.nukkit.Server.checkTickUpdates(Server.java:871)
        at cn.nukkit.Server.tick(Server.java:933)
        at cn.nukkit.Server.tickProcessor(Server.java:750)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.IndexOutOfBoundsException: Index: 27, Size: 0
        at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:646)
        at java.util.ArrayList.add(ArrayList.java:458)
        at cn.nukkit.nbt.tag.ListTag.add(ListTag.java:78)
        at cn.nukkit.tile.Chest.setItem(Chest.java:103)
        at cn.nukkit.tile.Chest.saveNBT(Chest.java:55)
        at cn.nukkit.level.format.leveldb.Chunk.toBinary(Chunk.java:443)
        ... 13 more
```
After install leveldb map on server

**Comment by MagicDroidX** [comment]
It is due to the chest issue which has already been reported ;D.

**Comment by xpyctum** [comment]
@MagicDroidX Ok :D

**Comment by xpyctum** [comment]
Why?

**Comment by MagicDroidX** [comment]
This is duplicate with #261

**Comment by MagicDroidX** [comment]
Don't worry, I am currently working on this issue. :)

**Comment by xpyctum** [comment]
Ok :) :+1:

**Comment by MagicDroidX** [comment]
This has already been fixed. :)
