### ISSUE TITLE
Sign and Anvil

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#312]
If you press the sing on the anvil, then the crash happens
```
Packet cn.nukkit.network.protocol.BlockEntityDataPacket 0xBD000000B9000000630000007B0A0000080500546578743104006469646F080500546578743200000805005465787433000008050054657874340000080200696404005369676E03010078B900000003010079630000000301007A7B00000000
2016-1-9 20:07:37 [ALERT] java.lang.RuntimeException: java.io.EOFException
	at cn.nukkit.Player.handleDataPacket(Player.java:2943)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
	at cn.nukkit.network.Network.processInterfaces(Network.java:73)
	at cn.nukkit.Server.tick(Server.java:929)
	at cn.nukkit.Server.tickProcessor(Server.java:750)
	at cn.nukkit.Server.start(Server.java:730)
	at cn.nukkit.Server.<init>(Server.java:427)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at cn.nukkit.nbt.stream.NBTInputStream.readByte(NBTInputStream.java:53)
	at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:81)
	at cn.nukkit.nbt.tag.CompoundTag.load(CompoundTag.java:35)
	at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
	at cn.nukkit.nbt.NBTIO.read(NBTIO.java:73)
	at cn.nukkit.nbt.NBTIO.read(NBTIO.java:88)
	at cn.nukkit.Player.handleDataPacket(Player.java:2941)
	... 9 more

Blocked 217.15.28.33 for 5 seconds
```

**Comment by MagicDroidX** [comment]
I've fixed the BinaryStream and this cannot be reproduced as i expected.
