### ISSUE TITLE
NPE on removing aliases for existing commands.

### ISSUE THREAD

**Issue by ProjectInfinity** [Nukkit/Nukkit#315]
Trying to register a command that has the alias "tp" now fails thanks to this commit:
https://github.com/Nukkit/Nukkit/commit/9bd91fd454b441a2ea25519a643d6afabb2d4e5a

 Here's the error:
``` 
22:18:38 [INFO] Enabling LeetTP v1.0.1-bDEV
22:18:38 [ALERT] java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at cn.nukkit.command.SimpleCommandMap.register(SimpleCommandMap.java:94)
        at cn.nukkit.command.SimpleCommandMap.register(SimpleCommandMap.java:80)
        at cc.leet.leettp.LeetTP.onEnable(LeetTP.java:73)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:431)
        at cn.nukkit.Server.enablePlugin(Server.java:590)
        at cn.nukkit.Server.enablePlugins(Server.java:579)
        at cn.nukkit.Server.<init>(Server.java:423)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

22:18:38 [INFO] Disabling LeetTP v1.0.1-bDEV
``` 

Issue is related to the fact that the arraylist is being iterated and modified at the same time.

**Comment by ProjectInfinity** [comment]
Fixed. :)
