### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#325]
```
at java.util.Arrays.copyOf(Arrays.java:3175)
        at java.util.ArrayList.grow(ArrayList.java:246)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:220)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:212)
        at java.util.ArrayList.add(ArrayList.java:443)
        at cn.nukkit.nbt.tag.ListTag.load(ListTag.java:46)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
        at cn.nukkit.nbt.tag.CompoundTag.load(CompoundTag.java:35)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
        at cn.nukkit.nbt.NBTIO.read(NBTIO.java:73)
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:97)
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:92)
        at cn.nukkit.Server.getOfflinePlayerData(Server.java:1300)
        at cn.nukkit.Player.processLogin(Player.java:1523)
        at cn.nukkit.Player.authenticateCallback(Player.java:1488)
        at cn.nukkit.Player.tryAuthenticate(Player.java:1477)
        at cn.nukkit.Player.onPlayerPreLogin(Player.java:1473)
        at cn.nukkit.Player.handleDataPacket(Player.java:1838)
        at cn.nukkit.network.Network.processBatch(Network.java:152)
        at cn.nukkit.Player.handleDataPacket(Player.java:1747)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:929)
        at cn.nukkit.Server.tickProcessor(Server.java:750)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
```
After 1-5 players join. And crash with 'Increase heap size in java'

**Comment by imjack** [comment]
Looks to be the same as #319

**Comment by Angelic47** [comment]
Did you use the latest build nukkit?

**Comment by xpyctum** [comment]
@Angelic47 Yes.

**Comment by Angelic47** [comment]
Still buggy with NBTIO. Could you please upload this player's data here? Thanks!

**Comment by xpyctum** [comment]
I don't know who player profile causes a bug... i can upload a full player folder :D

**Comment by Angelic47** [comment]
Thanks a lot!

**Comment by xpyctum** [comment]
Fixed? Or still going on?

**Comment by MagicDroidX** [comment]
It should be fixed now! I'll close this and you can reopen it whenever it happens. :P
