### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by devidkohyt** [Nukkit/Nukkit#335]
at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:261)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
        at java.util.ArrayList.add(ArrayList.java:458)
        at cn.nukkit.nbt.tag.ListTag.load(ListTag.java:46)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
        at cn.nukkit.nbt.tag.CompoundTag.load(CompoundTag.java:35)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
        at cn.nukkit.nbt.NBTIO.read(NBTIO.java:73)
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:97)        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:92)        at cn.nukkit.Server.getOfflinePlayerData(Server.java:1300)
        at cn.nukkit.Player.processLogin(Player.java:1523)
        at cn.nukkit.Player.authenticateCallback(Player.java:1488)
        at cn.nukkit.Player.tryAuthenticate(Player.java:1477)
        at cn.nukkit.Player.onPlayerPreLogin(Player.java:1473)
        at cn.nukkit.Player.handleDataPacket(Player.java:1838)
        at cn.nukkit.network.Network.processBatch(Network.java:152)
        at cn.nukkit.Player.handleDataPacket(Player.java:1747)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:929)
        at cn.nukkit.Server.tickProcessor(Server.java:750)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by caoli5288** [comment]
FULL stack trace please.

**Comment by devidkohyt** [comment]
root@freby-w:~# java -jar nukkit-1.0-SNAPSHOT.jar
15:24:07 [INFO] Loading nukkit.yml...
15:24:08 [INFO] Loading server properties...
15:24:08 [INFO] Выбран Pyccĸий (rus) как основной язык
15:24:08 [INFO] Запускается сервер Minecraft: PE версии v0.13.1 alpha
15:24:08 [INFO] Открытие сервера на 0.0.0.0:19132
15:24:08 [INFO] Этот сервер использует Nukkit, версию 1.0dev "蘋果(Apple)派(Pie)" (API 1.0.0)
15:24:08 [INFO] Nukkit распространяется под лицензией LGPL
15:24:09 [INFO] Загрузка SimpleFly v1.0.0
15:24:09 [INFO] Загрузка Economy-LEET v1.0.1-b2
15:24:09 [INFO] Загрузка DbLib v0.0.4
15:24:09 [INFO] Загрузка ToolsPro v0.0.1
15:24:09 [INFO] Загрузка FakeName v1.0
15:24:09 [INFO] Загрузка Vanish v1.0
15:24:09 [INFO] Загрузка WorldEdit v0.0.1
15:24:09 [INFO] Загрузка MyRegion v1.0
15:24:09 [INFO] Загрузка Smiley v0.0.2
15:24:09 [INFO] Загрузка MadPerms v1.1.0
15:24:09 [INFO] Загрузка BasisCommands v0.0.4.33
15:24:09 [INFO] Загрузка Welcome v0.0.4
15:24:10 [INFO] Подготовка мира "world"
15:24:10 [INFO] Включение SimpleFly v1.0.0
15:24:10 [INFO] [SimpleFly] SimpleFly успешно загружен!
15:24:10 [INFO] Включение Economy-LEET v1.0.1-b2
15:24:10 [INFO] Включение DbLib v0.0.4
15:24:10 [INFO] [DbLib] DbLib 0.0.4 created by fromgate for nukkit.ru
15:24:10 [INFO] [DbLib] Connecting to: jdbc:sqlite:/root/nukkit.db (user: nukkit)
> 2016-01-12 15:24:10,277 [ERROR] SqliteDatabaseType WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
15:24:10 [INFO] Включение ToolsPro v0.0.1
15:24:10 [INFO] [ToolsPro] ToolsPro успешно загружен!
15:24:10 [INFO] Включение FakeName v1.0
15:24:10 [INFO] [FakeName] Плагин FakeName от Doomhawk включен!
15:24:10 [INFO] Включение Vanish v1.0
15:24:10 [INFO] [Vanish] Плагин Vanish от Doomhawk включен!
15:24:10 [INFO] [Vanish] Plugin Vanish by Doomhawk has been enabled!15:24:10 [INFO] Включение WorldEdit v0.0.1
15:24:10 [INFO] [WorldEdit] Selected language: English (ENG). You can change it in the config!
15:24:10 [INFO] [WorldEdit] Выбранный язык: Английский (ENG). Вы можете сменить его в конфиге!
15:24:10 [INFO] Включение MyRegion v1.0
15:24:10 [INFO] [MyRegion] Selected language: English (ENG). You can change it in the config!
15:24:10 [INFO] [MyRegion] Выбранный язык: Английский (ENG). Вы можете сменить его в конфиге!
15:24:10 [INFO] Включение Smiley v0.0.2
15:24:10 [INFO] Включение MadPerms v1.1.0
15:24:10 [INFO] [MadPerms] MadPerms is loading....
15:24:10 [INFO] Включение BasisCommands v0.0.4.33
15:24:10 [INFO] [BasisCommands] Initializing plugin listener
15:24:10 [INFO] [BasisCommands] Loading configurations' handler
15:24:10 [INFO] [BasisCommands] Loading I18N
15:24:10 [INFO] [BasisCommands] Loading I18N file for locale 'en-US'15:24:10 [INFO] [BasisCommands] American English I18N file loaded
15:24:10 [INFO] [BasisCommands] Loading auto notices
15:24:10 [INFO] [BasisCommands] Loading players' home positions
15:24:10 [INFO] [BasisCommands] Loading teleport requests' handler
15:24:10 [INFO] [BasisCommands] Loading commands
15:24:10 [INFO] Включение Welcome v0.0.4
15:24:10 [INFO] [Welcome] [MESSAGES] Messages: 41 Language: english Save translate file: 41 Debug mode: true
15:24:10 [INFO] [Welcome] Password validator regex prepared: (?=.*[a-z])(?=.*[0-9])(?=\S+$).{6,16}
15:24:11 [INFO] [Welcome] Password provider: DATABASE Hash algorithm: SHA256
15:24:11 [INFO] [Welcome] Command registered: login (aliases: lgn, l) permission: welcome.login
15:24:11 [INFO] [Welcome] Command registered: register (alias: reg) permission: welcome.register
15:24:11 [INFO] [Welcome] Command registered: unregister (alias: unreg) permission: welcome.unregister
15:24:11 [INFO] [Welcome] Command registered: changepassword (aliases: changepwd, changepass, cpw) permission: welcome.changepassword
15:24:11 [INFO] [Welcome] Command registered: welcome (alias: wel) (sub command: remove) permission: welcome.remove
15:24:11 [INFO] Запуск прослушивателя статуса GS4
15:24:11 [INFO] Установлен порт query на 19132
15:24:11 [INFO] Query запущен на 0.0.0.0:19132
15:24:11 [INFO] Игровой режим по умолчанию: Выживание
15:24:11 [INFO] Загружено (3.764 секунд)! Для справки введите "help" или "?"
>
        at cn.nukkit.nbt.tag.Tag.newTag(Tag.java:127)                       at cn.nukkit.nbt.tag.ListTag.load(ListTag.java:44)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)                  at cn.nukkit.nbt.tag.CompoundTag.load(CompoundTag.java:35)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)                  at cn.nukkit.nbt.NBTIO.read(NBTIO.java:73)
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:97)                at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:92)
        at cn.nukkit.Server.getOfflinePlayerData(Server.java:1300)
        at cn.nukkit.Player.processLogin(Player.java:1523)
        at cn.nukkit.Player.authenticateCallback(Player.java:1488)
        at cn.nukkit.Player.tryAuthenticate(Player.java:1477)
        at cn.nukkit.Player.onPlayerPreLogin(Player.java:1473)
        at cn.nukkit.Player.handleDataPacket(Player.java:1838)
        at cn.nukkit.network.Network.processBatch(Network.java:152)
        at cn.nukkit.Player.handleDataPacket(Player.java:1747)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:929)
        at cn.nukkit.Server.tickProcessor(Server.java:750)
        at cn.nukkit.Server.start(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:427)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
 4% | U 0.0 D 0.0 kB/s | TPS 20.0 | Load 31.73%stop
15:25:51 [INFO] [CONSOLE: Выключение сервера]
>
Took too long to stop, server was killed forcefully!

15:27:21 [EMERGENCY] RakNet crashed!
root@freby-w:~#

**Comment by MagicDroidX** [comment]
duplicate with #325
