### ISSUE TITLE
Save-All Error

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#340]
```
[CRITICAL] Необработанное исключение при выполнении команды 'save-all' в save-all: java.lang.NullPointerException
	at cn.nukkit.entity.Entity.saveNBT(Entity.java:515)
	at cn.nukkit.entity.Living.saveNBT(Living.java:73)
	at cn.nukkit.entity.Human.saveNBT(Human.java:147)
	at cn.nukkit.Player.save(Player.java:3220)
	at cn.nukkit.Player.save(Player.java:3212)
	at cn.nukkit.command.defaults.SaveCommand.execute(SaveCommand.java:29)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150)
	at cn.nukkit.Server.dispatchCommand(Server.java:603)
	at cn.nukkit.command.CommandReader.run(CommandReader.java:66)

[ALERT] java.lang.NullPointerException
	at cn.nukkit.entity.Entity.saveNBT(Entity.java:515)
	at cn.nukkit.entity.Living.saveNBT(Living.java:73)
	at cn.nukkit.entity.Human.saveNBT(Human.java:147)
	at cn.nukkit.Player.save(Player.java:3220)
	at cn.nukkit.Player.save(Player.java:3212)
	at cn.nukkit.command.defaults.SaveCommand.execute(SaveCommand.java:29)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150)
	at cn.nukkit.Server.dispatchCommand(Server.java:603)
	at cn.nukkit.command.CommandReader.run(CommandReader.java:66)
```

**Comment by xpyctum** [comment]
Использовал плагины, чтобы заспаунить энтити? 
У меня нету просто такой ошибки.

**Comment by Pub4Game** [comment]
Нет

**Comment by xpyctum** [comment]
Тогда без понятия почему :<

**Comment by caoli5288** [comment]
I can not observed this issue.

**Comment by MagicDroidX** [comment]
Remember to paste the codes as the line number may change very often.
