### ISSUE TITLE
Crash on /stop

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#360]
```
> java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
        at cn.nukkit.raknet.server.SessionManager.receiveStream(SessionManager.java:358)
        at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:79)
        at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:68)
        at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:56)
        at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:100)

```

**Comment by MagicDroidX** [comment]
Remember to paste the code with the trace, for example:
at cn.nukkit.raknet.server.SessionManager.receiveStream(SessionManager.java:**358**)
Then paste codes like this:
```
357: case RakNet.PACKET_SHUTDOWN:
358:       for (Session session : this.sessions.values()) {
                    this.removeSession(session);
           }
```

**Comment by xpyctum** [comment]
@MagicDroidX Using latest build.

**Comment by MagicDroidX** [comment]
@xpyctum This is a notice, because it may change very often. :)

**Comment by xpyctum** [comment]
@MagicDroidX Ok, will know :)
