### ISSUE TITLE
Trying in Async WE (in main thread is ok)

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#362]
```
> Exception in thread "Nukkit Asynchronous Task Handler #3" java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
        at cn.nukkit.level.Level.getNearbyEntities(Level.java:1743)
        at cn.nukkit.level.Level.getNearbyEntities(Level.java:1729)
        at cn.nukkit.level.Level.setBlock(Level.java:1264)
        at NP_Core.WEClass.setBlocks(WEClass.java:46)
        at NP_Core.NP_Core$2.run(NP_Core.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
And this get if use change to a sand block (//set 12)

**Comment by fromgate** [comment]
Which plugin you using for "//set 12"?

**Comment by xpyctum** [comment]
My plugin

**Comment by ProjectInfinity** [comment]
You should probably post your source code, altering blocks shouldn't be as far as I know thread safe. So if that is the case, then I'd say there's no issue here.

**Comment by fromgate** [comment]
@xpyctum  show your code at forum, I can try to help you. If you still need it.

**Comment by ProjectInfinity** [comment]
Having looked more into it, if you are altering blocks from async, then this is supposed to happen. You're not doing async right.

**Comment by xpyctum** [comment]
@ProjectInfinity Hm..

**Comment by ProjectInfinity** [comment]
@xpyctum To get a "async effect", do your calculations async, then create a sorts of queue that you go through and leave some room to breathe before continuing the queue. This way most of the work is done async and only the block editing is going to be sync. It'll seem much faster than doing all the work sync in one go.

**Comment by xpyctum** [comment]
@ProjectInfinity can you tell about in code examples?

**Comment by MagicDroidX** [comment]
The operations with blocks is not thread safe.
