### ISSUE TITLE
Hm, LevelDB...

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#364]
```
at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
        at cn.nukkit.nbt.stream.NBTInputStream.readUnsignedShort(NBTInputStream.java:72)
        at cn.nukkit.nbt.tag.ShortTag.load(ShortTag.java:37)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
        at cn.nukkit.nbt.tag.CompoundTag.load(CompoundTag.java:35)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:88)
        at cn.nukkit.level.format.leveldb.Chunk.fromBinary(Chunk.java:332)
        at cn.nukkit.level.format.leveldb.LevelDB.readChunk(LevelDB.java:283)
        at cn.nukkit.level.format.leveldb.LevelDB.loadChunk(LevelDB.java:259)
        at cn.nukkit.level.format.leveldb.LevelDB.getChunk(LevelDB.java:334)
        at cn.nukkit.level.format.leveldb.LevelDB.getChunk(LevelDB.java:31)
        at cn.nukkit.level.Level.loadChunk(Level.java:2160)
        at cn.nukkit.level.Level.getChunk(Level.java:1896)
        at cn.nukkit.level.Level.setChunk(Level.java:1949)
        at cn.nukkit.level.Level.generateChunkCallback(Level.java:1927)
        at cn.nukkit.level.generator.task.PopulationTask.onCompletion(PopulationTask.java:160)
        at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:79)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:198)
        at cn.nukkit.Server.tick(Server.java:932)
        at cn.nukkit.Server.tickProcessor(Server.java:751)
        at cn.nukkit.Server.start(Server.java:731)
        at cn.nukkit.Server.<init>(Server.java:428)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
```
Latest build.

**Comment by MagicDroidX** [comment]
Hmm... I cannot find the code which causes issues now, would you do me a favor by pasting the code in that build for me please?
