### ISSUE TITLE
Generate world error

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#376]
```
21:35:57 [INFO] ******** вошел с id сущности 1 на (world, 128.0, 0.0, 128.0)
> Exception in thread "Nukkit Asynchronous Task Handler #5" java.lang.NullPointerException
        at cn.nukkit.level.format.generic.BaseChunk.setBlock(BaseChunk.java:67)
        at cn.nukkit.level.format.generic.BaseChunk.setBlock(BaseChunk.java:60)
        at cn.nukkit.level.generator.Normal.generateChunk(Normal.java:177)
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:84)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:22)        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
readPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:22)        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:84)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:22)        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by xpyctum** [comment]
Level type?

**Comment by Pub4Game** [comment]
This is standard world generated Nukkit

**Comment by xpyctum** [comment]
@Pub4Game Get this same on anvil type

**Comment by MrPowerGamerBR** [comment]
@xpyctum same here, I get this error if the level type is Anvil.
