### ISSUE TITLE
Custom generator throws NPE

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#406]
Hello!
May be I'm doing something wrong, but I'm afraid it's a nukkit issue.
I'm trying to create simple generator:
```
package ru.nukkit.emptyworld;

import cn.nukkit.Server;
import cn.nukkit.block.Block;
import cn.nukkit.level.ChunkManager;
import cn.nukkit.level.generator.Generator;
import cn.nukkit.math.NukkitRandom;
import cn.nukkit.math.Vector3;

import java.util.Map;

public class EmptyGenerator extends Generator {

    private final String NAME = "emptyworld";
    private ChunkManager chunkManager;
    private boolean debug;


    public EmptyGenerator(Map<String, Object> options) {
    }

    @Override
    public int getId() {
        return TYPE_INFINITE;
    }

    @Override
    public void init(ChunkManager chunkManager, NukkitRandom nukkitRandom) {
        this.chunkManager = chunkManager;
        this.debug = true;
    }

    @Override
    public void generateChunk(int chX, int chZ) {
        try {
            for  (int x=0;x<=15;x++)
                for  (int z=0;z<=15;z++){
                    int color = x+z;
                    if (color>=16) color = 15;
                    this.chunkManager.getChunk(chX, chX).setBlock(x,1,z, Block.WOOL,color);
                }
        } catch (Exception e){
            Server.getInstance().getLogger().info("Failed to generate chunk "+chX+", "+ chZ);
            if (debug) {
                e.printStackTrace();
                debug = false; // all errors are same - one stack trace will be enough
            }
        }
    }

    @Override
    public void populateChunk(int i, int i1) {

    }

    @Override
    public Map<String, Object> getSettings() {
        return null;
    }

    @Override
    public String getName() {
        return NAME;
    }

    @Override
    public Vector3 getSpawn() {
        return new Vector3(128,65,128);
    }

    @Override
    public ChunkManager getChunkManager() {
        return chunkManager;
    }
}

```

After server start I see error messages in console:

```
07:23:36 [INFO] Failed to generate chunk 5, 10
> java.lang.NullPointerException
        at ru.nukkit.emptyworld.EmptyGenerator.generateChunk(EmptyGenerator.java:40)
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:84)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
07:23:36 [INFO] Failed to generate chunk 4, 9
07:23:36 [INFO] Failed to generate chunk 5, 9
07:23:36 [INFO] Failed to generate chunk 6, 9
07:23:36 [INFO] Failed to generate chunk 4, 10
07:23:36 [INFO] Failed to generate chunk 6, 10
07:23:36 [INFO] Failed to generate chunk 4, 11
07:23:36 [INFO] Failed to generate chunk 5, 11
07:23:36 [INFO] Failed to generate chunk 6, 11
```
And what was generated:
![Generated only chunks where chunk's x equals to z](https://dl.dropboxusercontent.com/u/64799811/%21%D0%A0%D0%B0%D0%B7%D0%BD%D0%BE%D0%B5/nukkit-custom-generator.png)

You can see that only chunks with equal X and Z generated. Other chunks throws NPE during generation.

**Comment by xpyctum** [comment]
@fromgate LOL, good world :D

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/16710522/379308ba-463a-11e6-9de1-0a9e72b7d84c.png)
:D

```
/**
 * Created by Pub4Game on 10.07.2016.
 */
public class Generator extends cn.nukkit.level.generator.Generator {
    
    private final String NAME = "emptyworld";
    private ChunkManager level;
    private BaseFullChunk chunk;

    public Generator(Map<String, Object> options) {
    }

    @Override
    public int getId() {
        return TYPE_INFINITE;
    }

    @Override
    public void init(ChunkManager chunkManager, NukkitRandom nukkitRandom) {
        this.level = chunkManager;
        this.chunk = null;
    }

    @Override
    public void generateChunk(int chunkX, int chunkZ) {
        if (this.chunk == null) {
            this.chunk = this.level.getChunk(chunkX, chunkZ).clone();
            this.chunk.setGenerated();
            int c = Biome.getBiome(Biome.FOREST).getColor();
            int R = c >> 16;
            int G = (c >> 8) & 0xff;
            int B = c & 0xff;

            for (int Z = 0; Z < 16; ++Z) {
                for (int X = 0; X < 16; ++X) {
                    this.chunk.setBiomeId(X, Z, Biome.FOREST);
                    this.chunk.setBiomeColor(X, Z, R, G, B);
                    int color = X + Z;
                    if (color >= 16) color = 15;
                    this.chunk.setBlock(X, 1, Z, Block.WOOL, color);
                }
            }
        }
        BaseFullChunk chunk = this.chunk.clone();
        chunk.setX(chunkX);
        chunk.setZ(chunkZ);
        this.level.setChunk(chunkX, chunkZ, chunk);
    }

    @Override
    public void populateChunk(int i, int i1) {

    }

    @Override
    public Map<String, Object> getSettings() {
        return null;
    }

    @Override
    public String getName() {
        return NAME;
    }

    @Override
    public Vector3 getSpawn() {
        return new Vector3(128, 65, 128);
    }

    @Override
    public ChunkManager getChunkManager() {
        return level;
    }
}
```

**Comment by Tee7even** [comment]
@Pub4Game is it really fixed or not accuring anymore?

**Comment by Pub4Game** [comment]
Yes, the world generator works great.

**Comment by KakesInfo** [comment]
Where to use the Generator ?

**Comment by 110EIm** [comment]
@KakesInfo When we make a world which has special features(ex: skygrid, island)

**Comment by KakesInfo** [comment]
I talked about where to use the Generator child class ?

**Comment by Snake1999** [comment]
@KakesInfo If possible, we can continue this topic in the forum http://forums.nukkit.io/
