### ISSUE TITLE
Anvil Save Error

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Nukkit/Nukkit#407]
```
10:09:23 [ERROR] Erro ao descarregar o chunk: java.lang.RuntimeException: java.l
ang.IndexOutOfBoundsException: Index: 7, Size: 6
10:09:23 [ALERT] java.lang.RuntimeException: java.lang.IndexOutOfBoundsException
: Index: 7, Size: 6
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:276)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2283)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2247)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2516)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2493)
        at cn.nukkit.level.Level.doTick(Level.java:590)
        at cn.nukkit.Server.checkTickUpdates(Server.java:880)
        at cn.nukkit.Server.tick(Server.java:942)
        at cn.nukkit.Server.tickProcessor(Server.java:745)
        at cn.nukkit.Server.start(Server.java:725)
        at cn.nukkit.Server.<init>(Server.java:429)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.IndexOutOfBoundsException: Index: 7, Size: 6
        at java.util.ArrayList.rangeCheckForAdd(Unknown Source)
        at java.util.ArrayList.add(Unknown Source)
        at cn.nukkit.nbt.tag.ListTag.add(ListTag.java:78)
        at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:314)
        at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.jav
a:143)
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:274)
        ... 11 more

10:12:39 [ERROR] Erro ao descarregar o chunk: java.lang.RuntimeException: java.l
ang.IndexOutOfBoundsException: Index: 6, Size: 5
10:12:39 [ALERT] java.lang.RuntimeException: java.lang.IndexOutOfBoundsException
: Index: 6, Size: 5
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:276)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2283)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2247)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2516)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2493)
        at cn.nukkit.level.Level.doTick(Level.java:590)
        at cn.nukkit.Server.checkTickUpdates(Server.java:880)
        at cn.nukkit.Server.tick(Server.java:942)
        at cn.nukkit.Server.tickProcessor(Server.java:745)
        at cn.nukkit.Server.start(Server.java:725)
        at cn.nukkit.Server.<init>(Server.java:429)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.IndexOutOfBoundsException: Index: 6, Size: 5
        at java.util.ArrayList.rangeCheckForAdd(Unknown Source)
        at java.util.ArrayList.add(Unknown Source)
        at cn.nukkit.nbt.tag.ListTag.add(ListTag.java:78)
        at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:314)
        at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.jav
a:143)
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:274)
        ... 11 more
```

This WASN'T a world generated with Nukkit (generated with Spigot 1.8.8), when I tried generating a Anvil world with Nukkit the MCPE client was stuck on the loading world screen (with the loading bar filled 1/4).

While this error appeared, the world loaded without any errors (Didn't test if the world was saved to disk tho).
![http://i.imgur.com/amR4n9K.png](http://i.imgur.com/amR4n9K.png)

**Comment by MagicDroidX** [comment]
Alright. Plz upload the world.

**Comment by MrPowerGamerBR** [comment]
@MagicDroidX 

https://dl.dropboxusercontent.com/u/93092749/Nukkit_Anvil_World.zip?dl=1

Coords: -150.0, 77.0, -147.0

**Comment by MagicDroidX** [comment]
Thanks to the GFW, I cannot download it from dropbox but I have made a try to fix this in https://github.com/Nukkit/Nukkit/commit/2a2549e6eb939325a9ff56f1fcc5242bf4b150a5.
Please check it. Thanks!

**Comment by MrPowerGamerBR** [comment]
@MagicDroidX if you need I can upload the world to my web server.

Anyway, I will test the world again with the new build, the problem is I don't know the exact position this bugs starts happening (it happens when I load a chunk and then that chunk with the NBT data is unloaded).

**Comment by MrPowerGamerBR** [comment]
@MagicDroidX I didn't get the issue again (and, for some reason, now when I tried to generate a Anvil map, it worked)
