### ISSUE TITLE
Error during player is damaging under water 

### ISSUE THREAD

**Issue by gacus007** [Nukkit/Nukkit#467]
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:24)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:50)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.entity.Entity.attack(Entity.java:651)
        at cn.nukkit.entity.EntityLiving.attack(EntityLiving.java:107)
        at cn.nukkit.Player.attack(Player.java:3471)
        at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:203)
        at cn.nukkit.Player.onUpdate(Player.java:1400)
        at cn.nukkit.level.Level.doTick(Level.java:607)
        at cn.nukkit.Server.checkTickUpdates(Server.java:891)
        at cn.nukkit.Server.tick(Server.java:953)
        at cn.nukkit.Server.tickProcessor(Server.java:756)
        at cn.nukkit.Server.start(Server.java:736)
        at cn.nukkit.Server.<init>(Server.java:440)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Snake1999** [comment]
Where is the *full* callstack? I didn't find out the cause from what you gave us :3

**Comment by MagicDroidX** [comment]
There should be an exception when one of your EventHandler is being executed. Check your plugins' codes.

**Comment by MrPowerGamerBR** [comment]
I'm not at home at the moment but I had a similar error.

When using EntityDamageByEntityEvent, a error constantly was shown in the
console when the player was damaged by fire, I even used "e.getEntity()
instanceof Player and e.getEntity().getDamager() instanceof Player" but the
error still happened.
Em 8 de fev de 2016 1:06 PM, "极夜暗芒使" <notifications@github.com> escreveu:
