### ISSUE TITLE
Config - NoSuchMethodError

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#469]
```
 Exception in thread "main" java.lang.NoSuchMethodError: cn.nukkit.utils.Config.getString(Ljava/lang/String;)Ljava/lang/String;
        at NP_Core.Protect.RegionGuard.checkPos(RegionGuard.java:111)
        at NP_Core.Protect.RegionGuard.<init>(RegionGuard.java:58)
        at NP_Core.NP_Core.onEnable(NP_Core.java:105)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:448)
        at cn.nukkit.Server.enablePlugin(Server.java:592)
        at cn.nukkit.Server.enablePlugins(Server.java:581)
        at cn.nukkit.Server.<init>(Server.java:432)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
```
```java
this.owner.getLogger().info(this.rg.get("xpyc_team.min", ""));
```
![image](https://cloud.githubusercontent.com/assets/6584811/12867335/842e04ce-cd0c-11e5-8991-c0fc4279d4fe.png)

**Comment by MrPowerGamerBR** [comment]
Update your Nukkit version to the latest build.
Em 6 de fev de 2016 13:02, "Oleg Basalyga" <notifications@github.com>
escreveu:

**Comment by Snake1999** [comment]
I remembered getString in Config is added few days ago. Your Nukkit might not up to date. Just update your Nukkit :D

**Comment by xpyctum** [comment]
I will check :D 
Sorry...
