### ISSUE TITLE
MovePlayer -> sendPosition Error?

### ISSUE THREAD

**Issue by boybook** [Nukkit/Nukkit#475]
> java.lang.NullPointerException
        at cn.nukkit.Player.sendPosition(Player.java:3501)
        at cn.nukkit.Player.sendPosition(Player.java:3495)
        at cn.nukkit.Player.sendPosition(Player.java:3491)
        at cn.nukkit.Player.handleDataPacket(Player.java:1789)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:949)
        at cn.nukkit.Server.tickProcessor(Server.java:756)
        at cn.nukkit.Server.start(Server.java:736)
        at cn.nukkit.Server.<init>(Server.java:440)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
23:18:07 [DEBUG] Packet cn.nukkit.network.protocol.MovePlayerPacket 0x9D000000000000000042FC8403BEF51224C264594043825EF843825EF8000000000000

**Comment by MagicDroidX** [comment]
I need the codes in the line 3501.
