### ISSUE TITLE
[NOTICE] Blocked 192.168.1.x for 5 seconds

### ISSUE THREAD

**Issue by haniokasai** [Nukkit/Nukkit#48]
when i put or tap block,nukkit says" Blocked 192.168.1.x for 5 seconds".
is it a bug?

19:41:34 [INFO] Loading nukkit.yml...
19:41:35 [INFO] Loading server properties...
19:41:35 [INFO] Selected English (eng) as the base language
19:41:35 [INFO] Starting Minecraft: PE server version v0.12.3 alpha
19:41:35 [INFO] Opening server on 0.0.0.0:19132
19:41:35 [INFO] This server is running Nukkit version 1.0dev "蘋果(Apple)派(Pie)" (API 1.0.0)
19:41:35 [INFO] Nukkit is distributed under the LGPL License
19:41:35 [NOTICE] Level "world" not found
19:41:35 [INFO] Preparing level "world"
19:41:35 [NOTICE] Spawn terrain for level "world" is being generated in the background
19:41:35 [INFO] Starting GS4 status listener
19:41:35 [INFO] Setting query port to 19132
19:41:35 [INFO] Query running on 0.0.0.0:19132
19:41:35 [INFO] Default game type: Survival Mode
19:41:35 [INFO] Done (0.863s)! For help, type "help" or "?"
19:42:13 [INFO] haniokasai[/192.168.1.9:19132] logged in with entity id 1 at (world, 125.0016, 72.0, 132.5499)
19:42:15 [INFO] haniokasai joined the game
> java.lang.NullPointerException
        at cn.nukkit.math.Vector3.equals(Vector3.java:240)
        at cn.nukkit.level.Level.getNearbyEntities(Level.java:1554)
        at cn.nukkit.level.Level.getNearbyEntities(Level.java:1539)
        at cn.nukkit.level.Level.setBlock(Level.java:1154)
        at cn.nukkit.block.Block.place(Block.java:505)
        at cn.nukkit.level.Level.useItemOn(Level.java:1468)
        at cn.nukkit.Player.handleDataPacket(Player.java:1923)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:899)
        at cn.nukkit.Server.tickProcessor(Server.java:722)
        at cn.nukkit.Server.start(Server.java:703)
        at cn.nukkit.Server.<init>(Server.java:399)
        at cn.nukkit.Nukkit.main(Nukkit.java:61)
19:42:17 [NOTICE] Blocked 192.168.1.9 for 5 seconds
19:42:27 [INFO] haniokasai left the game
19:42:27 [INFO] haniokasai[/192.168.1.9:19132] logged out due to timeout

**Comment by Snake1999** [comment]
I also found this bug today, it might be some objects not loaded correctly. Will be fixed soon :D

**Comment by Snake1999** [comment]
Note that block xxx address is a self-protect that  when a player hacks or using mods, or nukkit core have some problems when this player does some actions, the Nukkit server won't crash beacuse of it. This can protect your server and keep it always online.

**Comment by haniokasai** [comment]
Noted with thanks　:)
and im making japanese nukkit unofficial forum!

**Comment by Snake1999** [comment]
Awesome :D @haniokasai
