### ISSUE TITLE
Undead player ? 

### ISSUE THREAD

**Issue by Guillaume351** [Nukkit/Nukkit#524]
Hello,
Sometime, when a player dies, I get this error :
>   > java.lang.NullPointerException
 at cn.nukkit.Player.kill(Player.java:3346)
        at cn.nukkit.entity.Entity.setHealth(Entity.java:658)
        at cn.nukkit.entity.EntityLiving.setHealth(EntityLiving.java:66)
        at cn.nukkit.Player.setHealth(Player.java:3383)
        at cn.nukkit.entity.Entity.attack(Entity.java:621)
        at cn.nukkit.entity.EntityLiving.attack(EntityLiving.java:107)
        at cn.nukkit.Player.attack(Player.java:3513)
        at cn.nukkit.Player.handleDataPacket(Player.java:2450)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:949)
        at cn.nukkit.Server.tickProcessor(Server.java:756)
        at cn.nukkit.Server.start(Server.java:736)
        at cn.nukkit.Server.<init>(Server.java:440)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
18:56:21 [NOTICE] Blocked 94.227.84.170 for 5 seconds

The player that dies get disconnected from timeout. When he reconnects, he has kept his inventory (even if it has been dropped) and is full life.

EDIT ; player is not always disconnected. He is sometime stuck on place

**Comment by Guillaume351** [comment]
Oops- my fault
