### ISSUE TITLE
Anvil Error

### ISSUE THREAD

**Issue by M4Gn1T** [Nukkit/Nukkit#535]
Well, i installed MCPC map and got the error:
2016-2-23 15:47:03 [ALERT] java.lang.RuntimeException: java.io.EOFException
	at cn.nukkit.level.format.anvil.Anvil.loadChunk(Anvil.java:238)
	at cn.nukkit.level.format.anvil.Anvil.getChunk(Anvil.java:297)
	at cn.nukkit.level.format.anvil.Anvil.getChunk(Anvil.java:29)
	at cn.nukkit.level.Level.loadChunk(Level.java:2164)
	at cn.nukkit.level.Level.getChunk(Level.java:1900)
	at cn.nukkit.level.Level.populateChunk(Level.java:2390)
	at cn.nukkit.level.Level.populateChunk(Level.java:2381)
	at cn.nukkit.Player.sendNextChunk(Player.java:600)
	at cn.nukkit.Player.checkNetwork(Player.java:1449)
	at cn.nukkit.Server.tick(Server.java:956)
	at cn.nukkit.Server.tickProcessor(Server.java:756)
	at cn.nukkit.Server.start(Server.java:736)
	at cn.nukkit.Server.<init>(Server.java:440)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readInt(RandomAccessFile.java:803)
	at cn.nukkit.level.format.anvil.RegionLoader.readChunk(RegionLoader.java:44)
	at cn.nukkit.level.format.anvil.Anvil.loadChunk(Anvil.java:236)
	... 13 more

What should i do next?

**Comment by MrPowerGamerBR** [comment]
That's a Anvil error, not a MCRegion one.
Em 23 de fev de 2016 13:17, "M4Gn1T" <notifications@github.com> escreveu:

**Comment by M4Gn1T** [comment]
And what shuold i do?

**Comment by MrPowerGamerBR** [comment]
You changed the map format to Anvil in the config.yml, right?

I already used Anvil maps in Nukkit successfully before, maybe it is a
problem in your map.
Em 23 de fev de 2016 13:24, "M4Gn1T" <notifications@github.com> escreveu:

**Comment by M4Gn1T** [comment]
Ok, i changed to anvil but it seems doesn`t work
Can i give u my map somehow for test?

**Comment by MrPowerGamerBR** [comment]
@M4Gn1T I'm not from the Nukkit development team, I'm just somebody who uses Nukkit and reports some bugs.

But sharing the map would be useful so somebody from the Nukkit development team can see what it is the issue. ;)

**Comment by Snake1999** [comment]
Seems another cute bug :3

**Comment by MagicDroidX** [comment]
Please upload the world.
(Don't use storage which is blocked by the **G.F.W**)

**Comment by M4Gn1T** [comment]
Well, i have already decided this issues. I export this map (with MCEdit) to another one, which Nukkit is loaded.
