### ISSUE TITLE
Cant Open server

### ISSUE THREAD

**Issue by astersx** [Nukkit/Nukkit#536]
cn.nukkit.utils.LevelException: Caused by java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at cn.nukkit.level.Level.<init>(Level.java:200)
        at cn.nukkit.Server.loadLevel(Server.java:1513)
        at cn.nukkit.Server.<init>(Server.java:414)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.io.DataInputStream.readByte(DataInputStream.java:265)
        at cn.nukkit.nbt.stream.NBTInputStream.readByte(NBTInputStream.java:53)
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:81)
        at cn.nukkit.nbt.NBTIO.read(NBTIO.java:75)
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:98)
        at cn.nukkit.level.format.generic.BaseLevelProvider.<init>(BaseLevelProvider.java:36)
        at cn.nukkit.level.format.anvil.Anvil.<init>(Anvil.java:36)
        ... 8 more

        at cn.nukkit.level.Level.<init>(Level.java:202)
        at cn.nukkit.Server.loadLevel(Server.java:1513)
        at cn.nukkit.Server.<init>(Server.java:414)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

22:00:48 [EMERGENCY] No default level has been loaded
22:00:48 [INFO] Stopping other threads

**Comment by astersx** [comment]
The map was auto generated so not my fault

**Comment by MagicDroidX** [comment]
The file may be broken.
