### ISSUE TITLE
Block Coblestone error

### ISSUE THREAD

**Issue by robozeri** [Nukkit/Nukkit#57]
When you are looking to place blocks from this error
 java.lang.NullPointerException
        at cn.nukkit.math.Vector3.equals(Vector3.java:240)
        at cn.nukkit.level.Level.getNearbyEntities(Level.java:1554)
        at cn.nukkit.level.Level.getNearbyEntities(Level.java:1539)
        at cn.nukkit.level.Level.setBlock(Level.java:1154)
        at cn.nukkit.block.Block.place(Block.java:505)
        at cn.nukkit.level.Level.useItemOn(Level.java:1468)
        at cn.nukkit.Player.handleDataPacket(Player.java:1923)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:899)
        at cn.nukkit.Server.tickProcessor(Server.java:722)
        at cn.nukkit.Server.start(Server.java:703)
        at cn.nukkit.Server.<init>(Server.java:399)
        at cn.nukkit.Nukkit.main(Nukkit.java:61)

**Comment by Angelic47** [comment]
Now bugs was fixed :-D
Nukkit is not finished yet so there is no coblestone in nukkit. However, now you can also placing coblestone without any problems. Just using newest nukkit instead. Now nukkit is updating so quickly and may you need to build jar by yourself when you need.

**Comment by MagicDroidX** [comment]
@caoli5288 :D Nice Packet

**Comment by robozeri** [comment]
ok now I compiled everything is solved, we mark all bugs i love nukkit
