### ISSUE TITLE
Chunk sending / Server bug ?

### ISSUE THREAD

**Issue by Guillaume351** [Nukkit/Nukkit#582]
Hello,
The server works fine for a few minutes.

Then after 2 - 5 minutes, if I die (I do pvp on it), you'll be teleported in void and stuck, world will not load. I respawn correctly if I die after multiple time before 2 - 5 minutes. Moreover, if I disconnect and try to join again with any username, the loading progress bar will be stuck at 0%.

If I try to stop server after this bug : 

> 
18:17:28 [ALERT] java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
        at cn.nukkit.level.Level.unload(Level.java:463)
        at cn.nukkit.Server.unloadLevel(Server.java:1499)
        at cn.nukkit.Server.forceShutdown(Server.java:693)
        at cn.nukkit.Server.start(Server.java:741)
        at cn.nukkit.Server.<init>(Server.java:444)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

18:17:28 [EMERGENCY] Exception happened while shutting down, exit the process
18:17:28 [EMERGENCY] RakNet crashed!

Edit : After that bug, if the player respawn and is stuck in the void, if I do /list, he is not displayed in the player list. However, if he disconnects, it will show the message to tell he leaved the game.

**Comment by Guillaume351** [comment]
The second part of the bug is fixed (error when shutting down server), but not the main problem : after respawning, players are still stuck in void and removed from playerlist (if I do "/list"), but still connected to the server
