### ISSUE TITLE
Error with Anvil world

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#583]
```
[ALERT] java.lang.RuntimeException: java.io.EOFException
	at cn.nukkit.level.format.anvil.Anvil.loadChunk(Anvil.java:238)
	at cn.nukkit.level.format.anvil.Anvil.getChunk(Anvil.java:297)
	at cn.nukkit.level.format.anvil.Anvil.getChunk(Anvil.java:29)
	at cn.nukkit.level.Level.loadChunk(Level.java:2236)
	at cn.nukkit.level.Level.getChunk(Level.java:1972)
	at cn.nukkit.level.generator.task.PopulationTask.<init>(PopulationTask.java:32)
	at cn.nukkit.level.Level.populateChunk(Level.java:2485)
	at cn.nukkit.level.Level.populateChunk(Level.java:2453)
	at cn.nukkit.Player.sendNextChunk(Player.java:600)
	at cn.nukkit.Player.checkNetwork(Player.java:1464)
	at cn.nukkit.Server.tick(Server.java:960)
	at cn.nukkit.Server.tickProcessor(Server.java:760)
	at cn.nukkit.Server.start(Server.java:740)
	at cn.nukkit.Server.<init>(Server.java:444)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readInt(RandomAccessFile.java:803)
	at cn.nukkit.level.format.anvil.RegionLoader.readChunk(RegionLoader.java:44)
	at cn.nukkit.level.format.anvil.Anvil.loadChunk(Anvil.java:236)
	... 14 more

[ALERT] java.lang.RuntimeException: java.io.IOException: Negative seek offset
	at cn.nukkit.level.format.anvil.Anvil.loadChunk(Anvil.java:238)
	at cn.nukkit.level.format.anvil.Anvil.getChunk(Anvil.java:297)
	at cn.nukkit.level.format.anvil.Anvil.getChunk(Anvil.java:29)
	at cn.nukkit.level.Level.loadChunk(Level.java:2236)
	at cn.nukkit.level.Level.getChunk(Level.java:1972)
	at cn.nukkit.level.generator.task.PopulationTask.<init>(PopulationTask.java:32)
	at cn.nukkit.level.Level.populateChunk(Level.java:2485)
	at cn.nukkit.level.Level.populateChunk(Level.java:2453)
	at cn.nukkit.Player.sendNextChunk(Player.java:600)
	at cn.nukkit.Player.checkNetwork(Player.java:1464)
	at cn.nukkit.Server.tick(Server.java:960)
	at cn.nukkit.Server.tickProcessor(Server.java:760)
	at cn.nukkit.Server.start(Server.java:740)
	at cn.nukkit.Server.<init>(Server.java:444)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.io.IOException: Negative seek offset
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:555)
	at cn.nukkit.level.format.anvil.RegionLoader.readChunk(RegionLoader.java:43)
	at cn.nukkit.level.format.anvil.Anvil.loadChunk(Anvil.java:236)
	... 14 more
```

LINK MAP : http://forum.darkando.com/Swordhaven.zip

**Comment by MagicDroidX** [comment]
Works fine for me.
