### ISSUE TITLE
Error with loading plugins

### ISSUE THREAD

**Issue by GreenNature-MC-Server** [Nukkit/Nukkit#623]
What my console say when i start the server:

`> Exception in thread "main" java.lang.NoSuchMethodError: cn.nukkit.utils.Config.setNested(Ljava/lang/String;Ljava/lang/Object;)V
        at VoteBan.MainClass.onEnable(MainClass.java:25)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:452)
        at cn.nukkit.Server.enablePlugin(Server.java:600)
        at cn.nukkit.Server.enablePlugins(Server.java:589)
        at cn.nukkit.Server.<init>(Server.java:440)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)`

Is it my fault and i would can fix it or is it a bug? :(

![screenshot 384](https://cloud.githubusercontent.com/assets/14999129/13912077/51e9ecea-ef39-11e5-9e61-d309b2d76116.png) 

(For information: a.sh is the start .sh file and in the start file is "java -Xmx2048M -jar nukkit.jar -o true" and i'm using Linux on my server)

**Comment by GreenNature-MC-Server** [comment]
Oh Sorry! I found the mistake! It was the dump plugin named VoteBan...

**Comment by fromgate** [comment]
@GreenNature-MC-Server You can contact plugin developer here: http://nukkit.ru/resources/voteban.22/

There's an error related Nukkit API changes. Plugin author must update it.
