### ISSUE TITLE
[ALERT] java.lang.reflect.InvocationTargetException Error when a player writing something

### ISSUE THREAD

**Issue by GreenNature-MC-Server** [Nukkit/Nukkit#624]
If a player write something there is this error everytime

`[ALERT] java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:25)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:50)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:557)
        at cn.nukkit.Player.handleDataPacket(Player.java:2618)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:956)
        at cn.nukkit.Server.tickProcessor(Server.java:763)
        at cn.nukkit.Server.start(Server.java:743)
        at cn.nukkit.Server.<init>(Server.java:444)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.NullPointerException
        at M4Gn1T.Chat.onChat(Chat.java:53)
        ... 16 more`

![screenshot 386](https://cloud.githubusercontent.com/assets/14999129/13917167/6e460880-ef5f-11e5-896d-1f0530130fd5.png)

OS: Linux

**Comment by xpyctum** [comment]
your error, not nukkit.

**Comment by GreenNature-MC-Server** [comment]
And how can i fix it?

**Comment by xpyctum** [comment]
fix your plugin.

**Comment by Pub4Game** [comment]
Remove plugin from chat

**Comment by GreenNature-MC-Server** [comment]
Which plugin and i have 15 plugins in the server 😂

**Comment by xpyctum** [comment]
M4Gn1T.Chat

**Comment by fromgate** [comment]
@GreenNature-MC-Server 
You can contact author here: http://nukkit.ru/resources/chat.68/

**Comment by GreenNature-MC-Server** [comment]
Ok the Plugin Chat+ was it...
Many plugins on Nukkit are very experimental... 😂
