### ISSUE TITLE
plugin load error

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#675]
15:16:34 [ALERT] java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.util.regex.Matcher.reset(Unknown Source)
        at java.util.regex.Matcher.<init>(Unknown Source)
        at java.util.regex.Pattern.matcher(Unknown Source)
        at java.util.regex.Pattern.matches(Unknown Source)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:187)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:131)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:123)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:119)
        at cn.nukkit.Server.<init>(Server.java:371)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Snake1999** [comment]
Seems not a Nukkit issue. Ask your plugin author to fix his/her bugs.
