### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by mfmfneko** [Nukkit/Nukkit#71]
(Sorry, I'm using the Google Translation.)
Hello! I cannot run the Nukkit.
1. "gradle compileJava"
2. "java -jar Nukkit.jar"
3. Error: no main manifest attribute

**Comment by WilliamGao1** [comment]
Try to create a MANIFEST.MF file

**Comment by haniokasai** [comment]
use maven, i could complete build.

**Comment by mfmfneko** [comment]
@WilliamGao1 Thank you for the reply!
It did not work well.

I've added this code (to build.gradle)
```
jar {
	manifest {
		attributes "Main-Class" : "cn.nukkit.Nukkit"
	}
}
```
but, error...
```
[mfmfneko@xxx-xxx-xxx-xxx nukkit]$ java -jar Nukkit-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/fusesource/jansi/AnsiConsole
        at cn.nukkit.utils.MainLogger.<init>(MainLogger.java:32)
        at cn.nukkit.utils.MainLogger.<init>(MainLogger.java:28)
        at cn.nukkit.Nukkit.main(Nukkit.java:59)
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.AnsiConsole
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
```

**Comment by mfmfneko** [comment]
@haniokasai I was able to solve the problem! Thanks!
