### ISSUE TITLE
Unable to place down a workbench/crafting table

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#726]
I'm unable to place a crafting table on the ground after crafting it. I'm using Minecraft Windows 10 Edition.

Steps to duplicate
-Start a completely new map in Survival. (switching gamemode may break this step!)
-Make sure your inventory is empty when you first start. (start with no previous player data)
-Get wood from a tree.
-Craft a workbench/crafting table.
-Place the item on the ground and the item will disappear within a few seconds.

22:28:28 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 0
        at cn.nukkit.Player.handleDataPacket(Player.java:2672)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:961)
        at cn.nukkit.Server.tickProcessor(Server.java:768)
        at cn.nukkit.Server.start(Server.java:748)
        at cn.nukkit.Server.<init>(Server.java:445)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

22:28:28 [NOTICE] Blocked 192.168.0.102 for 5 seconds
22:28:33 [NOTICE] Unblocked 192.168.0.102

**Comment by Pub4Game** [comment]
Dublicate https://github.com/Nukkit/Nukkit/issues/576
