### ISSUE TITLE
primed tnt exception

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#743]
16:13:15 [ALERT] java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java
:25)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java
:50)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:557)
        at cn.nukkit.entity.Entity.attack(Entity.java:628)
        at cn.nukkit.entity.item.EntityItem.attack(EntityItem.java:109)
        at cn.nukkit.level.Explosion.explodeB(Explosion.java:157)
        at cn.nukkit.entity.item.EntityPrimedTNT.explode(EntityPrimedTNT.java:14
6)
        at cn.nukkit.entity.item.EntityPrimedTNT.onUpdate(EntityPrimedTNT.java:1
28)
        at cn.nukkit.level.Level.doTick(Level.java:680)
        at cn.nukkit.Server.checkTickUpdates(Server.java:903)
        at cn.nukkit.Server.tick(Server.java:965)
        at cn.nukkit.Server.tickProcessor(Server.java:768)
        at cn.nukkit.Server.start(Server.java:748)
        at cn.nukkit.Server.<init>(Server.java:445)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.ClassCastException

**Comment by Pub4Game** [comment]
How to reproduce this?

**Comment by Creeperface01** [comment]
I think just touch tnt with flint and steel and wait for explosion :D

**Comment by Pub4Game** [comment]
I have no such error. Perhaps this is caused by the plugin.

**Comment by MagicDroidX** [comment]
There must be one plugin which was listening the event and thrown a exception in the event handler.
