### ISSUE TITLE
Cloud9 Error: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by HotFireyDeath** [Nukkit/Nukkit#771]
When running the .jar file directly (java -jar nukkit-1.0-SNAPSHOT.jar), in Cloud9 IDE, this error displays in the console:
`
Exception in thread "main" java.lang.UnsupportedClassVersionError: cn/nukkit/Nukkit : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
`

**Comment by MagicDroidX** [comment]
Update your java runtime to version 8.

**Comment by HotFireyDeath** [comment]
Oh, ok. I'll update to 1.8!
Thanks for the help!
