### ISSUE TITLE
uuid bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#783]
[ALERT] java.lang.NullPointerException
	at cn.nukkit.utils.Binary.writeUUID(Binary.java:68)
	at cn.nukkit.Player.handleDataPacket(Player.java:1782)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
	at cn.nukkit.network.Network.processInterfaces(Network.java:73)
	at cn.nukkit.Server.tick(Server.java:961)
	at cn.nukkit.Server.tickProcessor(Server.java:768)
	at cn.nukkit.Server.start(Server.java:748)
	at cn.nukkit.Server.<init>(Server.java:445)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Snake1999** [comment]
What?
