### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by karlvr** [Nukkit/Nukkit#794]
After a few minutes of game play, and perhaps an hour of server running, I run out of memory on the server.

Here is a stack trace:
```
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at cn.nukkit.utils.BinaryStream.grow(BinaryStream.java:314)
        at cn.nukkit.utils.BinaryStream.ensureCapacity(BinaryStream.java:298)
        at cn.nukkit.utils.BinaryStream.put(BinaryStream.java:83)
        at cn.nukkit.network.protocol.FullChunkDataPacket.encode(FullChunkDataPacket.java:35)
        at cn.nukkit.Server.batchPackets(Server.java:551)
        at cn.nukkit.Player.checkNetwork(Player.java:1492)
        at cn.nukkit.Server.tick(Server.java:968)
        at cn.nukkit.Server.tickProcessor(Server.java:768)
        at cn.nukkit.Server.start(Server.java:748)
        at cn.nukkit.Server.<init>(Server.java:445)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

Other stack traces I've seen have been about `ByteBuffer`s (if memory serves).

I seem to be able to reproduce it by logging in and then out, then in and out, then waiting, then in and then it crashes.

I'm happy to try any patches or to make a patch perhaps with a nudge in the right direction if anyone can give me a clue :-)

I am running with 768MB of RAM on Java 1.8.0_91 on a Raspberry Pi 2, running the latest from master (262f3ab5f73a0b95e7f460f18739d4959d93026d). Two worlds are configured, but only one used. I will try now without the second world. No plugins.

**Comment by Pub4Game** [comment]
Please try to find out more information

**Comment by karlvr** [comment]
@Pub4Game Fair enough, I will try to get some jmap output from it when it's approaching 100% memory usage. Maybe seeing which objects are consuming the memory will help point in a direction. I'm not familiar at all with the code base, but it appears that something relating to the server tick is consuming and not releasing memory... I'll report back if I can learn more.

**Comment by wasted123** [comment]
use the cmd /gc
