### ISSUE TITLE
Crash when firing a bow

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#80]
```
[INFO] Pub4Game joined the game
[DEBUG] Packet cn.nukkit.network.protocol.PlayerActionPacket 0xAB00000000000000000000000500000000000000000000000000000000
[ALERT] java.lang.NullPointerException
	at cn.nukkit.Player.handleDataPacket(Player.java:2094)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
	at cn.nukkit.network.Network.processInterfaces(Network.java:73)
	at cn.nukkit.Server.tick(Server.java:925)
	at cn.nukkit.Server.tickProcessor(Server.java:747)
	at cn.nukkit.Server.start(Server.java:728)
	at cn.nukkit.Server.<init>(Server.java:424)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

[NOTICE] Blocked 192.168.1.172 for 5 seconds
[INFO] Pub4Game left the game
[INFO] Pub4Game[/192.168.1.172:19132] logged out due to timeout
```

**Comment by Angelic47** [comment]
it seems that there must have some problems with raknet, we will fix it as soon as possible :D

**Comment by Pub4Game** [comment]
:+1:
