### ISSUE TITLE
Error when joining on the 0.15.0 branch

### ISSUE THREAD

**Issue by djpiper28** [Nukkit/Nukkit#811]
This is what appears when joining my server on the 0.15.0 beta with 0.15.0 nukkit
`[ALERT] java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at java.util.Arrays.copyOfRange(Unknown Source)
        at cn.nukkit.utils.BinaryStream.get(BinaryStream.java:75)
        at cn.nukkit.utils.BinaryStream.getShort(BinaryStream.java:122)
        at cn.nukkit.utils.BinaryStream.getString(BinaryStream.java:282)
        at cn.nukkit.utils.BinaryStream.getSkin(BinaryStream.java:239)
        at cn.nukkit.network.protocol.LoginPacket.decode(LoginPacket.java:47)
        at cn.nukkit.network.Network.processBatch(Network.java:152)
        at cn.nukkit.Player.handleDataPacket(Player.java:1730)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:137)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:73)
        at cn.nukkit.Server.tick(Server.java:961)
        at cn.nukkit.Server.tickProcessor(Server.java:768)
        at cn.nukkit.Server.start(Server.java:748)
        at cn.nukkit.Server.<init>(Server.java:445)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)`

**Comment by Pub4Game** [comment]
Nukkit for 0.15.0 yet ready.

**Comment by wasted123** [comment]
wait, where did u get nukkit for0.15.0?

**Comment by Pub4Game** [comment]
We have created a separate branch of development for 0.15.0

**Comment by wasted123** [comment]
where could I get it?

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/15914567/ac4b0f8a-2dea-11e6-98e5-893c8e1ca9c2.png)

**Comment by wasted123** [comment]
AND WHERE TO DOWNLOAD IT?

**Comment by Pub4Game** [comment]
You understand that this branch is in development? You can download source files and compile in IDEA

**Comment by Snake1999** [comment]
@wasted123 This is in development, you can try by compile by yourself. Or stop asking.

**Comment by EpicSteve33** [comment]
how you I compile it

**Comment by EpicSteve33** [comment]
@wasted123 how would I compile it?

**Comment by thebigsmileXD** [comment]
Shoghi mentioned Raknet was partly removed

**Comment by Pub4Game** [comment]
Unfortunately, I don't know what to do. These changes are too global, I hope PocketMine will release an update.

**Comment by thebigsmileXD** [comment]
https://github.com/GameCraftPE/Genisys

**Comment by thebigsmileXD** [comment]
And no way Pm will ever update again. Shoghi is developing mcpe now, and realms came out

**Comment by Snake1999** [comment]
This issue is going to be closed because our branch work should be 'secretly'. Any further discussion can be posted at our forum at forums.nukkit.io .

**Comment by Niall7459** [comment]
Servers for the win!

**Comment by j-melling** [comment]
Our branch work should be 'secretly'... great.. makes it easy for others to help
