### ISSUE TITLE
Error with AsyncTask

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#817]
```
[INFO] Выгрузка мира "world"
[DEBUG] Removing event handlers
[DEBUG] Stopping all tasks
[ALERT] java.lang.NullPointerException
    at cn.nukkit.level.format.anvil.Anvil.requestChunkCallback(Anvil.java:214)
    at cn.nukkit.level.format.anvil.Anvil$2.onCompletion(Anvil.java:160)
    at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:79)
    at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:214)
    at cn.nukkit.Server.forceShutdown(Server.java:709)
    at cn.nukkit.Server.start(Server.java:749)
    at cn.nukkit.Server.<init>(Server.java:445)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
 
[EMERGENCY] Exception happened while shutting down, exit the process
2016-6-8 22:17:32 [EMERGENCY] RakNet crashed!
```
@KMUzinCRSG

**Comment by KMUzinCRSG** [comment]
Fixed in #820
