### ISSUE TITLE
Bugs with enchantment table

### ISSUE THREAD

**Issue by GM123456789** [Nukkit/Nukkit#831]
When I put something in the enchantment table and try to enchant it, I won't get the enchant version of the thing but the original one

```
[ALERT] java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:418)
    at java.util.ArrayList.get(ArrayList.java:431)
    at cn.nukkit.inventory.EnchantInventory.onSlotChange(EnchantInventory.java:164)
    at cn.nukkit.inventory.BaseInventory.setItem(BaseInventory.java:164)
    at cn.nukkit.inventory.SimpleTransactionGroup.execute(SimpleTransactionGroup.java:139)
    at cn.nukkit.Player.handleDataPacket(Player.java:2990)
    at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:135)
    at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
    at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:61)
    at cn.nukkit.network.Network.processInterfaces(Network.java:73)
    at cn.nukkit.Server.tick(Server.java:961)
    at cn.nukkit.Server.tickProcessor(Server.java:768)
    at cn.nukkit.Server.start(Server.java:748)
    at cn.nukkit.Server.<init>(Server.java:445)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)

[DEBUG] Packet cn.nukkit.network.protocol.ContainerSetSlotPacket 0x8EB700001100000000
```

Error added @Pub4Game

**Comment by Pub4Game** [comment]
@MagicDroidX

**Comment by Snake1999** [comment]
Would you try again with latest version? 

Sorry for answering late :D

**Comment by Pub4Game** [comment]
Error confirmed.
