### ISSUE TITLE
level bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#834]
[ALERT] java.lang.NullPointerException
	at cn.nukkit.lang.BaseLang.parseTranslation(BaseLang.java:184)
	at cn.nukkit.lang.BaseLang.parseTranslation(BaseLang.java:176)
	at cn.nukkit.lang.BaseLang.translateString(BaseLang.java:139)
	at cn.nukkit.lang.BaseLang.translateString(BaseLang.java:128)
	at cn.nukkit.network.Network.processInterfaces(Network.java:81)
	at cn.nukkit.Server.tick(Server.java:961)
	at cn.nukkit.Server.tickProcessor(Server.java:768)
	at cn.nukkit.Server.start(Server.java:748)
	at cn.nukkit.Server.<init>(Server.java:445)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Creeperface01** [comment]
or server bug 
15:35:43 [INFO] Unloading level "STW5"

> 15:35:43 [CRITICAL] [Network] Stopped interface cn.nukkit.network.RakNetInterface due to null

**Comment by Creeperface01** [comment]
@Pub4Game @MagicDroidX

**Comment by onebone** [comment]
Did you build with submodule?

**Comment by Snake1999** [comment]
What?

**Comment by Creeperface01** [comment]
1. there is probably something wrong with this.provider.getSpawn().getX() 
2. there is an translation bug
