### ISSUE TITLE
Crash java.lang.IllegalArgumentException: Empty string not allowed

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#85]
```
[ERROR] Ошибка при выгрузке чанка: java.lang.IllegalArgumentException: Empty string not allowed
[ALERT] java.lang.RuntimeException: java.lang.IllegalArgumentException: Empty string not allowed
	at cn.nukkit.level.format.mcregion.McRegion.saveChunk(McRegion.java:277)
	at cn.nukkit.level.Level.unloadChunk(Level.java:2105)
	at cn.nukkit.level.Level.unloadChunk(Level.java:2069)
	at cn.nukkit.level.Level.unloadChunks(Level.java:2338)
	at cn.nukkit.level.Level.unloadChunks(Level.java:2315)
	at cn.nukkit.level.Level.doTick(Level.java:532)
	at cn.nukkit.Server.checkTickUpdates(Server.java:867)
	at cn.nukkit.Server.tick(Server.java:929)
	at cn.nukkit.Server.tickProcessor(Server.java:747)
	at cn.nukkit.Server.start(Server.java:728)
	at cn.nukkit.Server.<init>(Server.java:424)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.IllegalArgumentException: Empty string not allowed
	at cn.nukkit.nbt.tag.StringTag.<init>(StringTag.java:18)
	at cn.nukkit.nbt.tag.CompoundTag.putString(CompoundTag.java:85)
	at cn.nukkit.entity.Entity.saveNBT(Entity.java:491)
	at cn.nukkit.level.format.mcregion.Chunk.toBinary(Chunk.java:436)
	at cn.nukkit.level.format.mcregion.RegionLoader.writeChunk(RegionLoader.java:156)
	at cn.nukkit.level.format.mcregion.McRegion.saveChunk(McRegion.java:275)
	... 11 more
```

**Comment by MagicDroidX** [comment]
How can we reproduce this issue?

**Comment by Pub4Game** [comment]
Just fly forward, to generate a map

**Comment by Pub4Game** [comment]
Good job :+1:
