### ISSUE TITLE
banlist error

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#88]
```
[CRITICAL] Необработанное исключение при выполнении команды 'banlist' в banlist: java.lang.ArrayIndexOutOfBoundsException: 0
	at cn.nukkit.command.defaults.BanListCommand.execute(BanListCommand.java:40)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147)
	at cn.nukkit.Server.dispatchCommand(Server.java:599)
	at cn.nukkit.command.CommandReader.run(CommandReader.java:62)
```
```
[CRITICAL] Необработанное исключение при выполнении команды 'banlist ips' в banlist: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(Unknown Source)
	at cn.nukkit.command.defaults.BanListCommand.execute(BanListCommand.java:56)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147)
	at cn.nukkit.Server.dispatchCommand(Server.java:599)
	at cn.nukkit.command.CommandReader.run(CommandReader.java:62)
```
```
[INFO] Всего заблокирован(о) 0 игрок(ов):
[INFO] Произошла ошибка при выполнении этой команды
[CRITICAL] Необработанное исключение при выполнении команды 'banlist players' в banlist: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(Unknown Source)
	at cn.nukkit.command.defaults.BanListCommand.execute(BanListCommand.java:56)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147)
	at cn.nukkit.Server.dispatchCommand(Server.java:599)
	at cn.nukkit.command.CommandReader.run(CommandReader.java:62)
```

**Comment by Pub4Game** [comment]
Can I be your official tester? :D

**Comment by Snake1999** [comment]
@Pub4Game Of course you can! We welcome all contributions. Just find bugs and tell our group to fix it, I believe Nukkit will be stronger and more stable with you :D
