### ISSUE TITLE
NullPointerException when loading chunks...

### ISSUE THREAD

**Issue by MrGenga** [Nukkit/Nukkit#899]
### Issue description

My SkyWars plugin needs reload map by plugin. I use these algorithm:
1. Teleport all players to other world 
2. Unload level
3. Load level
### OS and versions

- Nukkit: latest
- OS: Ubuntu 16.04
- Device: VDS
### Crashdump, backtrace or other files

```
 12:53:12 [ALERT] java.lang.NullPointerException
        at cn.nukkit.level.Level.loadChunk(Level.java:2287)
        at cn.nukkit.level.Level.getChunk(Level.java:2021)
        at cn.nukkit.level.Level.populateChunk(Level.java:2514)
        at cn.nukkit.level.Level.populateChunk(Level.java:2505)
        at cn.nukkit.Player.sendNextChunk(Player.java:621)
        at cn.nukkit.Player.checkNetwork(Player.java:1501)
        at cn.nukkit.Server.tick(Server.java:980)
        at cn.nukkit.Server.tickProcessor(Server.java:776)
        at cn.nukkit.Server.start(Server.java:756)
        at cn.nukkit.Server.<init>(Server.java:452)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

**Comment by MrGenga** [comment]
I think level.getProvider() is null, but why and how to fix it?

**Comment by MrGenga** [comment]
HELP PLEASE

**Comment by Pub4Game** [comment]
If you'll write something like that, it does not speed up the fix. Instead of these useless words better to have written a type of the world, and even better gave him to me
