### ISSUE TITLE
Some error with QueryHandler

### ISSUE THREAD

**Issue by tiNsLeY799** [Nukkit/Nukkit#936]
I'm not sure how to reproduce this, but I do get these exceptions that crash the server, but do not close it.

```
2016-7-14 14:04:38 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 0
	at cn.nukkit.utils.Binary.readInt(Binary.java:232)
	at cn.nukkit.network.query.QueryHandler.handle(QueryHandler.java:89)
	at cn.nukkit.Server.handlePacket(Server.java:768)
	at cn.nukkit.network.RakNetInterface.handleRaw(RakNetInterface.java:186)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:131)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
	at cn.nukkit.network.Network.processInterfaces(Network.java:75)
	at cn.nukkit.Server.tick(Server.java:980)
	at cn.nukkit.Server.tickProcessor(Server.java:781)
	at cn.nukkit.Server.start(Server.java:761)
	at cn.nukkit.Server.<init>(Server.java:455)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

I am using Build 383 from Jenkins
I am using Windows 7

This also occurs when one IP attempts to log into my server

```
2016-7-14 14:04:38 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 0
	at cn.nukkit.utils.Binary.readInt(Binary.java:232)
	at cn.nukkit.network.query.QueryHandler.handle(QueryHandler.java:89)
	at cn.nukkit.Server.handlePacket(Server.java:768)
	at cn.nukkit.network.RakNetInterface.handleRaw(RakNetInterface.java:186)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:131)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
	at cn.nukkit.network.Network.processInterfaces(Network.java:75)
	at cn.nukkit.Server.tick(Server.java:980)
	at cn.nukkit.Server.tickProcessor(Server.java:781)
	at cn.nukkit.Server.start(Server.java:761)
	at cn.nukkit.Server.<init>(Server.java:455)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

2016-7-14 14:04:38 [NOTICE] Blocked 54.145.142.246 for 600 seconds

I've also noticed the server will also prevent players from logging into my server by keeping them "locked" on the "Building terrain" screen. The server will record their connection with the server but will not let them in. No exception or message is displayed about this.

Any insight about these errors and how can I fix them/work around them?

**Comment by Pub4Game** [comment]
> 2016-7-14 12:13:44 [ALERT] java.lang.reflect.InvocationTargetException
> at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:25)
> at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:51)
> at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:568)
> at cn.nukkit.entity.Entity.attack(Entity.java:644)
> at cn.nukkit.entity.item.EntityBoat.attack(EntityBoat.java:85)
> at cn.nukkit.Player.handleDataPacket(Player.java:2583)
> at cn.nukkit.network.Network.processPackets(Network.java:193)
> at cn.nukkit.network.Network.processBatch(Network.java:164)
> at cn.nukkit.Player.handleDataPacket(Player.java:1789)
> at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
> at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
> at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
> at cn.nukkit.network.Network.processInterfaces(Network.java:75)
> at cn.nukkit.Server.tick(Server.java:980)
> at cn.nukkit.Server.tickProcessor(Server.java:781)
> at cn.nukkit.Server.start(Server.java:761)
> at cn.nukkit.Server.(Server.java:455)
> at cn.nukkit.Nukkit.main(Nukkit.java:65)
> Caused by: java.lang.ClassCastException: cn.nukkit.entity.item.EntityBoat cannot be cast to cn.nukkit.Player
> **at ru.undefined1.xClans.xListener.playerDamageEvent(xListener.java:59)**
> ... 21 more

This error is caused by a plugin.

**Comment by tiNsLeY799** [comment]
Oh! That error! That error is caused by a player getting injured.
I'll go ahead and take down this one because this should be in a different
repository

The first exception keeps closing my server. I am not sure why it is
happening.

**Comment by Snake1999** [comment]
Maybe this issue should be closed now :)
