### ISSUE TITLE
how can i get clientID?

### ISSUE THREAD

**Issue by haniokasai** [Nukkit/Nukkit#938]
i tried getting player's clientID.but i cant.

String cid = player.getClientId().toString();

15:57:31 [ALERT] java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:25)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:51)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:568)
        at cn.nukkit.Player.doFirstSpawn(Player.java:696)
        at cn.nukkit.Player.sendNextChunk(Player.java:647)
        at cn.nukkit.Player.checkNetwork(Player.java:1529)
        at cn.nukkit.Server.tick(Server.java:994)
        at cn.nukkit.Server.tickProcessor(Server.java:781)
        at cn.nukkit.Server.start(Server.java:761)
        at cn.nukkit.Server.<init>(Server.java:455)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.NullPointerException
        at com.haniokasai.nukkit.MyAuth.Main.join(Main.java:47)
        ... 15 more

**Comment by Pub4Game** [comment]
In authorization is better to use getUniqueId() because getClientId() is now obsolete.

**Comment by Snake1999** [comment]
By decoding byte code of mojang, we found client id might be going to appear in the future. What we can do at present is to identify the client by getUniqueId()

**Comment by Pub4Game** [comment]
You can do it :3
