### ISSUE TITLE
Sometimes throw java.lang.StringIndexOutOfBoundsException in MainLogger->CommandReader.unstashLine .....

### ISSUE THREAD

**Issue by boybook** [Nukkit/Nukkit#941]
### Issue description

I've been crazy by this problem! Sometimes when I using getLogger().info()/debug().... ,the server throw java.lang.StringIndexOutOfBoundsException: String index out of range: 0.
I am carried out in multiple threads calling, but the problem is not just happening in the other thread, the main thread is also sometimes throws the same error.

### Steps to reproduce the issue

1. Try to call logger.info()/.debug()/.warning and more in different threads.
2. It is really hard to reproduce.

### OS and versions

* Nukkit: 1.0dev 
* OS: Centos7
* Device: Server?

### Crashdump, backtrace or other files

* 10:02:37 [ALERT] java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
        at java.lang.StringBuilder.charAt(StringBuilder.java:76)
        at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:545)
        at jline.console.ConsoleReader.backspace(ConsoleReader.java:1050)
        at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1036)
        at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3859)
        at cn.nukkit.command.CommandReader.unstashLine(CommandReader.java:108)
        at cn.nukkit.utils.MainLogger.send(MainLogger.java:155)
        at cn.nukkit.utils.MainLogger.send(MainLogger.java:141)
        at cn.nukkit.utils.MainLogger.info(MainLogger.java:87)
        at net.easecation.codefuncore.runnable.player.locale.GetPlayerLocaleThread.getLocale(GetPlayerLocaleThread.java:106)
        at net.easecation.codefuncore.runnable.player.locale.GetPlayerLocaleThread.onRun(GetPlayerLocaleThread.java:68)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by PeratX** [comment]
Yes, I caught this issue too.

**Comment by boybook** [comment]
23333自己刚刚修复了。。

**Comment by Pub4Game** [comment]
![image](https://cloud.githubusercontent.com/assets/11244874/17009859/7790483a-4f07-11e6-9a4c-9befff19d083.png)

**Comment by Pub4Game** [comment]
@MagicDroidX Error has not been resolved completely...
