### ISSUE TITLE
NPE in Logger Implementation (jLine unsupported Terminal)

### ISSUE THREAD

**Issue by geNAZt** [Nukkit/Nukkit#989]
### Issue description
You use the logger either by yourself or Nukkit uses it. 

### Steps to reproduce the issue
1. Put Nukkit in a non tty env (like docker)
2. Load a Level via API or use the Logger
3. Chances are that the Loger NPEs

### OS and versions
* Nukkit: 1.0dev 0.15.0alpha
* OS: CoreOS - Running Docker with Alpine Java JDK Image
* Device: Windows 10 / Android

### Crashdump, backtrace or other files
2016-8-13 10:22:07 [ALERT] java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:545)
	at jline.console.ConsoleReader.backspace(ConsoleReader.java:1050)
	at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1036)
	at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3859)
	at cn.nukkit.command.CommandReader.unstashLine(CommandReader.java:104)
	at cn.nukkit.utils.MainLogger.send(MainLogger.java:155)
	at cn.nukkit.utils.MainLogger.send(MainLogger.java:141)
	at cn.nukkit.utils.MainLogger.info(MainLogger.java:87)
	at cn.nukkit.level.Level.<init>(Level.java:224)
	at cn.nukkit.Server.loadLevel(Server.java:1551)

**Comment by minecrafter** [comment]
The logger code is just overall poor-quality - it's not even thread-safe.

**Comment by fromgate** [comment]
@geNAZt  Nice to meet you here :)

**Comment by geNAZt** [comment]
Why does everybody know me :( I can't step into one project without anyone noticing me :-1:  HELP ! :dancer:

**Comment by fromgate** [comment]
:) I just ported Yamler to Nukkit and than use it's ideas to implement SimpleConfig class in it. 
So you are the "grandfather" of Nukkit's SimpleConfig :)

**Comment by jackbentley** [comment]
Also happens when writing to the stdin (since it's using the logger).

```
say test
19:56:49 [INFO] [Server] test
Exception in thread "Console" java.lang.StringIndexOutOfBoundsException: String index out of range: 2
at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
at java.lang.StringBuilder.charAt(StringBuilder.java:76)
at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:545)
at jline.console.ConsoleReader.backspace(ConsoleReader.java:1050)
at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1036)
at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3859)
at cn.nukkit.command.CommandReader.readLine(CommandReader.java:46)
at cn.nukkit.command.CommandReader.run(CommandReader.java:61)
```

**Comment by MrPowerGamerBR** [comment]
Maybe fixed in https://github.com/Nukkit/Nukkit/commit/23b035e7f0659434b44286c0554947ef3f9f67f8
