### ISSUE TITLE
bug on startup

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#997]
### Issue description
it throws an exception if i select a language

### Steps to reproduce the issue
remove nukkit.yml and server.properties and start server

### OS and versions
all probably

### Crashdump, backtrace or other files
[ALERT] java.lang.IllegalArgumentException: content must not be null
	at cn.nukkit.utils.Utils.writeFile(Utils.java:27)
	at cn.nukkit.utils.Utils.writeFile(Utils.java:18)
	at cn.nukkit.Server.<init>(Server.java:233)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Pub4Game** [comment]
I can't reproduce this, everything works fine.
